#!/usr/bin/env sh

# Read user-defined JVM options from jvm.options file
JVM_OPTS_FILE=${JVM_OPTS_FILE:-/app/jvm.options}
for JVM_OPT in `grep "^-" ${JVM_OPTS_FILE}`
do
  JAVA_OPTS="${JAVA_OPTS} ${JVM_OPT}"
done

/usr/local/openjdk-11/bin/java ${JAVA_OPTS} -cp /app/libs/kestra.jar:/app/libs/plugins/* org.kestra.cli.App "$@"