// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _02135D614, _0509A5F04, _18F56, _2E9358, _38B0E6C0, _5Ded489f, _6667C843 } from '../sdk.gen';
import type { AiControllerDashboardGenerationPrompt, AiControllerFlowGenerationPrompt, ApiChatTurnRequest, ApiConfirmActionRequest, ApiCreateThreadRequest } from '../types.gen';

/**
 * Generate or regenerate a dashboard based on a prompt
 */
export const generateDashboard = (parameters: AiControllerDashboardGenerationPrompt, options?: Omit<Parameters<typeof _5Ded489f>[1], 'throwOnError'>) => getDataOrThrow(_5Ded489f({ aiControllerDashboardGenerationPrompt: parameters }, {
    ...options,
    parseAs: 'text',
    headers: { Accept: 'application/yaml' }
}));

/**
 * Generate or regenerate a flow based on a prompt
 */
export const generateFlow = (parameters: AiControllerFlowGenerationPrompt, options?: Omit<Parameters<typeof _6667C843>[1], 'throwOnError'>) => getDataOrThrow(_6667C843({ aiControllerFlowGenerationPrompt: parameters }, {
    ...options,
    parseAs: 'text',
    headers: { Accept: 'application/yaml' }
}));

export const providers = (options?: Omit<Parameters<typeof _02135D614>[0], 'throwOnError'>) => getDataOrThrow(_02135D614(options));

/**
 * Create a Copilot conversation thread
 */
export const create = (parameters: ApiCreateThreadRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0509A5F04>[1], 'throwOnError'>) => getDataOrThrow(_0509A5F04({ tenant: resolveTenant(parameters?.tenant), apiCreateThreadRequest: parameters }, options));

/**
 * Fetch a Copilot thread with its full message history
 */
export const get = (parameters: Omit<Parameters<typeof _18F56>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _18F56>[1], 'throwOnError'>) => getDataOrThrow(_18F56(addTenantToParameters(parameters), options));

/**
 * Open a streaming agent chat turn (SSE)
 */
export const chat = (parameters: Omit<Parameters<typeof _2E9358>[0], 'apiChatTurnRequest' | 'tenant'> & ApiChatTurnRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _2E9358>[1], 'throwOnError'>) => _2E9358({
    ...parameters,
    tenant: resolveTenant(parameters?.tenant),
    apiChatTurnRequest: parameters
}, options);

/**
 * Confirm a proposed action and stream the resumed turn (SSE)
 */
export const confirm = (parameters: Omit<Parameters<typeof _38B0E6C0>[0], 'apiConfirmActionRequest' | 'tenant'> & ApiConfirmActionRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _38B0E6C0>[1], 'throwOnError'>) => _38B0E6C0({
    ...parameters,
    tenant: resolveTenant(parameters?.tenant),
    apiConfirmActionRequest: parameters
}, options);
