// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _02135D614, _34D9Fc6c, _55628B91, _5Ded489f, _6667C843 } from '../sdk.gen';
import type { AiControllerDashboardGenerationPrompt, AiControllerFlowGenerationPrompt, AppGenerationPrompt, TestSuiteGenerationPrompt } from '../types.gen';

/**
 * Generate or regenerate an app based on a prompt (EE only)
 */
export function generateApp(parameters: AppGenerationPrompt & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _34D9Fc6c>[1], 'throwOnError'>) {
    return getDataOrThrow(_34D9Fc6c({ tenant: resolveTenant(parameters?.tenant), appGenerationPrompt: parameters }, { ...options, headers: { Accept: 'application/yaml', ...options?.headers } }));
}

/**
 * Generate or regenerate a dashboard based on a prompt
 */
export function generateDashboard(parameters: AiControllerDashboardGenerationPrompt & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _5Ded489f>[1], 'throwOnError'>) {
    return getDataOrThrow(_5Ded489f({ tenant: resolveTenant(parameters?.tenant), aiControllerDashboardGenerationPrompt: parameters }, { ...options, headers: { Accept: 'application/yaml', ...options?.headers } }));
}

/**
 * Generate or regenerate a flow based on a prompt
 */
export function generateFlow(parameters: AiControllerFlowGenerationPrompt & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _6667C843>[1], 'throwOnError'>) {
    return getDataOrThrow(_6667C843({ tenant: resolveTenant(parameters?.tenant), aiControllerFlowGenerationPrompt: parameters }, { ...options, headers: { Accept: 'application/yaml', ...options?.headers } }));
}

/**
 * Generate or regenerate a test suite based on a prompt (EE only)
 */
export function generateTestSuite(parameters: TestSuiteGenerationPrompt & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _55628B91>[1], 'throwOnError'>) {
    return getDataOrThrow(_55628B91({ tenant: resolveTenant(parameters?.tenant), testSuiteGenerationPrompt: parameters }, { ...options, headers: { Accept: 'application/yaml', ...options?.headers } }));
}

/**
 * List available AI providers
 */
export function getProviders(parameters?: Omit<Parameters<typeof _02135D614>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _02135D614>[1], 'throwOnError'>) {
    return getDataOrThrow(_02135D614(addTenantToParameters(parameters), options));
}
