// This file is auto-generated by @hey-api/openapi-ts

import { getDataOrThrow } from './shared.gen';
import { _02135D614, _5Ded489f, _6667C843 } from '../sdk.gen';
import type { AiControllerDashboardGenerationPrompt, AiControllerFlowGenerationPrompt } from '../types.gen';

/**
 * Generate or regenerate a dashboard based on a prompt
 */
export const generateDashboard = (parameters: AiControllerDashboardGenerationPrompt, options?: Omit<Parameters<typeof _5Ded489f>[1], 'throwOnError'>) => getDataOrThrow(_5Ded489f({ aiControllerDashboardGenerationPrompt: parameters }, {
    ...options,
    parseAs: 'text',
    headers: { Accept: 'application/yaml' }
}));

/**
 * Generate or regenerate a flow based on a prompt
 */
export const generateFlow = (parameters: AiControllerFlowGenerationPrompt, options?: Omit<Parameters<typeof _6667C843>[1], 'throwOnError'>) => getDataOrThrow(_6667C843({ aiControllerFlowGenerationPrompt: parameters }, {
    ...options,
    parseAs: 'text',
    headers: { Accept: 'application/yaml' }
}));

export const providers = (options?: Omit<Parameters<typeof _02135D614>[0], 'throwOnError'>) => getDataOrThrow(_02135D614(options));
