// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _01561E78a, _017382997, _01757Bba9, _0250C96B9, _025A6B662, _027Bd6C7, _02A616Fc6, _02Cb78A91, _03Be212Fb, _04A77D515, _04B4B4089, _0607Ee9E7, _06C774818, _070996808, _0742Ed768, _23A9Ef85, _2Aee0508, _3F88B347, _43354B06, _4956Ca5f, _4F085C75, _5034D9D7, _7692D6F8 } from '../sdk.gen';
import type { AppsControllerApiBulkOperationRequest } from '../types.gen';

/**
 * Delete existing apps
 */
export function bulkDeleteApps(parameters: AppsControllerApiBulkOperationRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _02Cb78A91>[1], 'throwOnError'>) {
    return getDataOrThrow(_02Cb78A91({ tenant: resolveTenant(parameters?.tenant), appsControllerApiBulkOperationRequest: parameters }, options));
}

/**
 * Create a new app
 */
export function createApp(parameters: Omit<Parameters<typeof _23A9Ef85>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _23A9Ef85>[1], 'throwOnError'>) {
    return getDataOrThrow(_23A9Ef85(addTenantToParameters(parameters), options));
}

/**
 * Search for apps from catalog
 */
export function searchAppsFromCatalog(parameters: Omit<Parameters<typeof _4F085C75>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _4F085C75>[1], 'throwOnError'>) {
    return getDataOrThrow(_4F085C75(addTenantToParameters(parameters), options));
}

/**
 * Disable existing apps
 */
export function bulkDisableApps(parameters: AppsControllerApiBulkOperationRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _2Aee0508>[1], 'throwOnError'>) {
    return getDataOrThrow(_2Aee0508({ tenant: resolveTenant(parameters?.tenant), appsControllerApiBulkOperationRequest: parameters }, options));
}

/**
 * Enable existing apps
 */
export function bulkEnableApps(parameters: AppsControllerApiBulkOperationRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0250C96B9>[1], 'throwOnError'>) {
    return getDataOrThrow(_0250C96B9({ tenant: resolveTenant(parameters?.tenant), appsControllerApiBulkOperationRequest: parameters }, options));
}

/**
 * Export apps as a ZIP archive of YAML sources.
 */
export function bulkExportApps(parameters: AppsControllerApiBulkOperationRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _7692D6F8>[1], 'throwOnError'>) {
    return getDataOrThrow(_7692D6F8({ tenant: resolveTenant(parameters?.tenant), appsControllerApiBulkOperationRequest: parameters }, options));
}

/**
 *     Import apps as a ZIP archive of yaml sources or a multi-objects YAML file.
 *     When sending a Yaml that contains one or more apps, a list of index is returned.
 *     When sending a ZIP archive, a list of files that couldn't be imported is returned.
 *
 */
export function bulkImportApps(parameters: Omit<Parameters<typeof _017382997>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _017382997>[1], 'throwOnError'>) {
    return getDataOrThrow(_017382997(addTenantToParameters(parameters), options));
}

/**
 * Open the app for the given source
 */
export function previewApp(parameters: Omit<Parameters<typeof _027Bd6C7>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _027Bd6C7>[1], 'throwOnError'>) {
    return getDataOrThrow(_027Bd6C7(addTenantToParameters(parameters), options));
}

/**
 * Dispatch for the given app source (preview).
 */
export function previewDispatchApp(parameters: Omit<Parameters<typeof _4956Ca5f>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _4956Ca5f>[1], 'throwOnError'>) {
    return getDataOrThrow(_4956Ca5f(addTenantToParameters({ body: [], ...parameters }), options));
}

/**
 * Search for apps
 */
export function searchApps(parameters: Omit<Parameters<typeof _02A616Fc6>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _02A616Fc6>[1], 'throwOnError'>) {
    return getDataOrThrow(_02A616Fc6(addTenantToParameters(parameters), options));
}

/**
 * Get all the app tags
 */
export function listTags(parameters?: Omit<Parameters<typeof _5034D9D7>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _5034D9D7>[1], 'throwOnError'>) {
    return getDataOrThrow(_5034D9D7(addTenantToParameters(parameters), options));
}

/**
 * Dispatch for a given app.
 */
export function dispatchApp(parameters: Omit<Parameters<typeof _3F88B347>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _3F88B347>[1], 'throwOnError'>) {
    return getDataOrThrow(_3F88B347(addTenantToParameters({ body: [], ...parameters }), options));
}

/**
 * Download file from an app execution
 */
export function downloadFileFromAppExecution(parameters: Omit<Parameters<typeof _03Be212Fb>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _03Be212Fb>[1], 'throwOnError'>) {
    return getDataOrThrow(_03Be212Fb(addTenantToParameters(parameters), options));
}

/**
 * Get file meta information from an app execution
 */
export function getFileMetaFromAppExecution(parameters: Omit<Parameters<typeof _070996808>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _070996808>[1], 'throwOnError'>) {
    return getDataOrThrow(_070996808(addTenantToParameters(parameters), options));
}

/**
 * Get file preview from an app execution
 */
export function getFilePreviewFromAppExecution(parameters: Omit<Parameters<typeof _01757Bba9>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _01757Bba9>[1], 'throwOnError'>) {
    return getDataOrThrow(_01757Bba9(addTenantToParameters(parameters), options));
}

/**
 * Get an event stream from a given app.
 */
export function getStreamEventsFromApp(parameters: Omit<Parameters<typeof _06C774818>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _06C774818>[1], 'throwOnError'>) {
    return _06C774818(addTenantToParameters(parameters), options);
}

/**
 * Open an app
 */
export function openApp(parameters: Omit<Parameters<typeof _04B4B4089>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _04B4B4089>[1], 'throwOnError'>) {
    return getDataOrThrow(_04B4B4089(addTenantToParameters(parameters), options));
}

/**
 * Download logs for an app execution
 */
export function getLogsFromAppExecution(parameters: Omit<Parameters<typeof _43354B06>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _43354B06>[1], 'throwOnError'>) {
    return getDataOrThrow(_43354B06(addTenantToParameters(parameters), options));
}

/**
 * Delete an existing app
 */
export function deleteApp(parameters: Omit<Parameters<typeof _01561E78a>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _01561E78a>[1], 'throwOnError'>) {
    return getDataOrThrow(_01561E78a(addTenantToParameters(parameters), options));
}

/**
 * Retrieve an app
 */
export function getApp(parameters: Omit<Parameters<typeof _04A77D515>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _04A77D515>[1], 'throwOnError'>) {
    return getDataOrThrow(_04A77D515(addTenantToParameters(parameters), options));
}

/**
 * Update an existing app
 */
export function updateApp(parameters: Omit<Parameters<typeof _0742Ed768>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0742Ed768>[1], 'throwOnError'>) {
    return getDataOrThrow(_0742Ed768(addTenantToParameters(parameters), options));
}

/**
 * Disable the app.
 */
export function disableApp(parameters: Omit<Parameters<typeof _0607Ee9E7>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0607Ee9E7>[1], 'throwOnError'>) {
    return getDataOrThrow(_0607Ee9E7(addTenantToParameters(parameters), options));
}

/**
 * Enable the app.
 */
export function enableApp(parameters: Omit<Parameters<typeof _025A6B662>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _025A6B662>[1], 'throwOnError'>) {
    return getDataOrThrow(_025A6B662(addTenantToParameters(parameters), options));
}
