// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow } from './shared.gen';
import { _012A5247d, _015E23Cc6, _0179918B5, _01F1268Ac, _03765E0A6, _04484B7Fb, _07B84118d, _1C95E03c, _55B26Dc3, _735A5032, _742A913a } from '../sdk.gen';

/**
 * Create a new asset
 */
export function createAsset(parameters: Omit<Parameters<typeof _01F1268Ac>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _01F1268Ac>[1], 'throwOnError'>) {
    return getDataOrThrow(_01F1268Ac(addTenantToParameters(parameters), options));
}

/**
 * Delete assets by asset ids
 */
export function deleteAssetsByIds(parameters: Omit<Parameters<typeof _07B84118d>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _07B84118d>[1], 'throwOnError'>) {
    return getDataOrThrow(_07B84118d(addTenantToParameters(parameters), options));
}

/**
 * Delete assets by query
 */
export function deleteAssetsByQuery(parameters: Omit<Parameters<typeof _55B26Dc3>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _55B26Dc3>[1], 'throwOnError'>) {
    return getDataOrThrow(_55B26Dc3(addTenantToParameters(parameters), options));
}

/**
 * Delete asset lineage events by query, hard-delete (purge) only
 */
export function deleteAssetLineageEventsByQuery(parameters: Omit<Parameters<typeof _735A5032>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _735A5032>[1], 'throwOnError'>) {
    return getDataOrThrow(_735A5032(addTenantToParameters(parameters), options));
}

/**
 * Search for asset lineage events
 */
export function searchAssetLineageEvents(parameters: Omit<Parameters<typeof _1C95E03c>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _1C95E03c>[1], 'throwOnError'>) {
    return getDataOrThrow(_1C95E03c(addTenantToParameters(parameters), options));
}

/**
 * Search for assets
 */
export function searchAssets(parameters: Omit<Parameters<typeof _0179918B5>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0179918B5>[1], 'throwOnError'>) {
    return getDataOrThrow(_0179918B5(addTenantToParameters(parameters), options));
}

/**
 * Delete asset usages by query, hard-delete (purge) only
 */
export function deleteAssetUsagesByQuery(parameters: Omit<Parameters<typeof _03765E0A6>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _03765E0A6>[1], 'throwOnError'>) {
    return getDataOrThrow(_03765E0A6(addTenantToParameters(parameters), options));
}

/**
 * Search for asset usages
 */
export function searchAssetUsages(parameters: Omit<Parameters<typeof _015E23Cc6>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _015E23Cc6>[1], 'throwOnError'>) {
    return getDataOrThrow(_015E23Cc6(addTenantToParameters(parameters), options));
}

/**
 * Delete an asset
 */
export function deleteAsset(parameters: Omit<Parameters<typeof _04484B7Fb>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _04484B7Fb>[1], 'throwOnError'>) {
    return getDataOrThrow(_04484B7Fb(addTenantToParameters(parameters), options));
}

/**
 * Retrieve an asset
 */
export function getAsset(parameters: Omit<Parameters<typeof _742A913a>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _742A913a>[1], 'throwOnError'>) {
    return getDataOrThrow(_742A913a(addTenantToParameters(parameters), options));
}

/**
 * Get an asset dependencies
 */
export function getAssetDependencies(parameters: Omit<Parameters<typeof _012A5247d>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _012A5247d>[1], 'throwOnError'>) {
    return getDataOrThrow(_012A5247d(addTenantToParameters(parameters), options));
}
