// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _063F9F89e, _07B13992a, _0C399441, _42E6Ce42, _58A63A9b, _5Cb8Ad7c, _67B2B91a, _757Add8f } from '../sdk.gen';
import type { AuditLogControllerFindRequest } from '../types.gen';

export function exportAuditLogsForAllTenants(parameters?: Parameters<typeof _58A63A9b>[0], options?: Omit<Parameters<typeof _58A63A9b>[1], 'throwOnError'>) {
    return getDataOrThrow(_58A63A9b(parameters, options));
}

export function searchAuditLogsForAllTenants(parameters?: Parameters<typeof _757Add8f>[0], options?: Omit<Parameters<typeof _757Add8f>[1], 'throwOnError'>) {
    return getDataOrThrow(_757Add8f(parameters, options));
}

export function getGlobalResourceDiffFromAuditLog(parameters: Parameters<typeof _0C399441>[0], options?: Omit<Parameters<typeof _0C399441>[1], 'throwOnError'>) {
    return getDataOrThrow(_0C399441(parameters, options));
}

/**
 * Export all audit logs as a streamed CSV file
 */
export function exportAuditLogs(parameters?: Omit<Parameters<typeof _07B13992a>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _07B13992a>[1], 'throwOnError'>) {
    return getDataOrThrow(_07B13992a(addTenantToParameters(parameters), options));
}

/**
 * Find a specific audit log
 */
export function findAuditLog(parameters: AuditLogControllerFindRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _42E6Ce42>[1], 'throwOnError'>) {
    return getDataOrThrow(_42E6Ce42({ tenant: resolveTenant(parameters?.tenant), auditLogControllerFindRequest: parameters }, options));
}

/**
 * Find all audit logs about a specific resource.
 */
export function listAuditLogFromResourceId(parameters: Omit<Parameters<typeof _67B2B91a>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _67B2B91a>[1], 'throwOnError'>) {
    return getDataOrThrow(_67B2B91a(addTenantToParameters(parameters), options));
}

/**
 * Search for audit logs
 */
export function searchAuditLogs(parameters?: Omit<Parameters<typeof _063F9F89e>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _063F9F89e>[1], 'throwOnError'>) {
    return getDataOrThrow(_063F9F89e(addTenantToParameters(parameters), options));
}

/**
 * Retrieve the diff between audit logs
 */
export function getResourceDiffFromAuditLog(parameters: Omit<Parameters<typeof _5Cb8Ad7c>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _5Cb8Ad7c>[1], 'throwOnError'>) {
    return getDataOrThrow(_5Cb8Ad7c(addTenantToParameters(parameters), options));
}
