// This file is auto-generated by @hey-api/openapi-ts

import { getDataOrThrow } from './shared.gen';
import { _0154B123b, _017482F6, _02530052, _03Ab0B9Aa, _0686Bb52b, _07753C84, _0B6464Af, _3E005Ec1, _4485351c, _5Fb28D2, _638062Ff, b65C1D1 } from '../sdk.gen';
import type { AuthControllerInvitationUserRequest, AuthControllerResetPasswordRequest, CreateApiTokenRequest, MeControllerApiUserDetailsRequest } from '../types.gen';

export function index(options?: Omit<Parameters<typeof _5Fb28D2>[0], 'throwOnError'>) {
    return getDataOrThrow(_5Fb28D2(options));
}

export function forgottenPassword(parameters: Parameters<typeof _0686Bb52b>[0], options?: Omit<Parameters<typeof _0686Bb52b>[1], 'throwOnError'>) {
    return getDataOrThrow(_0686Bb52b(parameters, options));
}

export function acceptInvitation(parameters: Parameters<typeof _3E005Ec1>[0], options?: Omit<Parameters<typeof _3E005Ec1>[1], 'throwOnError'>) {
    return getDataOrThrow(_3E005Ec1(parameters, options));
}

export function createFromInvitation(parameters: Omit<Parameters<typeof _638062Ff>[0], 'authControllerInvitationUserRequest'> & AuthControllerInvitationUserRequest, options?: Omit<Parameters<typeof _638062Ff>[1], 'throwOnError'>) {
    return getDataOrThrow(_638062Ff({ ...parameters, authControllerInvitationUserRequest: parameters }, options));
}

export function getCurrentUser(options?: Omit<Parameters<typeof _02530052>[0], 'throwOnError'>) {
    return getDataOrThrow(_02530052(options));
}

/**
 * Update authenticated user details
 */
export function patchCurrentUser(parameters: MeControllerApiUserDetailsRequest, options?: Omit<Parameters<typeof _07753C84>[1], 'throwOnError'>) {
    return getDataOrThrow(_07753C84({ meControllerApiUserDetailsRequest: parameters }, options));
}

export function listApiTokensForCurrentUser(options?: Omit<Parameters<typeof _0B6464Af>[0], 'throwOnError'>) {
    return getDataOrThrow(_0B6464Af(options));
}

/**
 * Create API token for the authenticated user
 */
export function createApiTokenForCurrentUser(parameters: CreateApiTokenRequest, options?: Omit<Parameters<typeof _03Ab0B9Aa>[1], 'throwOnError'>) {
    return getDataOrThrow(_03Ab0B9Aa({ createApiTokenRequest: parameters }, options));
}

export function deleteApiTokenForCurrentUser(parameters: Parameters<typeof _0154B123b>[0], options?: Omit<Parameters<typeof _0154B123b>[1], 'throwOnError'>) {
    return getDataOrThrow(_0154B123b(parameters, options));
}

export function requestCode(parameters: Parameters<typeof _4485351c>[0], options?: Omit<Parameters<typeof _4485351c>[1], 'throwOnError'>) {
    return getDataOrThrow(_4485351c(parameters, options));
}

/**
 * Change a password for given token.
 */
export function resetPassword(parameters: AuthControllerResetPasswordRequest, options?: Omit<Parameters<typeof _017482F6>[1], 'throwOnError'>) {
    return getDataOrThrow(_017482F6({ authControllerResetPasswordRequest: parameters }, options));
}

export function validatePassword(parameters: Parameters<typeof b65C1D1>[0], options?: Omit<Parameters<typeof b65C1D1>[1], 'throwOnError'>) {
    return getDataOrThrow(b65C1D1(parameters, options));
}
