// This file is auto-generated by @hey-api/openapi-ts

import { getDataOrThrow } from './shared.gen';
import { _04B5D3B49, _0561Ad6Ab, _3A626Bff, _3D7A5F48 } from '../sdk.gen';
import type { Banner } from '../types.gen';

/**
 * Create an announcement banner
 */
export function createBanner(parameters: Banner, options?: Omit<Parameters<typeof _3D7A5F48>[1], 'throwOnError'>) {
    return getDataOrThrow(_3D7A5F48({ banner: parameters }, options));
}

export function searchBanners(parameters?: Parameters<typeof _3A626Bff>[0], options?: Omit<Parameters<typeof _3A626Bff>[1], 'throwOnError'>) {
    return getDataOrThrow(_3A626Bff(parameters, options));
}

export function deleteBanner(parameters: Parameters<typeof _04B5D3B49>[0], options?: Omit<Parameters<typeof _04B5D3B49>[1], 'throwOnError'>) {
    return getDataOrThrow(_04B5D3B49(parameters, options));
}

/**
 * Update an announcement banner
 */
export function updateBanner(parameters: Omit<Parameters<typeof _0561Ad6Ab>[0], 'banner'> & Banner, options?: Omit<Parameters<typeof _0561Ad6Ab>[1], 'throwOnError'>) {
    return getDataOrThrow(_0561Ad6Ab({ ...parameters, banner: parameters }, options));
}
