// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _012A7E5A6, _0476E3Baa, _07F78209, _3759Ea4f, _7F73D1E9 } from '../sdk.gen';
import type { IamBindingControllerApiCreateBindingRequest } from '../types.gen';

/**
 * Create a binding
 */
export function createBinding(parameters: IamBindingControllerApiCreateBindingRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _7F73D1E9>[1], 'throwOnError'>) {
    return getDataOrThrow(_7F73D1E9({ tenant: resolveTenant(parameters?.tenant), iamBindingControllerApiCreateBindingRequest: parameters }, options));
}

/**
 * Create multiple bindings
 */
export function bulkCreateBinding(parameters: Omit<Parameters<typeof _07F78209>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _07F78209>[1], 'throwOnError'>) {
    return getDataOrThrow(_07F78209(addTenantToParameters(parameters), options));
}

/**
 * Search for bindings
 */
export function searchBindings(parameters: Omit<Parameters<typeof _0476E3Baa>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0476E3Baa>[1], 'throwOnError'>) {
    return getDataOrThrow(_0476E3Baa(addTenantToParameters(parameters), options));
}

/**
 * Delete a binding
 */
export function deleteBinding(parameters: Omit<Parameters<typeof _012A7E5A6>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _012A7E5A6>[1], 'throwOnError'>) {
    return getDataOrThrow(_012A7E5A6(addTenantToParameters(parameters), options));
}

/**
 * Retrieve a binding
 */
export function getBinding(parameters: Omit<Parameters<typeof _3759Ea4f>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _3759Ea4f>[1], 'throwOnError'>) {
    return getDataOrThrow(_3759Ea4f(addTenantToParameters(parameters), options));
}
