// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _01F97887a, _03Ed2B7Aa, _04E46Ba97, _04Fc707F8, _05Af20E9a, _061F11167, _07538A9A8, _21Acaa5, _433558F9, _4De682Bc, _4E249771, _53Bd89C1, _5Abe0Fe8, _5E26A2A4, _74911Bdd, e68F94f } from '../sdk.gen';
import type { BlueprintControllerApiBlueprintItemWithSource, BlueprintControllerFlowBlueprintCreateOrUpdate, BlueprintControllerUseBlueprintTemplateRequest } from '../types.gen';

/**
 * List all blueprints
 */
export function searchBlueprints(parameters: Omit<Parameters<typeof _04Fc707F8>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _04Fc707F8>[1], 'throwOnError'>) {
    return getDataOrThrow(_04Fc707F8(addTenantToParameters(parameters), options));
}

/**
 * Retrieve a blueprint
 */
export function getBlueprint(parameters: Omit<Parameters<typeof _74911Bdd>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _74911Bdd>[1], 'throwOnError'>) {
    return getDataOrThrow(_74911Bdd(addTenantToParameters(parameters), options));
}

/**
 * Retrieve a blueprint graph
 */
export function getBlueprintGraph(parameters: Omit<Parameters<typeof _4E249771>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _4E249771>[1], 'throwOnError'>) {
    return getDataOrThrow(_4E249771(addTenantToParameters(parameters), options));
}

/**
 * Retrieve a blueprint source code
 */
export function getBlueprintSource(parameters: Omit<Parameters<typeof _07538A9A8>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _07538A9A8>[1], 'throwOnError'>) {
    return getDataOrThrow(_07538A9A8(addTenantToParameters(parameters), { ...options, headers: { Accept: 'application/yaml', ...options?.headers } }));
}

/**
 * List all internal blueprints
 */
export function searchInternalBlueprints(parameters?: Omit<Parameters<typeof _21Acaa5>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _21Acaa5>[1], 'throwOnError'>) {
    return getDataOrThrow(_21Acaa5(addTenantToParameters(parameters), options));
}

/**
 * Create a new internal blueprint
 */
export function createInternalBlueprints(parameters: BlueprintControllerApiBlueprintItemWithSource & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _433558F9>[1], 'throwOnError'>) {
    return getDataOrThrow(_433558F9({ tenant: resolveTenant(parameters?.tenant), blueprintControllerApiBlueprintItemWithSource: parameters }, options));
}

/**
 * Delete an internal blueprint
 */
export function deleteInternalBlueprints(parameters: Omit<Parameters<typeof _5Abe0Fe8>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _5Abe0Fe8>[1], 'throwOnError'>) {
    return getDataOrThrow(_5Abe0Fe8(addTenantToParameters(parameters), options));
}

/**
 * Retrieve an internal blueprint
 */
export function internalBlueprint(parameters: Omit<Parameters<typeof _03Ed2B7Aa>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _03Ed2B7Aa>[1], 'throwOnError'>) {
    return getDataOrThrow(_03Ed2B7Aa(addTenantToParameters(parameters), options));
}

/**
 * Update an internal blueprint
 */
export function updateInternalBlueprints(parameters: Omit<Parameters<typeof _01F97887a>[0], 'blueprintControllerApiBlueprintItemWithSource' | 'tenant'> & BlueprintControllerApiBlueprintItemWithSource & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _01F97887a>[1], 'throwOnError'>) {
    return getDataOrThrow(_01F97887a({
        ...parameters,
        tenant: resolveTenant(parameters?.tenant),
        blueprintControllerApiBlueprintItemWithSource: parameters
    }, options));
}

/**
 * Retrieve an internal blueprint source code
 */
export function internalBlueprintFlow(parameters: Omit<Parameters<typeof _5E26A2A4>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _5E26A2A4>[1], 'throwOnError'>) {
    return getDataOrThrow(_5E26A2A4(addTenantToParameters(parameters), { ...options, headers: { Accept: 'application/yaml', ...options?.headers } }));
}

/**
 * Retrieve an flow blueprint
 */
export function getFlowBlueprint(parameters: Omit<Parameters<typeof e68F94f>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof e68F94f>[1], 'throwOnError'>) {
    return getDataOrThrow(e68F94f(addTenantToParameters(parameters), options));
}

/**
 * Create a Flow Blueprint
 */
export function createFlowBlueprint(parameters: BlueprintControllerFlowBlueprintCreateOrUpdate & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _04E46Ba97>[1], 'throwOnError'>) {
    return getDataOrThrow(_04E46Ba97({ tenant: resolveTenant(parameters?.tenant), blueprintControllerFlowBlueprintCreateOrUpdate: parameters }, options));
}

/**
 * Delete an Flow Blueprint
 */
export function deleteFlowBlueprints(parameters: Omit<Parameters<typeof _061F11167>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _061F11167>[1], 'throwOnError'>) {
    return getDataOrThrow(_061F11167(addTenantToParameters(parameters), options));
}

/**
 * Retrieve an flow blueprint
 */
export function getFlowBlueprintById(parameters: Omit<Parameters<typeof _53Bd89C1>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _53Bd89C1>[1], 'throwOnError'>) {
    return getDataOrThrow(_53Bd89C1(addTenantToParameters(parameters), options));
}

/**
 * Update a Flow Blueprint
 */
export function updateFlowBlueprint(parameters: Omit<Parameters<typeof _4De682Bc>[0], 'blueprintControllerFlowBlueprintCreateOrUpdate' | 'tenant'> & BlueprintControllerFlowBlueprintCreateOrUpdate & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _4De682Bc>[1], 'throwOnError'>) {
    return getDataOrThrow(_4De682Bc({
        ...parameters,
        tenant: resolveTenant(parameters?.tenant),
        blueprintControllerFlowBlueprintCreateOrUpdate: parameters
    }, options));
}

/**
 * Use a Flow Blueprint template to generate a Flow source
 */
export function useBlueprintTemplate(parameters: Omit<Parameters<typeof _05Af20E9a>[0], 'blueprintControllerUseBlueprintTemplateRequest' | 'tenant'> & BlueprintControllerUseBlueprintTemplateRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _05Af20E9a>[1], 'throwOnError'>) {
    return getDataOrThrow(_05Af20E9a({
        ...parameters,
        tenant: resolveTenant(parameters?.tenant),
        blueprintControllerUseBlueprintTemplateRequest: parameters
    }, options));
}
