// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow } from './shared.gen';
import { _04Fc707F8, _07538A9A8, _4E249771, _74911Bdd } from '../sdk.gen';

/**
 * List all blueprints
 */
export const searchBlueprints = (parameters: Omit<Parameters<typeof _04Fc707F8>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _04Fc707F8>[1], 'throwOnError'>) => getDataOrThrow(_04Fc707F8(addTenantToParameters(parameters), options));

/**
 * Get a blueprint
 */
export const blueprint = (parameters: Omit<Parameters<typeof _74911Bdd>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _74911Bdd>[1], 'throwOnError'>) => getDataOrThrow(_74911Bdd(addTenantToParameters(parameters), options));

/**
 * Get a blueprint graph
 */
export const blueprintGraph = (parameters: Omit<Parameters<typeof _4E249771>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _4E249771>[1], 'throwOnError'>) => getDataOrThrow(_4E249771(addTenantToParameters(parameters), options));

/**
 * Get a blueprint flow
 */
export const blueprintSource = (parameters: Omit<Parameters<typeof _07538A9A8>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _07538A9A8>[1], 'throwOnError'>) => getDataOrThrow(_07538A9A8(addTenantToParameters(parameters), {
    ...options,
    parseAs: 'text',
    headers: { Accept: 'application/yaml' }
}));
