// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow } from './shared.gen';
import { _1Aac14e } from '../sdk.gen';

/**
 * List blueprint tags matching the filter
 */
export const listBlueprintTags = (parameters: Omit<Parameters<typeof _1Aac14e>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _1Aac14e>[1], 'throwOnError'>) => getDataOrThrow(_1Aac14e(addTenantToParameters(parameters), options));
