// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow } from './shared.gen';
import { _1Aac14e, _5E2Cd58f } from '../sdk.gen';

/**
 * List blueprint tags matching the filter
 */
export function listBlueprintTags(parameters: Omit<Parameters<typeof _1Aac14e>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _1Aac14e>[1], 'throwOnError'>) {
    return getDataOrThrow(_1Aac14e(addTenantToParameters(parameters), options));
}

/**
 * List all internal blueprint tags
 */
export function internalBlueprintTags(parameters?: Omit<Parameters<typeof _5E2Cd58f>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _5E2Cd58f>[1], 'throwOnError'>) {
    return getDataOrThrow(_5E2Cd58f(addTenantToParameters(parameters), options));
}
