// This file is auto-generated by @hey-api/openapi-ts

import { getDataOrThrow } from './shared.gen';
import { _04C0A2B1b, _0F86A2E5, _1A1Ca315 } from '../sdk.gen';

export function enterMaintenance(options?: Omit<Parameters<typeof _0F86A2E5>[0], 'throwOnError'>) {
    return getDataOrThrow(_0F86A2E5(options));
}

export function exitMaintenance(options?: Omit<Parameters<typeof _1A1Ca315>[0], 'throwOnError'>) {
    return getDataOrThrow(_1A1Ca315(options));
}

export function maintenanceStatus(options?: Omit<Parameters<typeof _04C0A2B1b>[0], 'throwOnError'>) {
    return getDataOrThrow(_04C0A2B1b(options));
}
