// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _023Aa77A1, _038B7Bb77, _03A7B5Fb3, _041E86E8a, _058Ca6Ef0, _05D79D482, _0685A4799, _0753Faa00, _0D292Fc8, _1Dce40Dc, _44135A73, _5A1A40A7, _7C9D7062 } from '../sdk.gen';
import type { ApiCreateCredentialRequest, ApiUpdateCredentialRequest } from '../types.gen';

/**
 * List all tenant-level credentials
 */
export function listCredentials(parameters: Omit<Parameters<typeof _05D79D482>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _05D79D482>[1], 'throwOnError'>) {
    return getDataOrThrow(_05D79D482(addTenantToParameters(parameters), options));
}

/**
 * Create a new tenant-level credential
 */
export function createCredential(parameters: ApiCreateCredentialRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _44135A73>[1], 'throwOnError'>) {
    return getDataOrThrow(_44135A73({ tenant: resolveTenant(parameters?.tenant), apiCreateCredentialRequest: parameters }, options));
}

/**
 * Delete a credential
 */
export function deleteCredential(parameters: Omit<Parameters<typeof _7C9D7062>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _7C9D7062>[1], 'throwOnError'>) {
    return getDataOrThrow(_7C9D7062(addTenantToParameters(parameters), options));
}

/**
 * Get a credential by ID
 */
export function getCredential(parameters: Omit<Parameters<typeof _03A7B5Fb3>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _03A7B5Fb3>[1], 'throwOnError'>) {
    return getDataOrThrow(_03A7B5Fb3(addTenantToParameters(parameters), options));
}

/**
 * Update an existing credential
 */
export function updateCredential(parameters: Omit<Parameters<typeof _0753Faa00>[0], 'apiUpdateCredentialRequest' | 'tenant'> & ApiUpdateCredentialRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0753Faa00>[1], 'throwOnError'>) {
    return getDataOrThrow(_0753Faa00({
        ...parameters,
        tenant: resolveTenant(parameters?.tenant),
        apiUpdateCredentialRequest: parameters
    }, options));
}

/**
 * Test a credential connection by attempting to fetch a token
 */
export function testConnection(parameters: Omit<Parameters<typeof _058Ca6Ef0>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _058Ca6Ef0>[1], 'throwOnError'>) {
    return getDataOrThrow(_058Ca6Ef0(addTenantToParameters(parameters), options));
}

/**
 * List credentials in a namespace
 */
export function listNamespaceCredentials(parameters: Omit<Parameters<typeof _023Aa77A1>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _023Aa77A1>[1], 'throwOnError'>) {
    return getDataOrThrow(_023Aa77A1(addTenantToParameters(parameters), options));
}

/**
 * Create a credential in a namespace
 */
export function createNamespaceCredential(parameters: Omit<Parameters<typeof _041E86E8a>[0], 'apiCreateCredentialRequest' | 'tenant'> & ApiCreateCredentialRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _041E86E8a>[1], 'throwOnError'>) {
    return getDataOrThrow(_041E86E8a({
        ...parameters,
        tenant: resolveTenant(parameters?.tenant),
        apiCreateCredentialRequest: parameters
    }, options));
}

/**
 * Get inherited credentials from parent namespaces
 */
export function getInheritedCredentials(parameters: Omit<Parameters<typeof _0D292Fc8>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0D292Fc8>[1], 'throwOnError'>) {
    return getDataOrThrow(_0D292Fc8(addTenantToParameters(parameters), options));
}

/**
 * Delete a credential from a namespace
 */
export function deleteNamespaceCredential(parameters: Omit<Parameters<typeof _0685A4799>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0685A4799>[1], 'throwOnError'>) {
    return getDataOrThrow(_0685A4799(addTenantToParameters(parameters), options));
}

/**
 * Get a credential by name in a namespace
 */
export function getNamespaceCredential(parameters: Omit<Parameters<typeof _1Dce40Dc>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _1Dce40Dc>[1], 'throwOnError'>) {
    return getDataOrThrow(_1Dce40Dc(addTenantToParameters(parameters), options));
}

/**
 * Update a credential in a namespace
 */
export function updateNamespaceCredential(parameters: Omit<Parameters<typeof _038B7Bb77>[0], 'apiUpdateCredentialRequest' | 'tenant'> & ApiUpdateCredentialRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _038B7Bb77>[1], 'throwOnError'>) {
    return getDataOrThrow(_038B7Bb77({
        ...parameters,
        tenant: resolveTenant(parameters?.tenant),
        apiUpdateCredentialRequest: parameters
    }, options));
}

/**
 * Test a credential connection
 */
export function testNamespaceConnection(parameters: Omit<Parameters<typeof _5A1A40A7>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _5A1A40A7>[1], 'throwOnError'>) {
    return getDataOrThrow(_5A1A40A7(addTenantToParameters(parameters), options));
}
