// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _011E5C4Dd, _02A557B36, _03315F398, _03F07A422, _052C8Df0a, _06166A596, _0F4647D9, _0Fd54Ad7, _1E9E7721, _5A2Fca1e, _6A36C4F8, _965A3Cb } from '../sdk.gen';
import type { ChartFiltersOverrides, DashboardControllerPreviewRequest } from '../types.gen';

/**
 * Search for dashboards
 */
export const searchDashboards = (parameters?: Omit<Parameters<typeof _0F4647D9>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0F4647D9>[1], 'throwOnError'>) => getDataOrThrow(_0F4647D9(addTenantToParameters(parameters), options));

/**
 * Create a dashboard from yaml source
 */
export const createDashboard = (parameters: Omit<Parameters<typeof _6A36C4F8>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _6A36C4F8>[1], 'throwOnError'>) => getDataOrThrow(_6A36C4F8(addTenantToParameters(parameters), options));

/**
 * Export a table chart data to CSV
 */
export const exportChartToCsv = (parameters: DashboardControllerPreviewRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _1E9E7721>[1], 'throwOnError'>) => getDataOrThrow(_1E9E7721({ tenant: resolveTenant(parameters?.tenant), dashboardControllerPreviewRequest: parameters }, { ...options, parseAs: 'text' }));

/**
 * Preview a chart data
 */
export const previewChart = (parameters: DashboardControllerPreviewRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _052C8Df0a>[1], 'throwOnError'>) => getDataOrThrow(_052C8Df0a({ tenant: resolveTenant(parameters?.tenant), dashboardControllerPreviewRequest: parameters }, options));

/**
 * Get default dashboards
 */
export const defaultDashboards = (parameters?: Omit<Parameters<typeof _02A557B36>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _02A557B36>[1], 'throwOnError'>) => getDataOrThrow(_02A557B36(addTenantToParameters(parameters), options));

/**
 * Validate dashboard from yaml source
 */
export const validateDashboard = (parameters: Omit<Parameters<typeof _5A2Fca1e>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _5A2Fca1e>[1], 'throwOnError'>) => getDataOrThrow(_5A2Fca1e(addTenantToParameters(parameters), options));

/**
 * Validate a chart from yaml source
 */
export const validateChart = (parameters: Omit<Parameters<typeof _03315F398>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _03315F398>[1], 'throwOnError'>) => getDataOrThrow(_03315F398(addTenantToParameters(parameters), options));

/**
 * Delete a dashboard
 */
export const deleteDashboard = (parameters: Omit<Parameters<typeof _0Fd54Ad7>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0Fd54Ad7>[1], 'throwOnError'>) => getDataOrThrow(_0Fd54Ad7(addTenantToParameters(parameters), options));

/**
 * Get a dashboard
 */
export const dashboard = (parameters: Omit<Parameters<typeof _03F07A422>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _03F07A422>[1], 'throwOnError'>) => getDataOrThrow(_03F07A422(addTenantToParameters(parameters), options));

/**
 * Update a dashboard
 */
export const updateDashboard = (parameters: Omit<Parameters<typeof _965A3Cb>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _965A3Cb>[1], 'throwOnError'>) => getDataOrThrow(_965A3Cb(addTenantToParameters(parameters), options));

/**
 * Generate a dashboard chart data
 */
export const dashboardChartData = (parameters: Omit<Parameters<typeof _06166A596>[0], 'chartFiltersOverrides' | 'tenant'> & ChartFiltersOverrides & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _06166A596>[1], 'throwOnError'>) => getDataOrThrow(_06166A596({
    ...parameters,
    tenant: resolveTenant(parameters?.tenant),
    chartFiltersOverrides: parameters
}, options));

/**
 * Export a dashboard chart data to CSV
 */
export const exportDashboardChartDataToCSV = (parameters: Omit<Parameters<typeof _011E5C4Dd>[0], 'chartFiltersOverrides' | 'tenant'> & ChartFiltersOverrides & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _011E5C4Dd>[1], 'throwOnError'>) => getDataOrThrow(_011E5C4Dd({
    ...parameters,
    tenant: resolveTenant(parameters?.tenant),
    chartFiltersOverrides: parameters
}, { ...options, parseAs: 'text' }));
