// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _01Fea9F09, _02A557B36, _03315F398, _03F07A422, _052C8Df0a, _05A013182, _06166A596, _07E6Bfb76, _0F4647D9, _0Fd54Ad7, _5A2Fca1e, _6A36C4F8, _965A3Cb } from '../sdk.gen';
import type { ChartFiltersOverrides, DashboardControllerPreviewRequest } from '../types.gen';

/**
 * Search for dashboards
 */
export const searchDashboards = (parameters?: Omit<Parameters<typeof _0F4647D9>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0F4647D9>[1], 'throwOnError'>) => getDataOrThrow(_0F4647D9(addTenantToParameters(parameters), options));

/**
 * Create a dashboard from yaml source
 */
export const createDashboard = (parameters: Omit<Parameters<typeof _6A36C4F8>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _6A36C4F8>[1], 'throwOnError'>) => getDataOrThrow(_6A36C4F8(addTenantToParameters(parameters), options));

/**
 * Export a chart data
 */
export const exportChart = (parameters: Omit<Parameters<typeof _07E6Bfb76>[0], 'dashboardControllerPreviewRequest' | 'tenant'> & DashboardControllerPreviewRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _07E6Bfb76>[1], 'throwOnError'>) => getDataOrThrow(_07E6Bfb76({
    ...parameters,
    tenant: resolveTenant(parameters?.tenant),
    dashboardControllerPreviewRequest: parameters
}, { ...options, parseAs: 'text' }));

/**
 * Preview a chart data
 */
export const previewChart = (parameters: DashboardControllerPreviewRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _052C8Df0a>[1], 'throwOnError'>) => getDataOrThrow(_052C8Df0a({ tenant: resolveTenant(parameters?.tenant), dashboardControllerPreviewRequest: parameters }, options));

/**
 * Get the built-in default dashboard definitions
 */
export const defaultDashboardDefinitions = (parameters?: Omit<Parameters<typeof _01Fea9F09>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _01Fea9F09>[1], 'throwOnError'>) => getDataOrThrow(_01Fea9F09(addTenantToParameters(parameters), options));

/**
 * Get default dashboards
 */
export const defaultDashboards = (parameters?: Omit<Parameters<typeof _02A557B36>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _02A557B36>[1], 'throwOnError'>) => getDataOrThrow(_02A557B36(addTenantToParameters(parameters), options));

/**
 * Validate dashboard from yaml source
 */
export const validateDashboard = (parameters: Omit<Parameters<typeof _5A2Fca1e>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _5A2Fca1e>[1], 'throwOnError'>) => getDataOrThrow(_5A2Fca1e(addTenantToParameters(parameters), options));

/**
 * Validate a chart from yaml source
 */
export const validateChart = (parameters: Omit<Parameters<typeof _03315F398>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _03315F398>[1], 'throwOnError'>) => getDataOrThrow(_03315F398(addTenantToParameters(parameters), options));

/**
 * Delete a dashboard
 */
export const deleteDashboard = (parameters: Omit<Parameters<typeof _0Fd54Ad7>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0Fd54Ad7>[1], 'throwOnError'>) => getDataOrThrow(_0Fd54Ad7(addTenantToParameters(parameters), options));

/**
 * Get a dashboard
 */
export const dashboard = (parameters: Omit<Parameters<typeof _03F07A422>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _03F07A422>[1], 'throwOnError'>) => getDataOrThrow(_03F07A422(addTenantToParameters(parameters), options));

/**
 * Update a dashboard
 */
export const updateDashboard = (parameters: Omit<Parameters<typeof _965A3Cb>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _965A3Cb>[1], 'throwOnError'>) => getDataOrThrow(_965A3Cb(addTenantToParameters(parameters), options));

/**
 * Generate a dashboard chart data
 */
export const dashboardChartData = (parameters: Omit<Parameters<typeof _06166A596>[0], 'chartFiltersOverrides' | 'tenant'> & ChartFiltersOverrides & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _06166A596>[1], 'throwOnError'>) => getDataOrThrow(_06166A596({
    ...parameters,
    tenant: resolveTenant(parameters?.tenant),
    chartFiltersOverrides: parameters
}, options));

/**
 * Export a dashboard chart data
 */
export const exportDashboardChart = (parameters: Omit<Parameters<typeof _05A013182>[0], 'chartFiltersOverrides' | 'tenant'> & ChartFiltersOverrides & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _05A013182>[1], 'throwOnError'>) => getDataOrThrow(_05A013182({
    ...parameters,
    tenant: resolveTenant(parameters?.tenant),
    chartFiltersOverrides: parameters
}, { ...options, parseAs: 'text' }));
