// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow } from './shared.gen';
import { _151C85Fc } from '../sdk.gen';

/**
 * Get default dashboards
 */
export function getDefaultDashboards(parameters?: Omit<Parameters<typeof _151C85Fc>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _151C85Fc>[1], 'throwOnError'>) {
    return getDataOrThrow(_151C85Fc(addTenantToParameters(parameters), options));
}
