// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow } from './shared.gen';
import { _5Db1D88 } from '../sdk.gen';

export const get = (parameters: Omit<Parameters<typeof _5Db1D88>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _5Db1D88>[1], 'throwOnError'>) => getDataOrThrow(_5Db1D88(addTenantToParameters(parameters), options));
