// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow } from './shared.gen';
import { _02505195f, _3841611c, _63Bc5F47 } from '../sdk.gen';

export const handleDeleteRequest = (parameters: Omit<Parameters<typeof _3841611c>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _3841611c>[1], 'throwOnError'>) => getDataOrThrow(_3841611c(addTenantToParameters(parameters), options));

export const handleGetRequest = (parameters: Omit<Parameters<typeof _02505195f>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _02505195f>[1], 'throwOnError'>) => _02505195f(addTenantToParameters(parameters), options);

export const handleRequest = (parameters: Omit<Parameters<typeof _63Bc5F47>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _63Bc5F47>[1], 'throwOnError'>) => getDataOrThrow(_63Bc5F47(addTenantToParameters(parameters), options));
