// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _010C1C295, _011787999, _0117D26A6, _01263C155, _012672A53, _0279E8381, _027A6Da8, _028Aeb63d, _028Ee38A7, _0299Dd8Df, _02B0Ac8D1, _02C81F3Ac, _02Ce15148, _02D1825F2, _02Fbc290f, _0357D5B80, _038Dcaf51, _039F8Ba95, _03Cf4A0Ab, _04199839e, _044Bb45A4, _0472E2162, _0486C8476, _050Bf82E9, _051905136, _05978F079, _05Ef057Dd, _063170190, _06944349d, _069531B2c, _06Fa01237, _070Ae25E8, _072B3D08b, _0752Adbc4, _076D036Df, _15Bac3E0, _18Dbd36b, _191Cdebb, _197Ff358, _271A34a, _2D63137, _2Eff59C2, _380C1616, _3D8Cecc2, _47F9Ce7e, _489E3513, _59F56586, _5A35A529, _5C609C5f, _5F1Abe3c, _66Dea7Aa, _67A4E57c, _71B7280, _72929E1b, _731Fd483, _736327A7, _7F56E7Dd, _9Beb7Be, e446C08, f43A000 } from '../sdk.gen';
import type { ExecutionControllerSetLabelsByIdsRequest, ExecutionControllerStateRequest } from '../types.gen';

/**
 * Search for executions for a flow
 */
export const searchExecutionsByFlowId = (parameters: Omit<Parameters<typeof _06944349d>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _06944349d>[1], 'throwOnError'>) => getDataOrThrow(_06944349d(addTenantToParameters(parameters), options));

/**
 * Delete a list of executions
 */
export const deleteExecutionsByIds = (parameters: Omit<Parameters<typeof _72929E1b>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _72929E1b>[1], 'throwOnError'>) => getDataOrThrow(_72929E1b(addTenantToParameters(parameters), options));

/**
 * Delete executions filter by query parameters
 */
export const deleteExecutionsByQuery = (parameters?: Omit<Parameters<typeof _18Dbd36b>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _18Dbd36b>[1], 'throwOnError'>) => getDataOrThrow(_18Dbd36b(addTenantToParameters(parameters), options));

/**
 * Change executions state by id asynchronously
 */
export const updateExecutionsStatusByIds = (parameters: Omit<Parameters<typeof _010C1C295>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _010C1C295>[1], 'throwOnError'>) => getDataOrThrow(_010C1C295(addTenantToParameters(parameters), options));

/**
 * Change executions state by query parameters asynchronously
 */
export const updateExecutionsStatusByQuery = (parameters: Omit<Parameters<typeof _191Cdebb>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _191Cdebb>[1], 'throwOnError'>) => getDataOrThrow(_191Cdebb(addTenantToParameters(parameters), options));

/**
 * List distinct values for one of the executions filter fields, optionally narrowed by additional query filters
 */
export const findDistinctFieldValues = (parameters: Omit<Parameters<typeof _736327A7>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _736327A7>[1], 'throwOnError'>) => getDataOrThrow(_736327A7(addTenantToParameters(parameters), options));

/**
 * Export all executions as a streamed CSV file
 */
export const exportExecutions = (parameters?: Omit<Parameters<typeof _02B0Ac8D1>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _02B0Ac8D1>[1], 'throwOnError'>) => getDataOrThrow(_02B0Ac8D1(addTenantToParameters(parameters), options));

/**
 * Get flow information's for an execution
 */
export const flowFromExecution = (parameters: Omit<Parameters<typeof _271A34a>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _271A34a>[1], 'throwOnError'>) => getDataOrThrow(_271A34a(addTenantToParameters(parameters), options));

/**
 * Force run a list of executions asynchronously
 */
export const forceRunByIds = (parameters: Omit<Parameters<typeof _0299Dd8Df>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0299Dd8Df>[1], 'throwOnError'>) => getDataOrThrow(_0299Dd8Df(addTenantToParameters(parameters), options));

/**
 * Force run executions filter by query parameters asynchronously
 */
export const forceRunExecutionsByQuery = (parameters?: Omit<Parameters<typeof _380C1616>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _380C1616>[1], 'throwOnError'>) => getDataOrThrow(_380C1616(addTenantToParameters(parameters), options));

/**
 * Kill a list of executions asynchronously
 */
export const killExecutionsByIds = (parameters: Omit<Parameters<typeof e446C08>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof e446C08>[1], 'throwOnError'>) => getDataOrThrow(e446C08(addTenantToParameters(parameters), options));

/**
 * Kill executions filter by query parameters
 */
export const killExecutionsByQuery = (parameters?: Omit<Parameters<typeof _070Ae25E8>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _070Ae25E8>[1], 'throwOnError'>) => getDataOrThrow(_070Ae25E8(addTenantToParameters(parameters), options));

/**
 * Set labels on a list of executions asynchronously
 */
export const setLabelsOnTerminatedExecutionsByIds = (parameters: ExecutionControllerSetLabelsByIdsRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _028Aeb63d>[1], 'throwOnError'>) => getDataOrThrow(_028Aeb63d({ tenant: resolveTenant(parameters?.tenant), executionControllerSetLabelsByIdsRequest: parameters }, options));

/**
 * Set label on executions filter by query parameters asynchronously
 */
export const setLabelsOnTerminatedExecutionsByQuery = (parameters: Omit<Parameters<typeof _489E3513>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _489E3513>[1], 'throwOnError'>) => getDataOrThrow(_489E3513(addTenantToParameters(parameters), options));

/**
 * Get the latest execution for given flows
 */
export const latestExecutions = (parameters: Omit<Parameters<typeof _02Ce15148>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _02Ce15148>[1], 'throwOnError'>) => getDataOrThrow(_02Ce15148(addTenantToParameters(parameters), options));

/**
 * Get all namespaces that have executable flows
 */
export const listExecutableDistinctNamespaces = (parameters?: Omit<Parameters<typeof _0752Adbc4>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0752Adbc4>[1], 'throwOnError'>) => getDataOrThrow(_0752Adbc4(addTenantToParameters(parameters), options));

/**
 * Get all flow ids for a namespace. Data returned are FlowForExecution containing minimal information about a Flow for when you are allowed to executing but not reading.
 */
export const listFlowExecutionsByNamespace = (parameters: Omit<Parameters<typeof _7F56E7Dd>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _7F56E7Dd>[1], 'throwOnError'>) => getDataOrThrow(_7F56E7Dd(addTenantToParameters(parameters), options));

/**
 * Pause a list of running executions asynchronously
 */
export const pauseExecutionsByIds = (parameters: Omit<Parameters<typeof _063170190>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _063170190>[1], 'throwOnError'>) => getDataOrThrow(_063170190(addTenantToParameters(parameters), options));

/**
 * Pause executions filter by query parameters asynchronously
 */
export const pauseExecutionsByQuery = (parameters?: Omit<Parameters<typeof _71B7280>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _71B7280>[1], 'throwOnError'>) => getDataOrThrow(_71B7280(addTenantToParameters(parameters), options));

/**
 * Create new executions from old ones asynchronously. Keep the flow revision
 */
export const replayExecutionsByIds = (parameters: Omit<Parameters<typeof _5C609C5f>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _5C609C5f>[1], 'throwOnError'>) => getDataOrThrow(_5C609C5f(addTenantToParameters(parameters), options));

/**
 * Create new executions from old ones filter by query parameters asynchronously. Keep the flow revision
 */
export const replayExecutionsByQuery = (parameters?: Omit<Parameters<typeof _038Dcaf51>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _038Dcaf51>[1], 'throwOnError'>) => getDataOrThrow(_038Dcaf51(addTenantToParameters(parameters), options));

/**
 * Restart a list of executions asynchronously
 */
export const restartExecutionsByIds = (parameters: Omit<Parameters<typeof _2D63137>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _2D63137>[1], 'throwOnError'>) => getDataOrThrow(_2D63137(addTenantToParameters(parameters), options));

/**
 * Restart executions filter by query parameters asynchronously
 */
export const restartExecutionsByQuery = (parameters?: Omit<Parameters<typeof _05978F079>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _05978F079>[1], 'throwOnError'>) => getDataOrThrow(_05978F079(addTenantToParameters(parameters), options));

/**
 * Resume a list of paused executions asynchronously
 */
export const resumeExecutionsByIds = (parameters: Omit<Parameters<typeof _028Ee38A7>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _028Ee38A7>[1], 'throwOnError'>) => getDataOrThrow(_028Ee38A7(addTenantToParameters(parameters), options));

/**
 * Resume executions filter by query parameters asynchronously
 */
export const resumeExecutionsByQuery = (parameters?: Omit<Parameters<typeof _5A35A529>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _5A35A529>[1], 'throwOnError'>) => getDataOrThrow(_5A35A529(addTenantToParameters(parameters), options));

/**
 * Search for executions
 */
export const searchExecutions = (parameters?: Omit<Parameters<typeof _05Ef057Dd>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _05Ef057Dd>[1], 'throwOnError'>) => getDataOrThrow(_05Ef057Dd(addTenantToParameters(parameters), options));

/**
 * Unqueue a list of executions asynchronously
 */
export const unqueueExecutionsByIds = (parameters: Omit<Parameters<typeof _02D1825F2>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _02D1825F2>[1], 'throwOnError'>) => getDataOrThrow(_02D1825F2(addTenantToParameters(parameters), options));

/**
 * Unqueue executions filter by query parameters asynchronously
 */
export const unqueueExecutionsByQuery = (parameters?: Omit<Parameters<typeof _0472E2162>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0472E2162>[1], 'throwOnError'>) => getDataOrThrow(_0472E2162(addTenantToParameters(parameters), options));

/**
 * Trigger a new execution by GET webhook trigger
 */
export const triggerExecutionByGetWebhook = (parameters: Omit<Parameters<typeof _027A6Da8>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _027A6Da8>[1], 'throwOnError'>) => getDataOrThrow(_027A6Da8(addTenantToParameters(parameters), options));

/**
 * Trigger a new execution by POST webhook trigger
 */
export const triggerExecutionByPostWebhook = (parameters: Omit<Parameters<typeof _0357D5B80>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0357D5B80>[1], 'throwOnError'>) => getDataOrThrow(_0357D5B80(addTenantToParameters(parameters), options));

/**
 * Trigger a new execution by PUT webhook trigger
 */
export const triggerExecutionByPutWebhook = (parameters: Omit<Parameters<typeof _0279E8381>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0279E8381>[1], 'throwOnError'>) => getDataOrThrow(_0279E8381(addTenantToParameters(parameters), options));

/**
 * Trigger a new execution by GET webhook trigger
 */
export const triggerExecutionByGetWebhookWithPath = (parameters: Omit<Parameters<typeof _731Fd483>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _731Fd483>[1], 'throwOnError'>) => getDataOrThrow(_731Fd483(addTenantToParameters(parameters), options));

/**
 * Trigger a new execution by POST webhook trigger
 */
export const triggerExecutionByPostWebhookWithPath = (parameters: Omit<Parameters<typeof _01263C155>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _01263C155>[1], 'throwOnError'>) => getDataOrThrow(_01263C155(addTenantToParameters(parameters), options));

/**
 * Trigger a new execution by PUT webhook trigger
 */
export const triggerExecutionByPutWebhookWithPath = (parameters: Omit<Parameters<typeof _66Dea7Aa>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _66Dea7Aa>[1], 'throwOnError'>) => getDataOrThrow(_66Dea7Aa(addTenantToParameters(parameters), options));

/**
 * Delete an execution
 */
export const deleteExecution = (parameters: Omit<Parameters<typeof _012672A53>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _012672A53>[1], 'throwOnError'>) => getDataOrThrow(_012672A53(addTenantToParameters(parameters), options));

/**
 * Get an execution
 */
export const execution = (parameters: Omit<Parameters<typeof _04199839e>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _04199839e>[1], 'throwOnError'>) => getDataOrThrow(_04199839e(addTenantToParameters(parameters), options));

/**
 * Change the state of an execution
 */
export const updateExecutionStatus = (parameters: Omit<Parameters<typeof _076D036Df>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _076D036Df>[1], 'throwOnError'>) => getDataOrThrow(_076D036Df(addTenantToParameters(parameters), options));

/**
 * Evaluate a variable expression for this execution
 */
export const evalExpression = (parameters: Omit<Parameters<typeof _02C81F3Ac>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _02C81F3Ac>[1], 'throwOnError'>) => getDataOrThrow(_02C81F3Ac(addTenantToParameters(parameters), options));

/**
 * Evaluate a variable expression for this taskrun
 */
export const evalTaskRunExpression = (parameters: Omit<Parameters<typeof _3D8Cecc2>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _3D8Cecc2>[1], 'throwOnError'>) => getDataOrThrow(_3D8Cecc2(addTenantToParameters(parameters), options));

/**
 * Force run an execution
 */
export const forceRunExecution = (parameters: Omit<Parameters<typeof _197Ff358>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _197Ff358>[1], 'throwOnError'>) => getDataOrThrow(_197Ff358(addTenantToParameters(parameters), options));

/**
 * Kill an execution
 */
export const killExecution = (parameters: Omit<Parameters<typeof _0117D26A6>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0117D26A6>[1], 'throwOnError'>) => getDataOrThrow(_0117D26A6(addTenantToParameters(parameters), options));

/**
 * Add or update labels of a terminated execution
 */
export const setLabelsOnTerminatedExecution = (parameters: Omit<Parameters<typeof _03Cf4A0Ab>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _03Cf4A0Ab>[1], 'throwOnError'>) => getDataOrThrow(_03Cf4A0Ab(addTenantToParameters(parameters), options));

/**
 * Pause a running execution.
 */
export const pauseExecution = (parameters: Omit<Parameters<typeof _2Eff59C2>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _2Eff59C2>[1], 'throwOnError'>) => getDataOrThrow(_2Eff59C2(addTenantToParameters(parameters), options));

/**
 * Create a new execution from an old one and start it from a specified task run id
 */
export const replayExecution = (parameters: Omit<Parameters<typeof _02Fbc290f>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _02Fbc290f>[1], 'throwOnError'>) => getDataOrThrow(_02Fbc290f(addTenantToParameters(parameters), options));

/**
 * Create a new execution from an old one and start it from a specified task run id
 */
export const replayExecutionWithinputs = (parameters: Omit<Parameters<typeof f43A000>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof f43A000>[1], 'throwOnError'>) => getDataOrThrow(f43A000(addTenantToParameters(parameters), options));

/**
 * Restart a new execution from an old one
 */
export const restartExecution = (parameters: Omit<Parameters<typeof _06Fa01237>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _06Fa01237>[1], 'throwOnError'>) => getDataOrThrow(_06Fa01237(addTenantToParameters(parameters), options));

/**
 * Resume a paused execution.
 */
export const resumeExecution = (parameters: Omit<Parameters<typeof _039F8Ba95>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _039F8Ba95>[1], 'throwOnError'>) => getDataOrThrow(_039F8Ba95(addTenantToParameters({ body: [], ...parameters }), options));

/**
 * Resume an execution from a breakpoint (in the 'BREAKPOINT' state).
 */
export const resumeExecutionFromBreakpoint = (parameters: Omit<Parameters<typeof _59F56586>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _59F56586>[1], 'throwOnError'>) => getDataOrThrow(_59F56586(addTenantToParameters(parameters), options));

/**
 * Validate inputs to resume a paused execution.
 */
export const validateResumeExecutionInputs = (parameters: Omit<Parameters<typeof _9Beb7Be>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _9Beb7Be>[1], 'throwOnError'>) => getDataOrThrow(_9Beb7Be(addTenantToParameters({ body: [], ...parameters }), options));

/**
 * Change state for a taskrun in an execution
 */
export const updateTaskRunState = (parameters: Omit<Parameters<typeof _069531B2c>[0], 'executionControllerStateRequest' | 'tenant'> & ExecutionControllerStateRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _069531B2c>[1], 'throwOnError'>) => getDataOrThrow(_069531B2c({
    ...parameters,
    tenant: resolveTenant(parameters?.tenant),
    executionControllerStateRequest: parameters
}, options));

/**
 * Unqueue an execution
 */
export const unqueueExecution = (parameters: Omit<Parameters<typeof _15Bac3E0>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _15Bac3E0>[1], 'throwOnError'>) => getDataOrThrow(_15Bac3E0(addTenantToParameters(parameters), options));

/**
 * Download file for an execution
 */
export const downloadFileFromExecution = (parameters: Omit<Parameters<typeof _051905136>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _051905136>[1], 'throwOnError'>) => getDataOrThrow(_051905136(addTenantToParameters(parameters), options));

/**
 * Get file meta information for an execution
 */
export const fileMetadatasFromExecution = (parameters: Omit<Parameters<typeof _044Bb45A4>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _044Bb45A4>[1], 'throwOnError'>) => getDataOrThrow(_044Bb45A4(addTenantToParameters(parameters), options));

/**
 * Get file preview for an execution
 */
export const previewFileFromExecution = (parameters: Omit<Parameters<typeof _0486C8476>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0486C8476>[1], 'throwOnError'>) => getDataOrThrow(_0486C8476(addTenantToParameters(parameters), options));

/**
 * Get flow information's for an execution
 */
export const flowFromExecutionById = (parameters: Omit<Parameters<typeof _5F1Abe3c>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _5F1Abe3c>[1], 'throwOnError'>) => getDataOrThrow(_5F1Abe3c(addTenantToParameters(parameters), options));

/**
 * Follow an execution
 */
export const followExecution = (parameters: Omit<Parameters<typeof _011787999>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _011787999>[1], 'throwOnError'>) => _011787999(addTenantToParameters(parameters), options);

/**
 * Follow all execution dependencies executions
 */
export const followDependenciesExecutions = (parameters: Omit<Parameters<typeof _072B3D08b>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _072B3D08b>[1], 'throwOnError'>) => _072B3D08b(addTenantToParameters(parameters), options);

/**
 * Generate a graph for an execution
 */
export const executionFlowGraph = (parameters: Omit<Parameters<typeof _47F9Ce7e>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _47F9Ce7e>[1], 'throwOnError'>) => getDataOrThrow(_47F9Ce7e(addTenantToParameters(parameters), options));

/**
 * Create a new execution for a flow
 */
export const createExecution = (parameters: Omit<Parameters<typeof _67A4E57c>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _67A4E57c>[1], 'throwOnError'>) => getDataOrThrow(_67A4E57c(addTenantToParameters({ body: [], ...parameters }), options));

/**
 * Validate the creation of a new execution for a flow
 */
export const validateNewExecutionInputs = (parameters: Omit<Parameters<typeof _050Bf82E9>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _050Bf82E9>[1], 'throwOnError'>) => getDataOrThrow(_050Bf82E9(addTenantToParameters({ body: [], ...parameters }), options));
