// This file is auto-generated by @hey-api/openapi-ts

import { getDataOrThrow, resolveTenant } from './shared.gen';
import { _04A36929b } from '../sdk.gen';
import type { ExpressionControllerRenderExpressionRequest } from '../types.gen';

/**
 * Render Pebble expressions for display
 */
export const renderExpressions = (parameters: ExpressionControllerRenderExpressionRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _04A36929b>[1], 'throwOnError'>) => getDataOrThrow(_04A36929b({ tenant: resolveTenant(parameters?.tenant), expressionControllerRenderExpressionRequest: parameters }, options));
