// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow } from './shared.gen';
import { _04B8569Da, _057D73E5c, _07288D39a, _075B6Dc39, _07C45C5D9, _4157Eab0, _5233556e, _54C4A1Db, _56Da3D52, _7D6E2400 } from '../sdk.gen';

/**
 * Delete a file or directory
 */
export const deleteFileDirectory = (parameters: Omit<Parameters<typeof _07288D39a>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _07288D39a>[1], 'throwOnError'>) => getDataOrThrow(_07288D39a(addTenantToParameters(parameters), options));

/**
 * Get namespace file content
 */
export const fileContent = (parameters: Omit<Parameters<typeof _07C45C5D9>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _07C45C5D9>[1], 'throwOnError'>) => getDataOrThrow(_07C45C5D9(addTenantToParameters(parameters), options));

/**
 * Create a file
 */
export const createNamespaceFile = (parameters: Omit<Parameters<typeof _54C4A1Db>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _54C4A1Db>[1], 'throwOnError'>) => getDataOrThrow(_54C4A1Db(addTenantToParameters(parameters), options));

/**
 * Move a file or directory
 */
export const moveFileDirectory = (parameters: Omit<Parameters<typeof _7D6E2400>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _7D6E2400>[1], 'throwOnError'>) => getDataOrThrow(_7D6E2400(addTenantToParameters(parameters), options));

/**
 * List directory content
 */
export const listNamespaceDirectoryFiles = (parameters: Omit<Parameters<typeof _075B6Dc39>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _075B6Dc39>[1], 'throwOnError'>) => getDataOrThrow(_075B6Dc39(addTenantToParameters(parameters), options));

/**
 * Create a directory
 */
export const createNamespaceDirectory = (parameters: Omit<Parameters<typeof _5233556e>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _5233556e>[1], 'throwOnError'>) => getDataOrThrow(_5233556e(addTenantToParameters(parameters), options));

/**
 * Export namespace files as a ZIP
 */
export const exportNamespaceFiles = (parameters: Omit<Parameters<typeof _4157Eab0>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _4157Eab0>[1], 'throwOnError'>) => getDataOrThrow(_4157Eab0(addTenantToParameters(parameters), { ...options, parseAs: 'text' }));

/**
 * Get namespace file revisions
 */
export const fileRevisions = (parameters: Omit<Parameters<typeof _04B8569Da>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _04B8569Da>[1], 'throwOnError'>) => getDataOrThrow(_04B8569Da(addTenantToParameters(parameters), options));

/**
 * Find files which path contain the given string in their URI
 */
export const searchNamespaceFiles = (parameters: Omit<Parameters<typeof _057D73E5c>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _057D73E5c>[1], 'throwOnError'>) => getDataOrThrow(_057D73E5c(addTenantToParameters(parameters), options));

/**
 * Get namespace file stats such as size, creation & modification dates and type
 */
export const fileMetadatas = (parameters: Omit<Parameters<typeof _56Da3D52>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _56Da3D52>[1], 'throwOnError'>) => getDataOrThrow(_56Da3D52(addTenantToParameters(parameters), options));
