// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _011A9De69, _02187E7C3, _030A1703e, _030B1A670, _032E9A671, _0480965c, _048Aa80Ed, _0494596B6, _06666E52f, _067435Ac4, _06B60682e, _0715460C9, _0715B9840, _07E3Fae4f, _0Ec51319, _1Ec18Cc3, _1F4344F1, _1F9D50E4, _3De59Ebf, _407247Bb, _41A7Bacb, _4Cc20E8d, _5196384a, _541Dca5a, _562B4060, _579848F4, _5B713B0f, _62Bef13d, _666C64Ed, _69272D79, _6C34C66c, _7D0E1E4, a76C0Db, ae43B0 } from '../sdk.gen';
import type { ConcurrencyLimit } from '../types.gen';

/**
 * Search for flow concurrency limits
 */
export const searchConcurrencyLimits = (parameters?: Omit<Parameters<typeof _1Ec18Cc3>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _1Ec18Cc3>[1], 'throwOnError'>) => getDataOrThrow(_1Ec18Cc3(addTenantToParameters(parameters), options));

/**
 * Update a flow concurrency limit
 */
export const updateConcurrencyLimit = (parameters: Omit<Parameters<typeof _06666E52f>[0], 'concurrencyLimit' | 'tenant'> & ConcurrencyLimit & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _06666E52f>[1], 'throwOnError'>) => getDataOrThrow(_06666E52f({
    ...parameters,
    tenant: resolveTenant(parameters?.tenant),
    concurrencyLimit: parameters
}, options));

/**
 * Create a flow from yaml source
 */
export const createFlow = (parameters: Omit<Parameters<typeof _5196384a>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _5196384a>[1], 'throwOnError'>) => getDataOrThrow(_5196384a(addTenantToParameters(parameters), options));

/**
 * Update from multiples yaml sources
 */
export const bulkUpdateFlows = (parameters?: Omit<Parameters<typeof _0494596B6>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0494596B6>[1], 'throwOnError'>) => getDataOrThrow(_0494596B6(addTenantToParameters(parameters), options));

/**
 * Delete flows by their IDs.
 */
export const deleteFlowsByIds = (parameters: Omit<Parameters<typeof _0Ec51319>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0Ec51319>[1], 'throwOnError'>) => getDataOrThrow(_0Ec51319(addTenantToParameters(parameters), options));

/**
 * Delete flows returned by the query parameters.
 */
export const deleteFlowsByQuery = (parameters?: Omit<Parameters<typeof _0715460C9>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0715460C9>[1], 'throwOnError'>) => getDataOrThrow(_0715460C9(addTenantToParameters(parameters), options));

/**
 * List flows containing deprecated tasks
 */
export const listDeprecated = (parameters?: Omit<Parameters<typeof _1F4344F1>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _1F4344F1>[1], 'throwOnError'>) => getDataOrThrow(_1F4344F1(addTenantToParameters(parameters), options));

/**
 * Disable flows by their IDs.
 */
export const disableFlowsByIds = (parameters: Omit<Parameters<typeof _7D0E1E4>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _7D0E1E4>[1], 'throwOnError'>) => getDataOrThrow(_7D0E1E4(addTenantToParameters(parameters), options));

/**
 * Disable flows returned by the query parameters.
 */
export const disableFlowsByQuery = (parameters?: Omit<Parameters<typeof _579848F4>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _579848F4>[1], 'throwOnError'>) => getDataOrThrow(_579848F4(addTenantToParameters(parameters), options));

/**
 * List all distinct namespaces
 */
export const listDistinctNamespaces = (parameters?: Omit<Parameters<typeof _06B60682e>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _06B60682e>[1], 'throwOnError'>) => getDataOrThrow(_06B60682e(addTenantToParameters(parameters), options));

/**
 * Enable flows by their IDs.
 */
export const enableFlowsByIds = (parameters: Omit<Parameters<typeof _3De59Ebf>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _3De59Ebf>[1], 'throwOnError'>) => getDataOrThrow(_3De59Ebf(addTenantToParameters(parameters), options));

/**
 * Enable flows returned by the query parameters.
 */
export const enableFlowsByQuery = (parameters?: Omit<Parameters<typeof _5B713B0f>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _5B713B0f>[1], 'throwOnError'>) => getDataOrThrow(_5B713B0f(addTenantToParameters(parameters), options));

/**
 * Export flows as a ZIP archive of yaml sources.
 */
export const exportFlowsByIds = (parameters: Omit<Parameters<typeof ae43B0>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof ae43B0>[1], 'throwOnError'>) => getDataOrThrow(ae43B0(addTenantToParameters(parameters), { ...options, parseAs: 'text' }));

/**
 * Export flows as a ZIP archive of yaml sources.
 */
export const exportFlowsByQuery = (parameters?: Omit<Parameters<typeof _0715B9840>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0715B9840>[1], 'throwOnError'>) => getDataOrThrow(_0715B9840(addTenantToParameters(parameters), { ...options, parseAs: 'text' }));

/**
 * Export all flows as a streamed CSV file
 */
export const exportFlows = (parameters?: Omit<Parameters<typeof _07E3Fae4f>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _07E3Fae4f>[1], 'throwOnError'>) => getDataOrThrow(_07E3Fae4f(addTenantToParameters(parameters), options));

/**
 * Get available Pebble expressions for a flow
 */
export const expressions = (parameters: Omit<Parameters<typeof a76C0Db>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof a76C0Db>[1], 'throwOnError'>) => getDataOrThrow(a76C0Db(addTenantToParameters(parameters), options));

/**
 * Generate a graph for a flow source
 */
export const generateFlowGraphFromSource = (parameters: Omit<Parameters<typeof _030B1A670>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _030B1A670>[1], 'throwOnError'>) => getDataOrThrow(_030B1A670(addTenantToParameters(parameters), options));

/**
 *     Import flows as a ZIP archive of yaml sources or a multi-objects YAML file.
 *     When sending a Yaml that contains one or more flows, a list of index is returned.
 *     When sending a ZIP archive, a list of files that couldn't be imported is returned.
 *
 */
export const importFlows = (parameters: Omit<Parameters<typeof _562B4060>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _562B4060>[1], 'throwOnError'>) => getDataOrThrow(_562B4060(addTenantToParameters(parameters), options));

/**
 * Search for flows
 */
export const searchFlows = (parameters?: Omit<Parameters<typeof _02187E7C3>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _02187E7C3>[1], 'throwOnError'>) => getDataOrThrow(_02187E7C3(addTenantToParameters(parameters), options));

/**
 * Search for flows source code
 */
export const searchFlowsBySourceCode = (parameters?: Omit<Parameters<typeof _067435Ac4>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _067435Ac4>[1], 'throwOnError'>) => getDataOrThrow(_067435Ac4(addTenantToParameters(parameters), options));

/**
 * Validate a list of flows
 */
export const validateFlows = (parameters: Omit<Parameters<typeof _032E9A671>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _032E9A671>[1], 'throwOnError'>) => getDataOrThrow(_032E9A671(addTenantToParameters(parameters), options));

/**
 * Validate a task
 */
export const validateTask = (parameters: Omit<Parameters<typeof _407247Bb>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _407247Bb>[1], 'throwOnError'>) => getDataOrThrow(_407247Bb(addTenantToParameters(parameters), options));

/**
 * Validate trigger
 */
export const validateTrigger = (parameters: Omit<Parameters<typeof _030A1703e>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _030A1703e>[1], 'throwOnError'>) => getDataOrThrow(_030A1703e(addTenantToParameters(parameters), options));

/**
 * Retrieve all flows from a given namespace
 */
export const listFlowsByNamespace = (parameters: Omit<Parameters<typeof _62Bef13d>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _62Bef13d>[1], 'throwOnError'>) => getDataOrThrow(_62Bef13d(addTenantToParameters(parameters), options));

/**
 * Update a complete namespace from yaml source
 */
export const updateFlowsInNamespace = (parameters: Omit<Parameters<typeof _541Dca5a>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _541Dca5a>[1], 'throwOnError'>) => getDataOrThrow(_541Dca5a(addTenantToParameters(parameters), options));

/**
 * Delete a flow
 */
export const deleteFlow = (parameters: Omit<Parameters<typeof _69272D79>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _69272D79>[1], 'throwOnError'>) => getDataOrThrow(_69272D79(addTenantToParameters(parameters), options));

/**
 * Get a flow
 */
export const flow = (parameters: Omit<Parameters<typeof _0480965c>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0480965c>[1], 'throwOnError'>) => getDataOrThrow(_0480965c(addTenantToParameters(parameters), options));

/**
 * Update a flow
 */
export const updateFlow = (parameters: Omit<Parameters<typeof _011A9De69>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _011A9De69>[1], 'throwOnError'>) => getDataOrThrow(_011A9De69(addTenantToParameters(parameters), options));

/**
 * Get flow dependencies
 */
export const flowDependencies = (parameters: Omit<Parameters<typeof _666C64Ed>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _666C64Ed>[1], 'throwOnError'>) => getDataOrThrow(_666C64Ed(addTenantToParameters(parameters), options));

/**
 * Generate a graph for a flow
 */
export const generateFlowGraph = (parameters: Omit<Parameters<typeof _41A7Bacb>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _41A7Bacb>[1], 'throwOnError'>) => getDataOrThrow(_41A7Bacb(addTenantToParameters(parameters), options));

/**
 * Delete revisions for a flow
 */
export const deleteRevisions = (parameters: Omit<Parameters<typeof _4Cc20E8d>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _4Cc20E8d>[1], 'throwOnError'>) => getDataOrThrow(_4Cc20E8d(addTenantToParameters(parameters), options));

/**
 * Get revisions for a flow
 */
export const listFlowRevisions = (parameters: Omit<Parameters<typeof _6C34C66c>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _6C34C66c>[1], 'throwOnError'>) => getDataOrThrow(_6C34C66c(addTenantToParameters(parameters), options));

/**
 * Get a flow task
 */
export const taskFromFlow = (parameters: Omit<Parameters<typeof _048Aa80Ed>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _048Aa80Ed>[1], 'throwOnError'>) => getDataOrThrow(_048Aa80Ed(addTenantToParameters(parameters), options));

/**
 * Get flow dependencies
 */
export const flowDependenciesFromNamespace = (parameters: Omit<Parameters<typeof _1F9D50E4>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _1F9D50E4>[1], 'throwOnError'>) => getDataOrThrow(_1F9D50E4(addTenantToParameters(parameters), options));
