// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _01Ebe5D1d, _023811Cca, _0331D20E8, _04430Ac6c, _04E18D824, _070B4Bca7, _0D6Bb264, _5Ec7Ba77, _666Ae97f, _747E9Cc9, _80D6B62 } from '../sdk.gen';
import type { ApiAutocomplete, ApiIds, IamGroupControllerApiCreateGroupRequest, IamGroupControllerApiUpdateGroupRequest } from '../types.gen';

/**
 * Create a group
 */
export function createGroup(parameters: IamGroupControllerApiCreateGroupRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _01Ebe5D1d>[1], 'throwOnError'>) {
    return getDataOrThrow(_01Ebe5D1d({ tenant: resolveTenant(parameters?.tenant), iamGroupControllerApiCreateGroupRequest: parameters }, options));
}

/**
 * List groups for autocomplete
 */
export function autocompleteGroups(parameters: Omit<Parameters<typeof _04E18D824>[0], 'apiAutocomplete' | 'tenant'> & ApiAutocomplete & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _04E18D824>[1], 'throwOnError'>) {
    return getDataOrThrow(_04E18D824({
        ...parameters,
        tenant: resolveTenant(parameters?.tenant),
        apiAutocomplete: parameters
    }, options));
}

/**
 * List groups by ids
 */
export function listGroupIds(parameters: ApiIds & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _5Ec7Ba77>[1], 'throwOnError'>) {
    return getDataOrThrow(_5Ec7Ba77({ tenant: resolveTenant(parameters?.tenant), apiIds: parameters }, options));
}

/**
 * Search for groups
 */
export function searchGroups(parameters: Omit<Parameters<typeof _0D6Bb264>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0D6Bb264>[1], 'throwOnError'>) {
    return getDataOrThrow(_0D6Bb264(addTenantToParameters(parameters), options));
}

/**
 * Delete a group
 */
export function deleteGroup(parameters: Omit<Parameters<typeof _04430Ac6c>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _04430Ac6c>[1], 'throwOnError'>) {
    return getDataOrThrow(_04430Ac6c(addTenantToParameters(parameters), options));
}

/**
 * Retrieve a group
 */
export function getGroup(parameters: Omit<Parameters<typeof _747E9Cc9>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _747E9Cc9>[1], 'throwOnError'>) {
    return getDataOrThrow(_747E9Cc9(addTenantToParameters(parameters), options));
}

/**
 * Update a group
 */
export function updateGroup(parameters: Omit<Parameters<typeof _023811Cca>[0], 'iamGroupControllerApiUpdateGroupRequest' | 'tenant'> & IamGroupControllerApiUpdateGroupRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _023811Cca>[1], 'throwOnError'>) {
    return getDataOrThrow(_023811Cca({
        ...parameters,
        tenant: resolveTenant(parameters?.tenant),
        iamGroupControllerApiUpdateGroupRequest: parameters
    }, options));
}

/**
 * Search for users in a group
 */
export function searchGroupMembers(parameters: Omit<Parameters<typeof _80D6B62>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _80D6B62>[1], 'throwOnError'>) {
    return getDataOrThrow(_80D6B62(addTenantToParameters(parameters), options));
}

/**
 * Update a user's membership type in a group
 */
export function setUserMembershipForGroup(parameters: Omit<Parameters<typeof _070B4Bca7>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _070B4Bca7>[1], 'throwOnError'>) {
    return getDataOrThrow(_070B4Bca7(addTenantToParameters(parameters), options));
}

/**
 * Remove a user from a group
 */
export function deleteUserFromGroup(parameters: Omit<Parameters<typeof _666Ae97f>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _666Ae97f>[1], 'throwOnError'>) {
    return getDataOrThrow(_666Ae97f(addTenantToParameters(parameters), options));
}

/**
 * Add a user to a group
 */
export function addUserToGroup(parameters: Omit<Parameters<typeof _0331D20E8>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0331D20E8>[1], 'throwOnError'>) {
    return getDataOrThrow(_0331D20E8(addTenantToParameters(parameters), options));
}
