// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _01367005c, _043724297, _04Bf1164b, _35802F8f, _3Cb22532, _6998Eead } from '../sdk.gen';
import type { IamInvitationControllerApiInvitationCreateRequest } from '../types.gen';

export function findAllInvitationsForCurrentUser(options?: Omit<Parameters<typeof _6998Eead>[0], 'throwOnError'>) {
    return getDataOrThrow(_6998Eead(options));
}

/**
 * Create an invitation
 */
export function createInvitation(parameters: IamInvitationControllerApiInvitationCreateRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _04Bf1164b>[1], 'throwOnError'>) {
    return getDataOrThrow(_04Bf1164b({ tenant: resolveTenant(parameters?.tenant), iamInvitationControllerApiInvitationCreateRequest: parameters }, options));
}

/**
 * Retrieve all invitations for a given email
 */
export function listInvitationsByEmail(parameters: Omit<Parameters<typeof _043724297>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _043724297>[1], 'throwOnError'>) {
    return getDataOrThrow(_043724297(addTenantToParameters(parameters), options));
}

/**
 * Search for invitations
 */
export function searchInvitations(parameters: Omit<Parameters<typeof _3Cb22532>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _3Cb22532>[1], 'throwOnError'>) {
    return getDataOrThrow(_3Cb22532(addTenantToParameters(parameters), options));
}

/**
 * Delete an invitation
 */
export function deleteInvitation(parameters: Omit<Parameters<typeof _01367005c>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _01367005c>[1], 'throwOnError'>) {
    return getDataOrThrow(_01367005c(addTenantToParameters(parameters), options));
}

/**
 * Retrieve an invitation
 */
export function getInvitation(parameters: Omit<Parameters<typeof _35802F8f>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _35802F8f>[1], 'throwOnError'>) {
    return getDataOrThrow(_35802F8f(addTenantToParameters(parameters), options));
}
