// This file is auto-generated by @hey-api/openapi-ts

import { getDataOrThrow } from './shared.gen';
import { _0380059D8, _1013D24e, _489De83d, _56C0Cddb } from '../sdk.gen';
import type { KillSwitch } from '../types.gen';

/**
 * Create a kill switch
 */
export function createKillSwitch(parameters: KillSwitch, options?: Omit<Parameters<typeof _1013D24e>[1], 'throwOnError'>) {
    return getDataOrThrow(_1013D24e({ killSwitch: parameters }, options));
}

export function searchKillSwitches(options?: Omit<Parameters<typeof _0380059D8>[0], 'throwOnError'>) {
    return getDataOrThrow(_0380059D8(options));
}

export function deleteKillSwitch(parameters: Parameters<typeof _489De83d>[0], options?: Omit<Parameters<typeof _489De83d>[1], 'throwOnError'>) {
    return getDataOrThrow(_489De83d(parameters, options));
}

/**
 * Update a kill switch
 */
export function updateKillSwitch(parameters: Omit<Parameters<typeof _56C0Cddb>[0], 'killSwitch'> & KillSwitch, options?: Omit<Parameters<typeof _56C0Cddb>[1], 'throwOnError'>) {
    return getDataOrThrow(_56C0Cddb({ ...parameters, killSwitch: parameters }, options));
}
