// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _023C90349, _043D2910a, _057232872, _05D06Cae3, _066Ce9C38, _06C163B2c } from '../sdk.gen';
import type { KvControllerApiDeleteBulkRequest } from '../types.gen';

/**
 * List all keys
 */
export const listAllKeys = (parameters?: Omit<Parameters<typeof _023C90349>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _023C90349>[1], 'throwOnError'>) => getDataOrThrow(_023C90349(addTenantToParameters(parameters), options));

/**
 * Bulk-delete multiple key/value pairs from the given namespace.
 */
export const deleteKeyValues = (parameters: Omit<Parameters<typeof _043D2910a>[0], 'kvControllerApiDeleteBulkRequest' | 'tenant'> & KvControllerApiDeleteBulkRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _043D2910a>[1], 'throwOnError'>) => getDataOrThrow(_043D2910a({
    ...parameters,
    tenant: resolveTenant(parameters?.tenant),
    kvControllerApiDeleteBulkRequest: parameters
}, options));

/**
 * List all keys for inherited namespaces
 */
export const listKeysWithInheritence = (parameters: Omit<Parameters<typeof _057232872>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _057232872>[1], 'throwOnError'>) => getDataOrThrow(_057232872(addTenantToParameters(parameters), options));

/**
 * Delete a key-value pair
 */
export const deleteKeyValue = (parameters: Omit<Parameters<typeof _05D06Cae3>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _05D06Cae3>[1], 'throwOnError'>) => getDataOrThrow(_05D06Cae3(addTenantToParameters(parameters), options));

/**
 * Get value for a key
 */
export const keyValue = (parameters: Omit<Parameters<typeof _066Ce9C38>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _066Ce9C38>[1], 'throwOnError'>) => getDataOrThrow(_066Ce9C38(addTenantToParameters(parameters), options));

/**
 * Puts a key-value pair in store
 */
export const setKeyValue = (parameters: Omit<Parameters<typeof _06C163B2c>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _06C163B2c>[1], 'throwOnError'>) => getDataOrThrow(_06C163B2c(addTenantToParameters(parameters), options));
