// This file is auto-generated by @hey-api/openapi-ts

import { getDataOrThrow } from './shared.gen';
import { _625Ef69 } from '../sdk.gen';
import type { UsernamePasswordCredentials } from '../types.gen';

export function login(parameters: UsernamePasswordCredentials, options?: Omit<Parameters<typeof _625Ef69>[1], 'throwOnError'>) {
    return getDataOrThrow(_625Ef69({ usernamePasswordCredentials: parameters }, options));
}
