// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow } from './shared.gen';
import { _0292596F9, _02A5C7489, _06C136Fdf, _075A36Ca9, _21216412, _459D2D6e, _4Ca5D6B4, _74Ae0977 } from '../sdk.gen';

/**
 * Delete a list of logs by their ids
 */
export const deleteLogsByIds = (parameters: Omit<Parameters<typeof _0292596F9>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0292596F9>[1], 'throwOnError'>) => getDataOrThrow(_0292596F9(addTenantToParameters(parameters), options));

/**
 * Delete logs matching the given filters
 */
export const deleteLogsByQuery = (parameters?: Omit<Parameters<typeof _075A36Ca9>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _075A36Ca9>[1], 'throwOnError'>) => getDataOrThrow(_075A36Ca9(addTenantToParameters(parameters), options));

/**
 * Search for logs
 */
export const searchLogs = (parameters?: Omit<Parameters<typeof _02A5C7489>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _02A5C7489>[1], 'throwOnError'>) => getDataOrThrow(_02A5C7489(addTenantToParameters(parameters), options));

/**
 * Delete logs for a specific execution, taskrun or task
 */
export const deleteLogsFromExecution = (parameters: Omit<Parameters<typeof _4Ca5D6B4>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _4Ca5D6B4>[1], 'throwOnError'>) => getDataOrThrow(_4Ca5D6B4(addTenantToParameters(parameters), options));

/**
 * Get logs for a specific execution, taskrun or task
 */
export const listLogsFromExecution = (parameters: Omit<Parameters<typeof _06C136Fdf>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _06C136Fdf>[1], 'throwOnError'>) => getDataOrThrow(_06C136Fdf(addTenantToParameters(parameters), options));

/**
 * Download logs for a specific execution, taskrun or task
 */
export const downloadLogsFromExecution = (parameters: Omit<Parameters<typeof _74Ae0977>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _74Ae0977>[1], 'throwOnError'>) => getDataOrThrow(_74Ae0977(addTenantToParameters(parameters), options));

/**
 * Follow logs for a specific execution
 */
export const followLogsFromExecution = (parameters: Omit<Parameters<typeof _459D2D6e>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _459D2D6e>[1], 'throwOnError'>) => _459D2D6e(addTenantToParameters(parameters), options);

/**
 * Delete logs for a specific execution, taskrun or task
 */
export const deleteLogsFromFlow = (parameters: Omit<Parameters<typeof _21216412>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _21216412>[1], 'throwOnError'>) => getDataOrThrow(_21216412(addTenantToParameters(parameters), options));
