// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow } from './shared.gen';
import { _02A5C7489, _06C136Fdf, _21216412, _459D2D6e, _4Ca5D6B4, _74Ae0977 } from '../sdk.gen';

/**
 * Search for logs
 */
export function searchLogs(parameters?: Omit<Parameters<typeof _02A5C7489>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _02A5C7489>[1], 'throwOnError'>) {
    return getDataOrThrow(_02A5C7489(addTenantToParameters(parameters), options));
}

/**
 * Delete logs for a specific execution, taskrun or task
 */
export function deleteLogsFromExecution(parameters: Omit<Parameters<typeof _4Ca5D6B4>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _4Ca5D6B4>[1], 'throwOnError'>) {
    return getDataOrThrow(_4Ca5D6B4(addTenantToParameters(parameters), options));
}

/**
 * Get logs for a specific execution, taskrun or task
 */
export function listLogsFromExecution(parameters: Omit<Parameters<typeof _06C136Fdf>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _06C136Fdf>[1], 'throwOnError'>) {
    return getDataOrThrow(_06C136Fdf(addTenantToParameters(parameters), options));
}

/**
 * Download logs for a specific execution, taskrun or task
 */
export function downloadLogsFromExecution(parameters: Omit<Parameters<typeof _74Ae0977>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _74Ae0977>[1], 'throwOnError'>) {
    return getDataOrThrow(_74Ae0977(addTenantToParameters(parameters), options));
}

/**
 * Follow logs for a specific execution
 */
export function followLogsFromExecution(parameters: Omit<Parameters<typeof _459D2D6e>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _459D2D6e>[1], 'throwOnError'>) {
    return _459D2D6e(addTenantToParameters(parameters), options);
}

/**
 * Delete logs for a specific execution, taskrun or task
 */
export function deleteLogsFromFlow(parameters: Omit<Parameters<typeof _21216412>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _21216412>[1], 'throwOnError'>) {
    return getDataOrThrow(_21216412(addTenantToParameters(parameters), options));
}
