// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _01561Bc11, _049932423, _04A77A99c, _0742Eabef, _23Aa1Afe, _382Ac1A6, _5031B3D7 } from '../sdk.gen';
import type { ApiMcpServerWritable } from '../types.gen';

/**
 * List MCP servers
 */
export const listMcps = (parameters?: Omit<Parameters<typeof _5031B3D7>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _5031B3D7>[1], 'throwOnError'>) => getDataOrThrow(_5031B3D7(addTenantToParameters(parameters), options));

/**
 * Create an MCP server
 */
export const createMcp = (parameters: ApiMcpServerWritable & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _23Aa1Afe>[1], 'throwOnError'>) => getDataOrThrow(_23Aa1Afe({ tenant: resolveTenant(parameters?.tenant), apiMcpServerWritable: parameters }, options));

/**
 * Delete an MCP server
 */
export const deleteMcp = (parameters: Omit<Parameters<typeof _01561Bc11>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _01561Bc11>[1], 'throwOnError'>) => getDataOrThrow(_01561Bc11(addTenantToParameters(parameters), options));

/**
 * Get an MCP server
 */
export const mcp = (parameters: Omit<Parameters<typeof _04A77A99c>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _04A77A99c>[1], 'throwOnError'>) => getDataOrThrow(_04A77A99c(addTenantToParameters(parameters), options));

/**
 * Update an MCP server
 */
export const updateMcp = (parameters: Omit<Parameters<typeof _0742Eabef>[0], 'apiMcpServerWritable' | 'tenant'> & ApiMcpServerWritable & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0742Eabef>[1], 'throwOnError'>) => getDataOrThrow(_0742Eabef({
    ...parameters,
    tenant: resolveTenant(parameters?.tenant),
    apiMcpServerWritable: parameters
}, options));

/**
 * Toggle an MCP server's enabled state
 */
export const toggleMcp = (parameters: Omit<Parameters<typeof _382Ac1A6>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _382Ac1A6>[1], 'throwOnError'>) => getDataOrThrow(_382Ac1A6(addTenantToParameters(parameters), options));

/**
 * List tools exposed by an MCP server
 */
export const listTools = (parameters: Omit<Parameters<typeof _049932423>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _049932423>[1], 'throwOnError'>) => getDataOrThrow(_049932423(addTenantToParameters(parameters), options));
