// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow } from './shared.gen';
import { _041Bfcd8d, _041C601E4, _22F15037, _3Acedc00, _48B0B9B9, _64625D6d } from '../sdk.gen';

/**
 * Get metrics aggregations for a specific flow
 */
export const aggregateMetricsFromFlow = (parameters: Omit<Parameters<typeof _041C601E4>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _041C601E4>[1], 'throwOnError'>) => getDataOrThrow(_041C601E4(addTenantToParameters(parameters), options));

/**
 * Get metrics aggregations for a specific flow
 */
export const aggregateMetricsFromTask = (parameters: Omit<Parameters<typeof _041Bfcd8d>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _041Bfcd8d>[1], 'throwOnError'>) => getDataOrThrow(_041Bfcd8d(addTenantToParameters(parameters), options));

/**
 * Get metrics names for a specific flow
 */
export const listFlowMetrics = (parameters: Omit<Parameters<typeof _22F15037>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _22F15037>[1], 'throwOnError'>) => getDataOrThrow(_22F15037(addTenantToParameters(parameters), options));

/**
 * Get metrics names for a specific task in a flow
 */
export const listTaskMetrics = (parameters: Omit<Parameters<typeof _3Acedc00>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _3Acedc00>[1], 'throwOnError'>) => getDataOrThrow(_3Acedc00(addTenantToParameters(parameters), options));

/**
 * Get tasks id that have metrics for a specific flow, include deleted or renamed tasks
 */
export const listTasksWithMetrics = (parameters: Omit<Parameters<typeof _64625D6d>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _64625D6d>[1], 'throwOnError'>) => getDataOrThrow(_64625D6d(addTenantToParameters(parameters), options));

/**
 * Get metrics for a specific execution
 */
export const searchByExecution = (parameters: Omit<Parameters<typeof _48B0B9B9>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _48B0B9B9>[1], 'throwOnError'>) => getDataOrThrow(_48B0B9B9(addTenantToParameters(parameters), options));
