// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _04167Ea76, _0753B2353, _078936A73, _30933140, _334059E8, _435C395a, _475D2A03, _625Ef69, _6A59A9Ad } from '../sdk.gen';
import type { BasicAuthCredentials, MiscControllerLoginRequest } from '../types.gen';

export const basicAuthConfigErrors = (options?: Omit<Parameters<typeof _6A59A9Ad>[0], 'throwOnError'>) => getDataOrThrow(_6A59A9Ad(options));

export const configuration = (options?: Omit<Parameters<typeof _30933140>[0], 'throwOnError'>) => getDataOrThrow(_30933140(options));

export const loginConfiguration = (options?: Omit<Parameters<typeof _475D2A03>[0], 'throwOnError'>) => getDataOrThrow(_475D2A03(options));

/**
 * Authenticate with basic auth credentials.
 */
export const login = (parameters: MiscControllerLoginRequest, options?: Omit<Parameters<typeof _625Ef69>[1], 'throwOnError'>) => getDataOrThrow(_625Ef69({ miscControllerLoginRequest: parameters }, options));

export const logout = (options?: Omit<Parameters<typeof _04167Ea76>[0], 'throwOnError'>) => getDataOrThrow(_04167Ea76(options));

export const expressionFilters = (options?: Omit<Parameters<typeof _078936A73>[0], 'throwOnError'>) => getDataOrThrow(_078936A73(options));

export const expressionFunctions = (options?: Omit<Parameters<typeof _0753B2353>[0], 'throwOnError'>) => getDataOrThrow(_0753B2353(options));

/**
 * Configure basic authentication for the instance.
 */
export const createBasicAuth = (parameters: BasicAuthCredentials & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _435C395a>[1], 'throwOnError'>) => getDataOrThrow(_435C395a({ tenant: resolveTenant(parameters?.tenant), basicAuthCredentials: parameters }, options));

/**
 * Retrieve instance usage information
 */
export const usages = (parameters?: Omit<Parameters<typeof _334059E8>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _334059E8>[1], 'throwOnError'>) => getDataOrThrow(_334059E8(addTenantToParameters(parameters), options));
