// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _02437E287, _0263Aab71, _02B2002Fa, _033Ccd4Fe, _05690531a, _068E39279, _0753B2353, _078936A73, _2C5384F6, _30933140, _334059E8, _435C395a, _48B8043b, _50Eb0692, _6108Ef36, _6A59A9Ad, _6Be81575, _70177F17 } from '../sdk.gen';
import type { BasicAuthCredentials, SetupConfigurationSetupData } from '../types.gen';

export function getBasicAuthConfigErrors(options?: Omit<Parameters<typeof _6A59A9Ad>[0], 'throwOnError'>) {
    return getDataOrThrow(_6A59A9Ad(options));
}

export function getConfiguration(options?: Omit<Parameters<typeof _30933140>[0], 'throwOnError'>) {
    return getDataOrThrow(_30933140(options));
}

export function licenseInfo(options?: Omit<Parameters<typeof _0263Aab71>[0], 'throwOnError'>) {
    return getDataOrThrow(_0263Aab71(options));
}

export function refreshLicense(options?: Omit<Parameters<typeof _05690531a>[0], 'throwOnError'>) {
    return getDataOrThrow(_05690531a(options));
}

export function mainTenantFlows(options?: Omit<Parameters<typeof _033Ccd4Fe>[0], 'throwOnError'>) {
    return getDataOrThrow(_033Ccd4Fe(options));
}

export function getExpressionFilters(options?: Omit<Parameters<typeof _078936A73>[0], 'throwOnError'>) {
    return getDataOrThrow(_078936A73(options));
}

export function getExpressionFunctions(options?: Omit<Parameters<typeof _0753B2353>[0], 'throwOnError'>) {
    return getDataOrThrow(_0753B2353(options));
}

export function setupConfiguration(options?: Omit<Parameters<typeof _02437E287>[0], 'throwOnError'>) {
    return getDataOrThrow(_02437E287(options));
}

/**
 * Create the first Superadmin user
 */
export function setupKestra(parameters: SetupConfigurationSetupData, options?: Omit<Parameters<typeof _068E39279>[1], 'throwOnError'>) {
    return getDataOrThrow(_068E39279({ setupConfigurationSetupData: parameters }, options));
}

/**
 * Retrieve resource-to-actions mapping
 */
export function listPermissions(parameters?: Omit<Parameters<typeof _02B2002Fa>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _02B2002Fa>[1], 'throwOnError'>) {
    return getDataOrThrow(_02B2002Fa(addTenantToParameters(parameters), options));
}

/**
 * Retrieve managed role templates
 */
export function listTemplates(parameters?: Omit<Parameters<typeof _48B8043b>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _48B8043b>[1], 'throwOnError'>) {
    return getDataOrThrow(_48B8043b(addTenantToParameters(parameters), options));
}

/**
 * Configure basic authentication for the instance.
 */
export function createBasicAuth(parameters: BasicAuthCredentials & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _435C395a>[1], 'throwOnError'>) {
    return getDataOrThrow(_435C395a({ tenant: resolveTenant(parameters?.tenant), basicAuthCredentials: parameters }, options));
}

export function generate(parameters?: Omit<Parameters<typeof _6Be81575>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _6Be81575>[1], 'throwOnError'>) {
    return getDataOrThrow(_6Be81575(addTenantToParameters(parameters), options));
}

/**
 * Retrieve debug information for a support ticket
 */
export function supportDebugInfo(parameters?: Omit<Parameters<typeof _50Eb0692>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _50Eb0692>[1], 'throwOnError'>) {
    return getDataOrThrow(_50Eb0692(addTenantToParameters(parameters), options));
}

/**
 * Forward support ticket to configured registry proxy
 */
export function forwardSupportTicket(parameters: Omit<Parameters<typeof _2C5384F6>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _2C5384F6>[1], 'throwOnError'>) {
    return getDataOrThrow(_2C5384F6(addTenantToParameters(parameters), options));
}

/**
 * Retrieve usage information for the current tenant
 */
export function tenantUsage(parameters?: Omit<Parameters<typeof _70177F17>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _70177F17>[1], 'throwOnError'>) {
    return getDataOrThrow(_70177F17(addTenantToParameters(parameters), options));
}

/**
 * Retrieve instance usage information
 */
export function getUsages(parameters?: Omit<Parameters<typeof _334059E8>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _334059E8>[1], 'throwOnError'>) {
    return getDataOrThrow(_334059E8(addTenantToParameters(parameters), options));
}

/**
 * List worker-selector tags available to the current tenant
 */
export function workerSelectorTags(parameters?: Omit<Parameters<typeof _6108Ef36>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _6108Ef36>[1], 'throwOnError'>) {
    return getDataOrThrow(_6108Ef36(addTenantToParameters(parameters), options));
}
