// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _03F73Cd01, _0755159C0, _4A10C6A5, _548A6080 } from '../sdk.gen';
import type { ApiAutocomplete } from '../types.gen';

/**
 * List namespaces for autocomplete
 */
export const autocompleteNamespaces = (parameters: ApiAutocomplete & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _548A6080>[1], 'throwOnError'>) => getDataOrThrow(_548A6080({ tenant: resolveTenant(parameters?.tenant), apiAutocomplete: parameters }, options));

/**
 * Search for namespaces
 */
export const searchNamespaces = (parameters?: Omit<Parameters<typeof _0755159C0>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0755159C0>[1], 'throwOnError'>) => getDataOrThrow(_0755159C0(addTenantToParameters(parameters), options));

/**
 * Get a namespace
 */
export const loadNamespace = (parameters: Omit<Parameters<typeof _4A10C6A5>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _4A10C6A5>[1], 'throwOnError'>) => getDataOrThrow(_4A10C6A5(addTenantToParameters(parameters), options));

/**
 * List inherited secrets
 */
export const inheritedSecrets = (parameters: Omit<Parameters<typeof _03F73Cd01>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _03F73Cd01>[1], 'throwOnError'>) => getDataOrThrow(_03F73Cd01(addTenantToParameters(parameters), options));
