// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _01De71843, _02E276Bc5, _03F73Cd01, _05Edac887, _06D81F16e, _071E8524c, _0755159C0, _0Cb0D041, _1Fe10518, _4A10C6A5, _4A4Df41f, _548A6080, _695A5Daa, _79431Ff0 } from '../sdk.gen';
import type { ApiAutocomplete, ApiSecretMetaEe, ApiSecretValue, Namespace } from '../types.gen';

/**
 * Create a namespace
 */
export function createNamespace(parameters: Namespace & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0Cb0D041>[1], 'throwOnError'>) {
    return getDataOrThrow(_0Cb0D041({ tenant: resolveTenant(parameters?.tenant), namespace: parameters }, options));
}

/**
 * List namespaces for autocomplete
 */
export function autocompleteNamespaces(parameters: ApiAutocomplete & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _548A6080>[1], 'throwOnError'>) {
    return getDataOrThrow(_548A6080({ tenant: resolveTenant(parameters?.tenant), apiAutocomplete: parameters }, options));
}

/**
 * Search for namespaces
 */
export function searchNamespaces(parameters: Omit<Parameters<typeof _0755159C0>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0755159C0>[1], 'throwOnError'>) {
    return getDataOrThrow(_0755159C0(addTenantToParameters(parameters), options));
}

/**
 * Delete a namespace
 */
export function deleteNamespace(parameters: Omit<Parameters<typeof _79431Ff0>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _79431Ff0>[1], 'throwOnError'>) {
    return getDataOrThrow(_79431Ff0(addTenantToParameters(parameters), options));
}

/**
 * Get a namespace
 */
export function getNamespace(parameters: Omit<Parameters<typeof _4A10C6A5>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _4A10C6A5>[1], 'throwOnError'>) {
    return getDataOrThrow(_4A10C6A5(addTenantToParameters(parameters), options));
}

/**
 * Update a namespace
 */
export function updateNamespace(parameters: Omit<Parameters<typeof _06D81F16e>[0], 'namespace' | 'tenant'> & Namespace & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _06D81F16e>[1], 'throwOnError'>) {
    return getDataOrThrow(_06D81F16e({
        ...parameters,
        tenant: resolveTenant(parameters?.tenant),
        namespace: parameters
    }, options));
}

/**
 * List inherited plugin defaults
 */
export function inheritedPluginDefaults(parameters: Omit<Parameters<typeof _4A4Df41f>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _4A4Df41f>[1], 'throwOnError'>) {
    return getDataOrThrow(_4A4Df41f(addTenantToParameters(parameters), options));
}

/**
 * List inherited variables
 */
export function inheritedVariables(parameters: Omit<Parameters<typeof _01De71843>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _01De71843>[1], 'throwOnError'>) {
    return getDataOrThrow(_01De71843(addTenantToParameters(parameters), options));
}

/**
 * Export this namespace plugin defaults
 */
export function exportPluginDefaults(parameters: Omit<Parameters<typeof _05Edac887>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _05Edac887>[1], 'throwOnError'>) {
    return getDataOrThrow(_05Edac887(addTenantToParameters(parameters), options));
}

/**
 * Import plugin defaults in this namespace
 */
export function importPluginDefaults(parameters: Omit<Parameters<typeof _695A5Daa>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _695A5Daa>[1], 'throwOnError'>) {
    return getDataOrThrow(_695A5Daa(addTenantToParameters(parameters), options));
}

/**
 * List inherited secrets
 */
export function getInheritedSecrets(parameters: Omit<Parameters<typeof _03F73Cd01>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _03F73Cd01>[1], 'throwOnError'>) {
    return getDataOrThrow(_03F73Cd01(addTenantToParameters(parameters), options));
}

/**
 * Update secrets for a namespace
 */
export function putSecrets(parameters: Omit<Parameters<typeof _071E8524c>[0], 'apiSecretValue' | 'tenant'> & ApiSecretValue & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _071E8524c>[1], 'throwOnError'>) {
    return getDataOrThrow(_071E8524c({
        ...parameters,
        tenant: resolveTenant(parameters?.tenant),
        apiSecretValue: parameters
    }, options));
}

/**
 * Delete a secret for a namespace
 */
export function deleteSecret(parameters: Omit<Parameters<typeof _02E276Bc5>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _02E276Bc5>[1], 'throwOnError'>) {
    return getDataOrThrow(_02E276Bc5(addTenantToParameters(parameters), options));
}

/**
 * Patch a secret metadata for a namespace
 */
export function patchSecret(parameters: Omit<Parameters<typeof _1Fe10518>[0], 'apiSecretMetaEe' | 'tenant'> & ApiSecretMetaEe & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _1Fe10518>[1], 'throwOnError'>) {
    return getDataOrThrow(_1Fe10518({
        ...parameters,
        tenant: resolveTenant(parameters?.tenant),
        apiSecretMetaEe: parameters
    }, options));
}
