// This file is auto-generated by @hey-api/openapi-ts

import { getDataOrThrow } from './shared.gen';
import { _03Fd61D60, _06C5Bb0B6, _093D9545, _270358Dc, _373Fe494, _537133D6, eafa603 } from '../sdk.gen';

export const listenUserNotifications = (options?: Omit<Parameters<typeof _537133D6>[0], 'throwOnError'>) => _537133D6(options);

export const history_ = (parameters?: Parameters<typeof _373Fe494>[0], options?: Omit<Parameters<typeof _373Fe494>[1], 'throwOnError'>) => getDataOrThrow(_373Fe494(parameters, options));

export const markAllRead = (options?: Omit<Parameters<typeof _06C5Bb0B6>[0], 'throwOnError'>) => getDataOrThrow(_06C5Bb0B6(options));

export const pollSince = (parameters: Parameters<typeof _093D9545>[0], options?: Omit<Parameters<typeof _093D9545>[1], 'throwOnError'>) => getDataOrThrow(_093D9545(parameters, options));

export const unreadCount = (options?: Omit<Parameters<typeof _03Fd61D60>[0], 'throwOnError'>) => getDataOrThrow(_03Fd61D60(options));

export const markRead = (parameters: Parameters<typeof eafa603>[0], options?: Omit<Parameters<typeof eafa603>[1], 'throwOnError'>) => getDataOrThrow(eafa603(parameters, options));

export const markUnread = (parameters: Parameters<typeof _270358Dc>[0], options?: Omit<Parameters<typeof _270358Dc>[1], 'throwOnError'>) => getDataOrThrow(_270358Dc(parameters, options));
