// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow } from './shared.gen';
import { _02Fb2086b, _1Df97Ee2, _5A13D0D0 } from '../sdk.gen';

/**
 * Get the flow-level outputs of an execution
 */
export const executionOutputs = (parameters: Omit<Parameters<typeof _5A13D0D0>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _5A13D0D0>[1], 'throwOnError'>) => getDataOrThrow(_5A13D0D0(addTenantToParameters(parameters), options));

/**
 * List the task runs of an execution having outputs
 */
export const taskOutputsInformation = (parameters: Omit<Parameters<typeof _02Fb2086b>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _02Fb2086b>[1], 'throwOnError'>) => getDataOrThrow(_02Fb2086b(addTenantToParameters(parameters), options));

/**
 * Get task run outputs
 */
export const taskRunOutputs = (parameters: Omit<Parameters<typeof _1Df97Ee2>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _1Df97Ee2>[1], 'throwOnError'>) => getDataOrThrow(_1Df97Ee2(addTenantToParameters(parameters), options));
