// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow } from './shared.gen';
import { _02Fb2086b, _1Df97Ee2 } from '../sdk.gen';

/**
 * Get task run outputs
 */
export const taskOutputsInformation = (parameters: Omit<Parameters<typeof _02Fb2086b>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _02Fb2086b>[1], 'throwOnError'>) => getDataOrThrow(_02Fb2086b(addTenantToParameters(parameters), options));

/**
 * Get task run outputs
 */
export const taskRunOutputs = (parameters: Omit<Parameters<typeof _1Df97Ee2>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _1Df97Ee2>[1], 'throwOnError'>) => getDataOrThrow(_1Df97Ee2(addTenantToParameters(parameters), options));
