// This file is auto-generated by @hey-api/openapi-ts

import { getDataOrThrow } from './shared.gen';
import { _01C907F3e, _0229397B6, _023E2Be03, _028D5F9Be, _02D5B2720, _034F04E13, _03C2494Fa, _046C7F41c, _04B060Ef4, _04C6659B3, _07477A414, _07Ae22D38, _09Bfeede, _0Aad6466, _20858736, _30C1Aea6, _36Cc3F94, _402B3Be4, _557632E4, _56210B11, _59325214, _6379A635, _6Bf6A12b, _6Fb73243, _729F184e, _7F997Ca0, d02B69d, e16C271 } from '../sdk.gen';
import type { InstanceControllerApiPluginListRequest } from '../types.gen';

export function listVersionedPlugin(parameters: Parameters<typeof _04B060Ef4>[0], options?: Omit<Parameters<typeof _04B060Ef4>[1], 'throwOnError'>) {
    return getDataOrThrow(_04B060Ef4(parameters, options));
}

export function listAvailableVersionedPlugins(options?: Omit<Parameters<typeof _59325214>[0], 'throwOnError'>) {
    return getDataOrThrow(_59325214(options));
}

export function listAvailableVersionedPluginsForSecretManager(options?: Omit<Parameters<typeof _07Ae22D38>[0], 'throwOnError'>) {
    return getDataOrThrow(_07Ae22D38(options));
}

export function listAvailableVersionedPluginsForStorage(options?: Omit<Parameters<typeof _30C1Aea6>[0], 'throwOnError'>) {
    return getDataOrThrow(_30C1Aea6(options));
}

/**
 * Install specified plugin artifacts
 */
export function installVersionedPlugins(parameters: InstanceControllerApiPluginListRequest, options?: Omit<Parameters<typeof _046C7F41c>[1], 'throwOnError'>) {
    return getDataOrThrow(_046C7F41c({ instanceControllerApiPluginListRequest: parameters }, options));
}

/**
 * Resolve versions for specified plugin artifacts
 */
export function resolveVersionedPlugins(parameters: InstanceControllerApiPluginListRequest, options?: Omit<Parameters<typeof _6379A635>[1], 'throwOnError'>) {
    return getDataOrThrow(_6379A635({ instanceControllerApiPluginListRequest: parameters }, options));
}

/**
 * Uninstall plugin artifacts
 */
export function uninstallVersionedPlugins(parameters: InstanceControllerApiPluginListRequest, options?: Omit<Parameters<typeof _6Bf6A12b>[1], 'throwOnError'>) {
    return getDataOrThrow(_6Bf6A12b({ instanceControllerApiPluginListRequest: parameters }, options));
}

/**
 * Upload a plugin artifact JAR file
 */
export function uploadVersionedPlugins(parameters: Parameters<typeof _0229397B6>[0], options?: Omit<Parameters<typeof _0229397B6>[1], 'throwOnError'>) {
    return getDataOrThrow(_0229397B6(parameters, options));
}

export function getVersionedPluginDetails(parameters: Parameters<typeof _729F184e>[0], options?: Omit<Parameters<typeof _729F184e>[1], 'throwOnError'>) {
    return getDataOrThrow(_729F184e(parameters, options));
}

export function getVersionedPluginIcon(parameters: Parameters<typeof _034F04E13>[0], options?: Omit<Parameters<typeof _034F04E13>[1], 'throwOnError'>) {
    return getDataOrThrow(_034F04E13(parameters, options));
}

export function getPluginReleaseNotesContent(parameters: Parameters<typeof _20858736>[0], options?: Omit<Parameters<typeof _20858736>[1], 'throwOnError'>) {
    return getDataOrThrow(_20858736(parameters, options));
}

export function getVersionedPluginDetailsFromVersion(parameters: Parameters<typeof _7F997Ca0>[0], options?: Omit<Parameters<typeof _7F997Ca0>[1], 'throwOnError'>) {
    return getDataOrThrow(_7F997Ca0(parameters, options));
}

export function listPlugins(parameters?: Parameters<typeof _09Bfeede>[0], options?: Omit<Parameters<typeof _09Bfeede>[1], 'throwOnError'>) {
    return getDataOrThrow(_09Bfeede(parameters, options));
}

export function getPluginBySubgroups(options?: Omit<Parameters<typeof _36Cc3F94>[0], 'throwOnError'>) {
    return getDataOrThrow(_36Cc3F94(options));
}

export function getPluginIcons(options?: Omit<Parameters<typeof e16C271>[0], 'throwOnError'>) {
    return getDataOrThrow(e16C271(options));
}

export function getPluginGroupIcons(options?: Omit<Parameters<typeof _557632E4>[0], 'throwOnError'>) {
    return getDataOrThrow(_557632E4(options));
}

export function getPluginIcon(parameters: Parameters<typeof _028D5F9Be>[0], options?: Omit<Parameters<typeof _028D5F9Be>[1], 'throwOnError'>) {
    return getDataOrThrow(_028D5F9Be(parameters, options));
}

export function getPluginIconSvg(parameters: Parameters<typeof _01C907F3e>[0], options?: Omit<Parameters<typeof _01C907F3e>[1], 'throwOnError'>) {
    return getDataOrThrow(_01C907F3e(parameters, options));
}

export function getAllInputTypes(options?: Omit<Parameters<typeof _0Aad6466>[0], 'throwOnError'>) {
    return getDataOrThrow(_0Aad6466(options));
}

export function getSchemaFromInputType(parameters: Parameters<typeof _6Fb73243>[0], options?: Omit<Parameters<typeof _6Fb73243>[1], 'throwOnError'>) {
    return getDataOrThrow(_6Fb73243(parameters, options));
}

export function getPluginUiManifest(parameters: Parameters<typeof _07477A414>[0], options?: Omit<Parameters<typeof _07477A414>[1], 'throwOnError'>) {
    return getDataOrThrow(_07477A414(parameters, options));
}

export function getPropertiesFromType(parameters: Parameters<typeof _04C6659B3>[0], options?: Omit<Parameters<typeof _04C6659B3>[1], 'throwOnError'>) {
    return getDataOrThrow(_04C6659B3(parameters, options));
}

export function getSchemasFromType(parameters: Parameters<typeof _02D5B2720>[0], options?: Omit<Parameters<typeof _02D5B2720>[1], 'throwOnError'>) {
    return getDataOrThrow(_02D5B2720(parameters, options));
}

export function listTriggerPlugins(options?: Omit<Parameters<typeof _03C2494Fa>[0], 'throwOnError'>) {
    return getDataOrThrow(_03C2494Fa(options));
}

export function getPluginDocumentation(parameters: Parameters<typeof _56210B11>[0], options?: Omit<Parameters<typeof _56210B11>[1], 'throwOnError'>) {
    return getDataOrThrow(_56210B11(parameters, options));
}

export function getPluginVersions(parameters: Parameters<typeof _402B3Be4>[0], options?: Omit<Parameters<typeof _402B3Be4>[1], 'throwOnError'>) {
    return getDataOrThrow(_402B3Be4(parameters, options));
}

export function getPluginDocumentationFromVersion(parameters: Parameters<typeof _023E2Be03>[0], options?: Omit<Parameters<typeof _023E2Be03>[1], 'throwOnError'>) {
    return getDataOrThrow(_023E2Be03(parameters, options));
}

export function getPluginUi(parameters: Parameters<typeof d02B69d>[0], options?: Omit<Parameters<typeof d02B69d>[1], 'throwOnError'>) {
    return getDataOrThrow(d02B69d(parameters, options));
}
