// This file is auto-generated by @hey-api/openapi-ts

import { getDataOrThrow } from './shared.gen';
import { _01C907F3e, _023E2Be03, _028D5F9Be, _02D5B2720, _03C2494Fa, _04C6659B3, _07477A414, _09Bfeede, _0Aad6466, _36Cc3F94, _402B3Be4, _557632E4, _56210B11, _6Fb73243, d02B69d, e16C271 } from '../sdk.gen';

export const listPlugins = (parameters?: Parameters<typeof _09Bfeede>[0], options?: Omit<Parameters<typeof _09Bfeede>[1], 'throwOnError'>) => getDataOrThrow(_09Bfeede(parameters, options));

export const pluginBySubgroups = (options?: Omit<Parameters<typeof _36Cc3F94>[0], 'throwOnError'>) => getDataOrThrow(_36Cc3F94(options));

export const pluginIcons = (options?: Omit<Parameters<typeof e16C271>[0], 'throwOnError'>) => getDataOrThrow(e16C271(options));

export const pluginGroupIcons = (options?: Omit<Parameters<typeof _557632E4>[0], 'throwOnError'>) => getDataOrThrow(_557632E4(options));

export const pluginIcon = (parameters: Parameters<typeof _028D5F9Be>[0], options?: Omit<Parameters<typeof _028D5F9Be>[1], 'throwOnError'>) => getDataOrThrow(_028D5F9Be(parameters, options));

export const pluginIconSvg = (parameters: Parameters<typeof _01C907F3e>[0], options?: Omit<Parameters<typeof _01C907F3e>[1], 'throwOnError'>) => getDataOrThrow(_01C907F3e(parameters, options));

export const allInputTypes = (options?: Omit<Parameters<typeof _0Aad6466>[0], 'throwOnError'>) => getDataOrThrow(_0Aad6466(options));

export const schemaFromInputType = (parameters: Parameters<typeof _6Fb73243>[0], options?: Omit<Parameters<typeof _6Fb73243>[1], 'throwOnError'>) => getDataOrThrow(_6Fb73243(parameters, options));

export const pluginUiManifest = (parameters: Parameters<typeof _07477A414>[0], options?: Omit<Parameters<typeof _07477A414>[1], 'throwOnError'>) => getDataOrThrow(_07477A414(parameters, options));

export const propertiesFromType = (parameters: Parameters<typeof _04C6659B3>[0], options?: Omit<Parameters<typeof _04C6659B3>[1], 'throwOnError'>) => getDataOrThrow(_04C6659B3(parameters, options));

export const schemasFromType = (parameters: Parameters<typeof _02D5B2720>[0], options?: Omit<Parameters<typeof _02D5B2720>[1], 'throwOnError'>) => getDataOrThrow(_02D5B2720(parameters, options));

export const listTriggerPlugins = (options?: Omit<Parameters<typeof _03C2494Fa>[0], 'throwOnError'>) => getDataOrThrow(_03C2494Fa(options));

export const pluginDocumentation = (parameters: Parameters<typeof _56210B11>[0], options?: Omit<Parameters<typeof _56210B11>[1], 'throwOnError'>) => getDataOrThrow(_56210B11(parameters, options));

export const pluginVersions = (parameters: Parameters<typeof _402B3Be4>[0], options?: Omit<Parameters<typeof _402B3Be4>[1], 'throwOnError'>) => getDataOrThrow(_402B3Be4(parameters, options));

export const pluginDocumentationFromVersion = (parameters: Parameters<typeof _023E2Be03>[0], options?: Omit<Parameters<typeof _023E2Be03>[1], 'throwOnError'>) => getDataOrThrow(_023E2Be03(parameters, options));

export const pluginUi = (parameters: Parameters<typeof d02B69d>[0], options?: Omit<Parameters<typeof d02B69d>[1], 'throwOnError'>) => getDataOrThrow(d02B69d(parameters, options));
