// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow } from './shared.gen';
import { _036059A58 } from '../sdk.gen';

/**
 * Search for quota limits
 */
export function search(parameters?: Omit<Parameters<typeof _036059A58>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _036059A58>[1], 'throwOnError'>) {
    return getDataOrThrow(_036059A58(addTenantToParameters(parameters), options));
}
