// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow } from './shared.gen';
import { _041B6F32e, _30Dbd29f, _5Db1D8b } from '../sdk.gen';

/**
 * List reusable inputs visible from a namespace (including inherited ones)
 */
export function list(parameters: Omit<Parameters<typeof _041B6F32e>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _041B6F32e>[1], 'throwOnError'>) {
    return getDataOrThrow(_041B6F32e(addTenantToParameters(parameters), options));
}

/**
 * Delete reusable inputs
 */
export function deleteReusableInputs(parameters: Omit<Parameters<typeof _30Dbd29f>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _30Dbd29f>[1], 'throwOnError'>) {
    return getDataOrThrow(_30Dbd29f(addTenantToParameters(parameters), options));
}

/**
 * Get reusable inputs by id, resolving namespace inheritance
 */
export function get(parameters: Omit<Parameters<typeof _5Db1D8b>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _5Db1D8b>[1], 'throwOnError'>) {
    return getDataOrThrow(_5Db1D8b(addTenantToParameters(parameters), options));
}
