// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow } from './shared.gen';
import { _1E2243F8, _37A4Ba84, _678B45A8 } from '../sdk.gen';

/**
 * Create or update reusable inputs from their YAML source
 */
export function createOrUpdate(parameters: Omit<Parameters<typeof _678B45A8>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _678B45A8>[1], 'throwOnError'>) {
    return getDataOrThrow(_678B45A8(addTenantToParameters(parameters), options));
}

/**
 * List all revisions of reusable inputs (history view)
 */
export function revisions(parameters: Omit<Parameters<typeof _1E2243F8>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _1E2243F8>[1], 'throwOnError'>) {
    return getDataOrThrow(_1E2243F8(addTenantToParameters(parameters), options));
}

/**
 * List namespaces that define at least one reusable inputs definition (editor autocompletion)
 */
export function namespacesWithBlocks(parameters?: Omit<Parameters<typeof _37A4Ba84>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _37A4Ba84>[1], 'throwOnError'>) {
    return getDataOrThrow(_37A4Ba84(addTenantToParameters(parameters), options));
}
