// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _011A45F21, _020Dd7E0b, _047B1714, _519Bb792, _58Eb5Fb5, _5C889A24, _692Cacc1 } from '../sdk.gen';
import type { ApiAutocomplete, ApiIds, IamRoleControllerApiRoleCreateOrUpdateRequest } from '../types.gen';

/**
 * Create a role
 */
export function createRole(parameters: IamRoleControllerApiRoleCreateOrUpdateRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _519Bb792>[1], 'throwOnError'>) {
    return getDataOrThrow(_519Bb792({ tenant: resolveTenant(parameters?.tenant), iamRoleControllerApiRoleCreateOrUpdateRequest: parameters }, options));
}

/**
 * List roles for autocomplete
 */
export function autocompleteRoles(parameters: ApiAutocomplete & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _58Eb5Fb5>[1], 'throwOnError'>) {
    return getDataOrThrow(_58Eb5Fb5({ tenant: resolveTenant(parameters?.tenant), apiAutocomplete: parameters }, options));
}

/**
 * List roles by ids
 */
export function listRolesFromGivenIds(parameters: ApiIds & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _5C889A24>[1], 'throwOnError'>) {
    return getDataOrThrow(_5C889A24({ tenant: resolveTenant(parameters?.tenant), apiIds: parameters }, options));
}

/**
 * Search for roles
 */
export function searchRoles(parameters: Omit<Parameters<typeof _020Dd7E0b>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _020Dd7E0b>[1], 'throwOnError'>) {
    return getDataOrThrow(_020Dd7E0b(addTenantToParameters(parameters), options));
}

/**
 * Delete a role
 */
export function deleteRole(parameters: Omit<Parameters<typeof _692Cacc1>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _692Cacc1>[1], 'throwOnError'>) {
    return getDataOrThrow(_692Cacc1(addTenantToParameters(parameters), options));
}

/**
 * Retrieve a role
 */
export function getRole(parameters: Omit<Parameters<typeof _047B1714>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _047B1714>[1], 'throwOnError'>) {
    return getDataOrThrow(_047B1714(addTenantToParameters(parameters), options));
}

/**
 * Update a role
 */
export function updateRole(parameters: Omit<Parameters<typeof _011A45F21>[0], 'iamRoleControllerApiRoleCreateOrUpdateRequest' | 'tenant'> & IamRoleControllerApiRoleCreateOrUpdateRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _011A45F21>[1], 'throwOnError'>) {
    return getDataOrThrow(_011A45F21({
        ...parameters,
        tenant: resolveTenant(parameters?.tenant),
        iamRoleControllerApiRoleCreateOrUpdateRequest: parameters
    }, options));
}
