// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _029Da9A7c, _041E4E0A1, _04Ca27C03, _05Fc1D744, _0E583313, _226Ab45e, c23903c } from '../sdk.gen';
import type { PatchRequest, ScimResource, ScimUser, SearchRequest } from '../types.gen';

export function queryGroups(parameters: Omit<Parameters<typeof _05Fc1D744>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _05Fc1D744>[1], 'throwOnError'>) {
    return getDataOrThrow(_05Fc1D744(addTenantToParameters(parameters), options));
}

export function createSCIMResourceByIdGroups(parameters: Omit<Parameters<typeof _029Da9A7c>[0], 'scimUser' | 'tenant'> & ScimUser & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _029Da9A7c>[1], 'throwOnError'>) {
    return getDataOrThrow(_029Da9A7c({
        ...parameters,
        tenant: resolveTenant(parameters?.tenant),
        scimUser: parameters
    }, options));
}

export function findGroups(parameters: Omit<Parameters<typeof _0E583313>[0], 'searchRequest' | 'tenant'> & SearchRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0E583313>[1], 'throwOnError'>) {
    return getDataOrThrow(_0E583313({
        ...parameters,
        tenant: resolveTenant(parameters?.tenant),
        searchRequest: parameters
    }, options));
}

export function deleteGroups(parameters: Omit<Parameters<typeof _041E4E0A1>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _041E4E0A1>[1], 'throwOnError'>) {
    return getDataOrThrow(_041E4E0A1(addTenantToParameters(parameters), options));
}

export function getSCIMResourceByIdGroups(parameters: Omit<Parameters<typeof _226Ab45e>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _226Ab45e>[1], 'throwOnError'>) {
    return getDataOrThrow(_226Ab45e(addTenantToParameters(parameters), options));
}

export function patchGroups(parameters: Omit<Parameters<typeof c23903c>[0], 'patchRequest' | 'tenant'> & PatchRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof c23903c>[1], 'throwOnError'>) {
    return getDataOrThrow(c23903c({
        ...parameters,
        tenant: resolveTenant(parameters?.tenant),
        patchRequest: parameters
    }, options));
}

export function updateGroups(parameters: Omit<Parameters<typeof _04Ca27C03>[0], 'scimResource' | 'tenant'> & ScimResource & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _04Ca27C03>[1], 'throwOnError'>) {
    return getDataOrThrow(_04Ca27C03({
        ...parameters,
        tenant: resolveTenant(parameters?.tenant),
        scimResource: parameters
    }, options));
}
