// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _022Bb8541, _0436B14E3, _04870C5C2, _0A933De0, _191553Cf, _4B7C6Aa0, _6Ac6Cc58 } from '../sdk.gen';
import type { PatchRequest, ScimResource, ScimUser, SearchRequest } from '../types.gen';

export function queryUsers(parameters: Omit<Parameters<typeof _0A933De0>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0A933De0>[1], 'throwOnError'>) {
    return getDataOrThrow(_0A933De0(addTenantToParameters(parameters), options));
}

export function createSCIMResourceByIdUsers(parameters: Omit<Parameters<typeof _6Ac6Cc58>[0], 'scimUser' | 'tenant'> & ScimUser & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _6Ac6Cc58>[1], 'throwOnError'>) {
    return getDataOrThrow(_6Ac6Cc58({
        ...parameters,
        tenant: resolveTenant(parameters?.tenant),
        scimUser: parameters
    }, options));
}

export function findUsers(parameters: Omit<Parameters<typeof _191553Cf>[0], 'searchRequest' | 'tenant'> & SearchRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _191553Cf>[1], 'throwOnError'>) {
    return getDataOrThrow(_191553Cf({
        ...parameters,
        tenant: resolveTenant(parameters?.tenant),
        searchRequest: parameters
    }, options));
}

export function deleteUsers(parameters: Omit<Parameters<typeof _0436B14E3>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0436B14E3>[1], 'throwOnError'>) {
    return getDataOrThrow(_0436B14E3(addTenantToParameters(parameters), options));
}

export function getSCIMResourceByIdUsers(parameters: Omit<Parameters<typeof _04870C5C2>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _04870C5C2>[1], 'throwOnError'>) {
    return getDataOrThrow(_04870C5C2(addTenantToParameters(parameters), options));
}

export function patchUsers(parameters: Omit<Parameters<typeof _4B7C6Aa0>[0], 'patchRequest' | 'tenant'> & PatchRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _4B7C6Aa0>[1], 'throwOnError'>) {
    return getDataOrThrow(_4B7C6Aa0({
        ...parameters,
        tenant: resolveTenant(parameters?.tenant),
        patchRequest: parameters
    }, options));
}

export function updateUsers(parameters: Omit<Parameters<typeof _022Bb8541>[0], 'scimResource' | 'tenant'> & ScimResource & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _022Bb8541>[1], 'throwOnError'>) {
    return getDataOrThrow(_022Bb8541({
        ...parameters,
        tenant: resolveTenant(parameters?.tenant),
        scimResource: parameters
    }, options));
}
