// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow } from './shared.gen';
import { _0445677A0, _04Bd94Eba, _04C8F91F9, _2Ef85897, _4A09A2De } from '../sdk.gen';

export function getAllResourceTypes(parameters: Omit<Parameters<typeof _0445677A0>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0445677A0>[1], 'throwOnError'>) {
    return getDataOrThrow(_0445677A0(addTenantToParameters(parameters), options));
}

export function getResourceType(parameters: Omit<Parameters<typeof _4A09A2De>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _4A09A2De>[1], 'throwOnError'>) {
    return getDataOrThrow(_4A09A2De(addTenantToParameters(parameters), options));
}

export function getAllSchemas(parameters: Omit<Parameters<typeof _04C8F91F9>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _04C8F91F9>[1], 'throwOnError'>) {
    return getDataOrThrow(_04C8F91F9(addTenantToParameters(parameters), options));
}

export function getSchema(parameters: Omit<Parameters<typeof _2Ef85897>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _2Ef85897>[1], 'throwOnError'>) {
    return getDataOrThrow(_2Ef85897(addTenantToParameters(parameters), options));
}

export function getServiceProviderConfiguration(parameters: Omit<Parameters<typeof _04Bd94Eba>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _04Bd94Eba>[1], 'throwOnError'>) {
    return getDataOrThrow(_04Bd94Eba(addTenantToParameters(parameters), options));
}
