// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _0391165C3, _0670384C2, _12D3F2C9, _3945Cbd8, _454A6c, _4A97D3F1, _570E8Fac } from '../sdk.gen';
import type { CreateSecurityIntegrationRequest } from '../types.gen';

/**
 * List all security integrations
 */
export function listSecurityIntegrations(parameters?: Omit<Parameters<typeof _0391165C3>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0391165C3>[1], 'throwOnError'>) {
    return getDataOrThrow(_0391165C3(addTenantToParameters(parameters), options));
}

/**
 * Create a security integration
 */
export function createSecurityIntegration(parameters: CreateSecurityIntegrationRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _3945Cbd8>[1], 'throwOnError'>) {
    return getDataOrThrow(_3945Cbd8({ tenant: resolveTenant(parameters?.tenant), createSecurityIntegrationRequest: parameters }, options));
}

/**
 * Retrieve security integrations filtered by Filters
 */
export function searchSecurityIntegration(parameters: Omit<Parameters<typeof _570E8Fac>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _570E8Fac>[1], 'throwOnError'>) {
    return getDataOrThrow(_570E8Fac(addTenantToParameters(parameters), options));
}

/**
 * Delete a security integration
 */
export function deleteSecurityIntegration(parameters: Omit<Parameters<typeof _12D3F2C9>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _12D3F2C9>[1], 'throwOnError'>) {
    return getDataOrThrow(_12D3F2C9(addTenantToParameters(parameters), options));
}

/**
 * Retrieve a security integration
 */
export function getSecurityIntegration(parameters: Omit<Parameters<typeof _0670384C2>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0670384C2>[1], 'throwOnError'>) {
    return getDataOrThrow(_0670384C2(addTenantToParameters(parameters), options));
}

/**
 * Disable a security integration
 */
export function disableSecurityIntegration(parameters: Omit<Parameters<typeof _454A6c>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _454A6c>[1], 'throwOnError'>) {
    return getDataOrThrow(_454A6c(addTenantToParameters(parameters), options));
}

/**
 * Enable a security integration
 */
export function enableSecurityIntegration(parameters: Omit<Parameters<typeof _4A97D3F1>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _4A97D3F1>[1], 'throwOnError'>) {
    return getDataOrThrow(_4A97D3F1(addTenantToParameters(parameters), options));
}
