// This file is auto-generated by @hey-api/openapi-ts

import { getDataOrThrow } from './shared.gen';
import { _02D424Dda, _0427Da586, _04Beefd81, _38F8C0C3 } from '../sdk.gen';

export function metrics(parameters: Parameters<typeof _38F8C0C3>[0], options?: Omit<Parameters<typeof _38F8C0C3>[1], 'throwOnError'>) {
    return getDataOrThrow(_38F8C0C3(parameters, options));
}

export function getActiveServices(options?: Omit<Parameters<typeof _0427Da586>[0], 'throwOnError'>) {
    return getDataOrThrow(_0427Da586(options));
}

export function searchServices(parameters: Parameters<typeof _02D424Dda>[0], options?: Omit<Parameters<typeof _02D424Dda>[1], 'throwOnError'>) {
    return getDataOrThrow(_02D424Dda(parameters, options));
}

export function getService(parameters: Parameters<typeof _04Beefd81>[0], options?: Omit<Parameters<typeof _04Beefd81>[1], 'throwOnError'>) {
    return getDataOrThrow(_04Beefd81(parameters, options));
}
