// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow } from './shared.gen';
import { _04Beefd81, _38F8C0C3 } from '../sdk.gen';

/**
 * Get metrics for running services
 */
export const metrics = (parameters: Omit<Parameters<typeof _38F8C0C3>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _38F8C0C3>[1], 'throwOnError'>) => getDataOrThrow(_38F8C0C3(addTenantToParameters(parameters), options));

/**
 * Get details about a service
 */
export const service = (parameters: Omit<Parameters<typeof _04Beefd81>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _04Beefd81>[1], 'throwOnError'>) => getDataOrThrow(_04Beefd81(addTenantToParameters(parameters), options));
