// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _010043Fd5, _020E2391f, _02Dfdba59, _038D53E30, _0434216C9, _0465C8F2c, _0A5Ca62c, _0B990465, _27B78202, _2Eea22Ae, _3026D709, _3Fdb7B5f, _4043C216, _64A9593d, _7C4007C5, _8194F9, e42E043 } from '../sdk.gen';
import type { ApiPatchSuperAdminRequest, CreateApiTokenRequest, IamServiceAccountControllerApiCreateServiceAccountRequest, IamServiceAccountControllerApiPatchServiceAccountRequest, IamServiceAccountControllerApiServiceAccountRequest } from '../types.gen';

export function listServiceAccounts(parameters: Parameters<typeof _64A9593d>[0], options?: Omit<Parameters<typeof _64A9593d>[1], 'throwOnError'>) {
    return getDataOrThrow(_64A9593d(parameters, options));
}

/**
 * Create a service account
 */
export function createServiceAccount(parameters: IamServiceAccountControllerApiCreateServiceAccountRequest, options?: Omit<Parameters<typeof _0A5Ca62c>[1], 'throwOnError'>) {
    return getDataOrThrow(_0A5Ca62c({ iamServiceAccountControllerApiCreateServiceAccountRequest: parameters }, options));
}

export function deleteServiceAccount(parameters: Parameters<typeof e42E043>[0], options?: Omit<Parameters<typeof e42E043>[1], 'throwOnError'>) {
    return getDataOrThrow(e42E043(parameters, options));
}

export function getServiceAccount(parameters: Parameters<typeof _2Eea22Ae>[0], options?: Omit<Parameters<typeof _2Eea22Ae>[1], 'throwOnError'>) {
    return getDataOrThrow(_2Eea22Ae(parameters, options));
}

/**
 * Update service account details
 */
export function patchServiceAccountDetails(parameters: Omit<Parameters<typeof _27B78202>[0], 'iamServiceAccountControllerApiPatchServiceAccountRequest'> & IamServiceAccountControllerApiPatchServiceAccountRequest, options?: Omit<Parameters<typeof _27B78202>[1], 'throwOnError'>) {
    return getDataOrThrow(_27B78202({ ...parameters, iamServiceAccountControllerApiPatchServiceAccountRequest: parameters }, options));
}

export function listApiTokensForServiceAccount(parameters: Parameters<typeof _010043Fd5>[0], options?: Omit<Parameters<typeof _010043Fd5>[1], 'throwOnError'>) {
    return getDataOrThrow(_010043Fd5(parameters, options));
}

/**
 * Create new API Token for a specific service account
 */
export function createApiTokensForServiceAccount(parameters: Omit<Parameters<typeof _3026D709>[0], 'createApiTokenRequest'> & CreateApiTokenRequest, options?: Omit<Parameters<typeof _3026D709>[1], 'throwOnError'>) {
    return getDataOrThrow(_3026D709({ ...parameters, createApiTokenRequest: parameters }, options));
}

export function deleteApiTokenForServiceAccount(parameters: Parameters<typeof _0434216C9>[0], options?: Omit<Parameters<typeof _0434216C9>[1], 'throwOnError'>) {
    return getDataOrThrow(_0434216C9(parameters, options));
}

/**
 * Update service account superadmin privileges
 */
export function patchServiceAccountSuperAdmin(parameters: Omit<Parameters<typeof _0465C8F2c>[0], 'apiPatchSuperAdminRequest'> & ApiPatchSuperAdminRequest, options?: Omit<Parameters<typeof _0465C8F2c>[1], 'throwOnError'>) {
    return getDataOrThrow(_0465C8F2c({ ...parameters, apiPatchSuperAdminRequest: parameters }, options));
}

/**
 * List service accounts for the given tenant
 */
export function listServiceAccountsForTenant(parameters: Omit<Parameters<typeof _4043C216>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _4043C216>[1], 'throwOnError'>) {
    return getDataOrThrow(_4043C216(addTenantToParameters(parameters), options));
}

/**
 * Create a service account for the given tenant
 */
export function createServiceAccountForTenant(parameters: IamServiceAccountControllerApiServiceAccountRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _3Fdb7B5f>[1], 'throwOnError'>) {
    return getDataOrThrow(_3Fdb7B5f({ tenant: resolveTenant(parameters?.tenant), iamServiceAccountControllerApiServiceAccountRequest: parameters }, options));
}

/**
 * Delete a service account
 */
export function deleteServiceAccountForTenant(parameters: Omit<Parameters<typeof _038D53E30>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _038D53E30>[1], 'throwOnError'>) {
    return getDataOrThrow(_038D53E30(addTenantToParameters(parameters), options));
}

/**
 * Retrieve a service account
 */
export function getServiceAccountForTenant(parameters: Omit<Parameters<typeof _7C4007C5>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _7C4007C5>[1], 'throwOnError'>) {
    return getDataOrThrow(_7C4007C5(addTenantToParameters(parameters), options));
}

/**
 * Update a user service account
 */
export function updateServiceAccount(parameters: Omit<Parameters<typeof _020E2391f>[0], 'iamServiceAccountControllerApiServiceAccountRequest' | 'tenant'> & IamServiceAccountControllerApiServiceAccountRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _020E2391f>[1], 'throwOnError'>) {
    return getDataOrThrow(_020E2391f({
        ...parameters,
        tenant: resolveTenant(parameters?.tenant),
        iamServiceAccountControllerApiServiceAccountRequest: parameters
    }, options));
}

/**
 * List API tokens for a specific service account
 */
export function listApiTokensForServiceAccountWithTenant(parameters: Omit<Parameters<typeof _0B990465>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0B990465>[1], 'throwOnError'>) {
    return getDataOrThrow(_0B990465(addTenantToParameters(parameters), options));
}

/**
 * Create new API Token for a specific service account
 */
export function createApiTokensForServiceAccountWithTenant(parameters: Omit<Parameters<typeof _8194F9>[0], 'createApiTokenRequest' | 'tenant'> & CreateApiTokenRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _8194F9>[1], 'throwOnError'>) {
    return getDataOrThrow(_8194F9({
        ...parameters,
        tenant: resolveTenant(parameters?.tenant),
        createApiTokenRequest: parameters
    }, options));
}

/**
 * Delete an API Token for specific service account and token id
 */
export function deleteApiTokenForServiceAccountWithTenant(parameters: Omit<Parameters<typeof _02Dfdba59>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _02Dfdba59>[1], 'throwOnError'>) {
    return getDataOrThrow(_02Dfdba59(addTenantToParameters(parameters), options));
}
