// This file is auto-generated by @hey-api/openapi-ts

let globalTenant = 'main';

export function setSelectedTenant(newTenant: string) {
    globalTenant = newTenant;
}

export function addTenantToParameters<TParams>(parameters: TParams): TParams & {
    tenant: string;
} {
    return ({ tenant: globalTenant, ...parameters });
}

export function resolveTenant(tenant?: string): string {
    return tenant ?? globalTenant;
}

export async function getDataOrThrow<T, E>(respPromise: Promise<{
    data: T;
    error?: undefined;
} | {
    data?: unknown;
    error: E;
}>): Promise<T> {
    const resp = await respPromise;
    if ("error" in resp) {
        throw resp.error;
    }
    return resp.data;
}
