// This file is auto-generated by @hey-api/openapi-ts

export const OPENAPI_SPEC_HASH = '962a3ed73ea4d1d3';

let globalTenant = 'main';

export const setSelectedTenant = (newTenant: string) => {
    globalTenant = newTenant;
};

export const addTenantToParameters = <TParams>(parameters: TParams): TParams & {
    tenant: string;
} => ({ tenant: globalTenant, ...parameters });

export const resolveTenant = (tenant?: string): string => tenant ?? globalTenant;

export const getDataOrThrow = async <T, E>(respPromise: Promise<{
    data: T;
    error?: undefined;
} | {
    data?: unknown;
    error: E;
}>): Promise<T> => {
    const resp = await respPromise;
    if ("error" in resp) {
        throw resp.error;
    }
    return resp.data;
};
