// This file is auto-generated by @hey-api/openapi-ts

import { getDataOrThrow } from './shared.gen';
import { _30Dbd29e, _4Ed5363c, _5Db1D8a, _6C815Daf } from '../sdk.gen';
import type { Tenant } from '../types.gen';

/**
 * Create a tenant
 */
export function create(parameters: Tenant, options?: Omit<Parameters<typeof _6C815Daf>[1], 'throwOnError'>) {
    return getDataOrThrow(_6C815Daf({ tenant: parameters }, options));
}

export function deleteTenants(parameters: Parameters<typeof _30Dbd29e>[0], options?: Omit<Parameters<typeof _30Dbd29e>[1], 'throwOnError'>) {
    return getDataOrThrow(_30Dbd29e(parameters, options));
}

export function get(parameters: Parameters<typeof _5Db1D8a>[0], options?: Omit<Parameters<typeof _5Db1D8a>[1], 'throwOnError'>) {
    return getDataOrThrow(_5Db1D8a(parameters, options));
}

/**
 * Update a tenant
 */
export function update(parameters: Omit<Parameters<typeof _4Ed5363c>[0], 'tenant'> & Tenant, options?: Omit<Parameters<typeof _4Ed5363c>[1], 'throwOnError'>) {
    return getDataOrThrow(_4Ed5363c({ ...parameters, tenant: parameters }, options));
}
