// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _0196Dc236, _02F368Adc, _24Ee93F9, _82Aea6c } from '../sdk.gen';
import type { IamTenantAccessControllerApiCreateTenantAccessRequest } from '../types.gen';

/**
 * Retrieve users belonging to the tenant
 */
export function listTenantAccess(parameters: Omit<Parameters<typeof _82Aea6c>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _82Aea6c>[1], 'throwOnError'>) {
    return getDataOrThrow(_82Aea6c(addTenantToParameters(parameters), options));
}

/**
 * Create tenant access for a user
 */
export function createTenantAccess(parameters: IamTenantAccessControllerApiCreateTenantAccessRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0196Dc236>[1], 'throwOnError'>) {
    return getDataOrThrow(_0196Dc236({ tenant: resolveTenant(parameters?.tenant), iamTenantAccessControllerApiCreateTenantAccessRequest: parameters }, options));
}

/**
 * Delete tenant access for a user
 */
export function deleteTenantAccess(parameters: Omit<Parameters<typeof _24Ee93F9>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _24Ee93F9>[1], 'throwOnError'>) {
    return getDataOrThrow(_24Ee93F9(addTenantToParameters(parameters), options));
}

/**
 * Retrieve tenant access for a user
 */
export function getTenantAccess(parameters: Omit<Parameters<typeof _02F368Adc>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _02F368Adc>[1], 'throwOnError'>) {
    return getDataOrThrow(_02F368Adc(addTenantToParameters(parameters), options));
}
