// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow } from './shared.gen';
import { _075060104 } from '../sdk.gen';

/**
 * Create tenant access for a user
 */
export function createTenantAccess(parameters: Omit<Parameters<typeof _075060104>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _075060104>[1], 'throwOnError'>) {
    return getDataOrThrow(_075060104(addTenantToParameters(parameters), options));
}
