// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow } from './shared.gen';
import { _0121E6D30, _0139064D9, _02A557B36, _03D361199, _05Bfd34Cc, _10D98Eb3, _2Ff5B9, _754Ac1C1, _764Cf52d } from '../sdk.gen';
import type { TenantControllerAppsCatalogConfigRequest, TenantControllerSetTenantDefaultDashboardsRequest } from '../types.gen';

export function find(parameters?: Parameters<typeof _2Ff5B9>[0], options?: Omit<Parameters<typeof _2Ff5B9>[1], 'throwOnError'>) {
    return getDataOrThrow(_2Ff5B9(parameters, options));
}

export function getAppsCatalogConfig(parameters: Parameters<typeof _10D98Eb3>[0], options?: Omit<Parameters<typeof _10D98Eb3>[1], 'throwOnError'>) {
    return getDataOrThrow(_10D98Eb3(parameters, options));
}

/**
 * Set the apps catalog config for the specified tenant.
 */
export function setAppsCatalogConfig(parameters: Omit<Parameters<typeof _0139064D9>[0], 'tenantControllerAppsCatalogConfigRequest'> & TenantControllerAppsCatalogConfigRequest, options?: Omit<Parameters<typeof _0139064D9>[1], 'throwOnError'>) {
    return getDataOrThrow(_0139064D9({ ...parameters, tenantControllerAppsCatalogConfigRequest: parameters }, options));
}

export function deleteAppsCatalogLogo(parameters: Parameters<typeof _03D361199>[0], options?: Omit<Parameters<typeof _03D361199>[1], 'throwOnError'>) {
    return getDataOrThrow(_03D361199(parameters, options));
}

/**
 * Set the apps catalog logo for the specified tenant.
 */
export function setAppsCatalogLogo(parameters: Parameters<typeof _0121E6D30>[0], options?: Omit<Parameters<typeof _0121E6D30>[1], 'throwOnError'>) {
    return getDataOrThrow(_0121E6D30(parameters, options));
}

/**
 * Set a tenant logo
 */
export function setLogo(parameters: Parameters<typeof _764Cf52d>[0], options?: Omit<Parameters<typeof _764Cf52d>[1], 'throwOnError'>) {
    return getDataOrThrow(_764Cf52d(parameters, options));
}

export function getDefaultDashboards(parameters: Parameters<typeof _02A557B36>[0], options?: Omit<Parameters<typeof _02A557B36>[1], 'throwOnError'>) {
    return getDataOrThrow(_02A557B36(parameters, options));
}

/**
 * Update default dashboards for the entire tenant
 */
export function setTenantDefaultDashboards(parameters: Omit<Parameters<typeof _05Bfd34Cc>[0], 'tenantControllerSetTenantDefaultDashboardsRequest'> & TenantControllerSetTenantDefaultDashboardsRequest, options?: Omit<Parameters<typeof _05Bfd34Cc>[1], 'throwOnError'>) {
    return getDataOrThrow(_05Bfd34Cc({ ...parameters, tenantControllerSetTenantDefaultDashboardsRequest: parameters }, options));
}

/**
 * Get tenant dependencies
 */
export function getFlowDependenciesFromTenant(parameters?: Omit<Parameters<typeof _754Ac1C1>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _754Ac1C1>[1], 'throwOnError'>) {
    return getDataOrThrow(_754Ac1C1(addTenantToParameters(parameters), options));
}
