// This file is auto-generated by @hey-api/openapi-ts

import { getDataOrThrow } from './shared.gen';
import { _02F7A6E1 } from '../sdk.gen';
import type { TenantControllerSetTenantDefaultDashboardsRequest } from '../types.gen';

/**
 * Make this dashboard the default for the entire tenant
 */
export const setTenantDefaultDashboard = (parameters: TenantControllerSetTenantDefaultDashboardsRequest, options?: Omit<Parameters<typeof _02F7A6E1>[1], 'throwOnError'>) => getDataOrThrow(_02F7A6E1({ tenantControllerSetTenantDefaultDashboardsRequest: parameters }, options));
