// This file is auto-generated by @hey-api/openapi-ts

import { addTenantToParameters, getDataOrThrow, resolveTenant } from './shared.gen';
import { _018132C8b, _0186007E5, _025Da49F7, _047926130, _0591Da8D4, _05E5Dc0C5, _244E051e, _361Cef9, _4D1D22C1, _51A50D10, _52B47B45, _61Ac07Ea, _62186B31, dae6Bd } from '../sdk.gen';
import type { TestSuiteControllerRunRequest, TestSuiteControllerSearchTestsLastResult, TestSuiteControllerTestSuiteBulkRequest, TestSuiteServiceRunByQueryRequest } from '../types.gen';

/**
 * Create a test from YAML source
 */
export function createTestSuite(parameters: Omit<Parameters<typeof _61Ac07Ea>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _61Ac07Ea>[1], 'throwOnError'>) {
    return getDataOrThrow(_61Ac07Ea(addTenantToParameters(parameters), options));
}

/**
 * Delete multiple tests by id
 */
export function deleteTestSuitesByIds(parameters: TestSuiteControllerTestSuiteBulkRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _025Da49F7>[1], 'throwOnError'>) {
    return getDataOrThrow(_025Da49F7({ tenant: resolveTenant(parameters?.tenant), testSuiteControllerTestSuiteBulkRequest: parameters }, options));
}

/**
 * Disable multiple tests by id
 */
export function disableTestSuitesByIds(parameters: TestSuiteControllerTestSuiteBulkRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0591Da8D4>[1], 'throwOnError'>) {
    return getDataOrThrow(_0591Da8D4({ tenant: resolveTenant(parameters?.tenant), testSuiteControllerTestSuiteBulkRequest: parameters }, options));
}

/**
 * Enable multiple tests by id
 */
export function enableTestSuitesByIds(parameters: TestSuiteControllerTestSuiteBulkRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _62186B31>[1], 'throwOnError'>) {
    return getDataOrThrow(_62186B31({ tenant: resolveTenant(parameters?.tenant), testSuiteControllerTestSuiteBulkRequest: parameters }, options));
}

/**
 * Search for tests results
 */
export function searchTestSuitesResults(parameters?: Omit<Parameters<typeof _4D1D22C1>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _4D1D22C1>[1], 'throwOnError'>) {
    return getDataOrThrow(_4D1D22C1(addTenantToParameters(parameters), options));
}

/**
 * Get tests last result
 */
export function getTestsLastResult(parameters: TestSuiteControllerSearchTestsLastResult & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _244E051e>[1], 'throwOnError'>) {
    return getDataOrThrow(_244E051e({ tenant: resolveTenant(parameters?.tenant), testSuiteControllerSearchTestsLastResult: parameters }, options));
}

/**
 * Get a test result
 */
export function getTestResult(parameters: Omit<Parameters<typeof _52B47B45>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _52B47B45>[1], 'throwOnError'>) {
    return getDataOrThrow(_52B47B45(addTenantToParameters(parameters), options));
}

/**
 * Run multiple TestSuites by query
 */
export function runTestSuitesByQuery(parameters: TestSuiteServiceRunByQueryRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _361Cef9>[1], 'throwOnError'>) {
    return getDataOrThrow(_361Cef9({ tenant: resolveTenant(parameters?.tenant), testSuiteServiceRunByQueryRequest: parameters }, options));
}

/**
 * Search for tests
 */
export function searchTestSuites(parameters?: Omit<Parameters<typeof _018132C8b>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _018132C8b>[1], 'throwOnError'>) {
    return getDataOrThrow(_018132C8b(addTenantToParameters(parameters), options));
}

/**
 * Validate a test
 */
export function validateTestSuite(parameters: Omit<Parameters<typeof _51A50D10>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _51A50D10>[1], 'throwOnError'>) {
    return getDataOrThrow(_51A50D10(addTenantToParameters(parameters), options));
}

/**
 * Delete a test
 */
export function deleteTestSuite(parameters: Omit<Parameters<typeof _0186007E5>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _0186007E5>[1], 'throwOnError'>) {
    return getDataOrThrow(_0186007E5(addTenantToParameters(parameters), options));
}

/**
 * Retrieve a test
 */
export function getTestSuite(parameters: Omit<Parameters<typeof _047926130>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _047926130>[1], 'throwOnError'>) {
    return getDataOrThrow(_047926130(addTenantToParameters(parameters), options));
}

/**
 * Update a test from YAML source
 */
export function updateTestSuite(parameters: Omit<Parameters<typeof dae6Bd>[0], 'tenant'> & {
    tenant?: string;
}, options?: Omit<Parameters<typeof dae6Bd>[1], 'throwOnError'>) {
    return getDataOrThrow(dae6Bd(addTenantToParameters(parameters), options));
}

/**
 * Run a full test
 */
export function runTestSuite(parameters: Omit<Parameters<typeof _05E5Dc0C5>[0], 'testSuiteControllerRunRequest' | 'tenant'> & TestSuiteControllerRunRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _05E5Dc0C5>[1], 'throwOnError'>) {
    return getDataOrThrow(_05E5Dc0C5({
        ...parameters,
        tenant: resolveTenant(parameters?.tenant),
        testSuiteControllerRunRequest: parameters
    }, options));
}
