// This file is auto-generated by @hey-api/openapi-ts

import { getDataOrThrow, resolveTenant } from './shared.gen';
import { _011A2F3Cc, _01E98E3Cd, _01Eb351A4, _023524D8, _0236Ea812, _0479Abbf, _049835Ff6, _04E4686D7, _0865C602, _2Dbe020a, _47Ed1E79, _487Ead27, _519D22E7, _59175F00, _63683Cb6, _66Bf0D5f, _692E1816, _789F9416 } from '../sdk.gen';
import type { ApiPatchSuperAdminRequest, CreateApiTokenRequest, IamTenantAccessControllerUserApiAutocomplete, IamUserControllerApiCreateOrUpdateUserRequest, IamUserControllerApiPatchRestrictedRequest, IamUserControllerApiPatchUserPasswordRequest, IamUserGroupControllerApiUpdateUserGroupsRequest, MeControllerApiUpdatePasswordRequest, MeControllerApiUserDetailsRequest } from '../types.gen';

/**
 * Update authenticated user password
 */
export function updateCurrentUserPassword(parameters: MeControllerApiUpdatePasswordRequest, options?: Omit<Parameters<typeof _789F9416>[1], 'throwOnError'>) {
    return getDataOrThrow(_789F9416({ meControllerApiUpdatePasswordRequest: parameters }, options));
}

export function listUsers(parameters: Parameters<typeof _049835Ff6>[0], options?: Omit<Parameters<typeof _049835Ff6>[1], 'throwOnError'>) {
    return getDataOrThrow(_049835Ff6(parameters, options));
}

/**
 * Create a new user account
 */
export function createUser(parameters: IamUserControllerApiCreateOrUpdateUserRequest, options?: Omit<Parameters<typeof _519D22E7>[1], 'throwOnError'>) {
    return getDataOrThrow(_519D22E7({ iamUserControllerApiCreateOrUpdateUserRequest: parameters }, options));
}

export function deleteUser(parameters: Parameters<typeof _692E1816>[0], options?: Omit<Parameters<typeof _692E1816>[1], 'throwOnError'>) {
    return getDataOrThrow(_692E1816(parameters, options));
}

export function getUser(parameters: Parameters<typeof _0479Abbf>[0], options?: Omit<Parameters<typeof _0479Abbf>[1], 'throwOnError'>) {
    return getDataOrThrow(_0479Abbf(parameters, options));
}

/**
 * Update user details
 */
export function patchUser(parameters: Omit<Parameters<typeof _01E98E3Cd>[0], 'meControllerApiUserDetailsRequest'> & MeControllerApiUserDetailsRequest, options?: Omit<Parameters<typeof _01E98E3Cd>[1], 'throwOnError'>) {
    return getDataOrThrow(_01E98E3Cd({ ...parameters, meControllerApiUserDetailsRequest: parameters }, options));
}

/**
 * Update a user account
 */
export function updateUser(parameters: Omit<Parameters<typeof _011A2F3Cc>[0], 'iamUserControllerApiCreateOrUpdateUserRequest'> & IamUserControllerApiCreateOrUpdateUserRequest, options?: Omit<Parameters<typeof _011A2F3Cc>[1], 'throwOnError'>) {
    return getDataOrThrow(_011A2F3Cc({ ...parameters, iamUserControllerApiCreateOrUpdateUserRequest: parameters }, options));
}

export function listApiTokensForUser(parameters: Parameters<typeof _0865C602>[0], options?: Omit<Parameters<typeof _0865C602>[1], 'throwOnError'>) {
    return getDataOrThrow(_0865C602(parameters, options));
}

/**
 * Create new API Token for a specific user
 */
export function createApiTokensForUser(parameters: Omit<Parameters<typeof _01Eb351A4>[0], 'createApiTokenRequest'> & CreateApiTokenRequest, options?: Omit<Parameters<typeof _01Eb351A4>[1], 'throwOnError'>) {
    return getDataOrThrow(_01Eb351A4({ ...parameters, createApiTokenRequest: parameters }, options));
}

export function deleteApiTokenForUser(parameters: Parameters<typeof _2Dbe020a>[0], options?: Omit<Parameters<typeof _2Dbe020a>[1], 'throwOnError'>) {
    return getDataOrThrow(_2Dbe020a(parameters, options));
}

export function deleteUserAuthMethod(parameters: Parameters<typeof _66Bf0D5f>[0], options?: Omit<Parameters<typeof _66Bf0D5f>[1], 'throwOnError'>) {
    return getDataOrThrow(_66Bf0D5f(parameters, options));
}

export function impersonate(parameters: Parameters<typeof _47Ed1E79>[0], options?: Omit<Parameters<typeof _47Ed1E79>[1], 'throwOnError'>) {
    return getDataOrThrow(_47Ed1E79(parameters, options));
}

/**
 * Update user password
 */
export function patchUserPassword(parameters: Omit<Parameters<typeof _0236Ea812>[0], 'iamUserControllerApiPatchUserPasswordRequest'> & IamUserControllerApiPatchUserPasswordRequest, options?: Omit<Parameters<typeof _0236Ea812>[1], 'throwOnError'>) {
    return getDataOrThrow(_0236Ea812({ ...parameters, iamUserControllerApiPatchUserPasswordRequest: parameters }, options));
}

export function deleteRefreshToken(parameters: Parameters<typeof _04E4686D7>[0], options?: Omit<Parameters<typeof _04E4686D7>[1], 'throwOnError'>) {
    return getDataOrThrow(_04E4686D7(parameters, options));
}

/**
 * Update user demo
 */
export function patchUserDemo(parameters: Omit<Parameters<typeof _63683Cb6>[0], 'iamUserControllerApiPatchRestrictedRequest'> & IamUserControllerApiPatchRestrictedRequest, options?: Omit<Parameters<typeof _63683Cb6>[1], 'throwOnError'>) {
    return getDataOrThrow(_63683Cb6({ ...parameters, iamUserControllerApiPatchRestrictedRequest: parameters }, options));
}

/**
 * Update user superadmin privileges
 */
export function patchUserSuperAdmin(parameters: Omit<Parameters<typeof _487Ead27>[0], 'apiPatchSuperAdminRequest'> & ApiPatchSuperAdminRequest, options?: Omit<Parameters<typeof _487Ead27>[1], 'throwOnError'>) {
    return getDataOrThrow(_487Ead27({ ...parameters, apiPatchSuperAdminRequest: parameters }, options));
}

/**
 * List users for autocomplete
 */
export function autocompleteUsers(parameters: IamTenantAccessControllerUserApiAutocomplete & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _59175F00>[1], 'throwOnError'>) {
    return getDataOrThrow(_59175F00({ tenant: resolveTenant(parameters?.tenant), iamTenantAccessControllerUserApiAutocomplete: parameters }, options));
}

/**
 * Update the list of groups a user belongs to for the given tenant
 */
export function updateUserGroups(parameters: Omit<Parameters<typeof _023524D8>[0], 'iamUserGroupControllerApiUpdateUserGroupsRequest' | 'tenant'> & IamUserGroupControllerApiUpdateUserGroupsRequest & {
    tenant?: string;
}, options?: Omit<Parameters<typeof _023524D8>[1], 'throwOnError'>) {
    return getDataOrThrow(_023524D8({
        ...parameters,
        tenant: resolveTenant(parameters?.tenant),
        iamUserGroupControllerApiUpdateUserGroupsRequest: parameters
    }, options));
}
