// This file is auto-generated by @hey-api/openapi-ts

import { getDataOrThrow } from './shared.gen';
import { _041B6F32f, _5Db1D89 } from '../sdk.gen';

export function list(options?: Omit<Parameters<typeof _041B6F32f>[0], 'throwOnError'>) {
    return getDataOrThrow(_041B6F32f(options));
}

export function get(parameters: Parameters<typeof _5Db1D89>[0], options?: Omit<Parameters<typeof _5Db1D89>[1], 'throwOnError'>) {
    return getDataOrThrow(_5Db1D89(parameters, options));
}
