// This file is auto-generated by @hey-api/openapi-ts

import { getDataOrThrow } from './shared.gen';
import { _322Dc10b } from '../sdk.gen';

export function subscribers(parameters: Parameters<typeof _322Dc10b>[0], options?: Omit<Parameters<typeof _322Dc10b>[1], 'throwOnError'>) {
    return getDataOrThrow(_322Dc10b(parameters, options));
}
