// This file is auto-generated by @hey-api/openapi-ts

import { getDataOrThrow } from './shared.gen';
import { _037B0F17a } from '../sdk.gen';

export function revoke(parameters: Parameters<typeof _037B0F17a>[0], options?: Omit<Parameters<typeof _037B0F17a>[1], 'throwOnError'>) {
    return getDataOrThrow(_037B0F17a(parameters, options));
}
