// This file is auto-generated by @hey-api/openapi-ts

import { getDataOrThrow } from './shared.gen';
import { _041B6F330, _30Dbd29d, _4Ed5363b, _5Db1D88, _6C815Dae } from '../sdk.gen';
import type { WorkerQueueControllerApiCreateOrUpdateWorkerQueueRequest } from '../types.gen';

export function list(options?: Omit<Parameters<typeof _041B6F330>[0], 'throwOnError'>) {
    return getDataOrThrow(_041B6F330(options));
}

/**
 * Create a Worker Queue
 */
export function create(parameters: WorkerQueueControllerApiCreateOrUpdateWorkerQueueRequest, options?: Omit<Parameters<typeof _6C815Dae>[1], 'throwOnError'>) {
    return getDataOrThrow(_6C815Dae({ workerQueueControllerApiCreateOrUpdateWorkerQueueRequest: parameters }, options));
}

export function deleteWorkerQueues(parameters: Parameters<typeof _30Dbd29d>[0], options?: Omit<Parameters<typeof _30Dbd29d>[1], 'throwOnError'>) {
    return getDataOrThrow(_30Dbd29d(parameters, options));
}

export function get(parameters: Parameters<typeof _5Db1D88>[0], options?: Omit<Parameters<typeof _5Db1D88>[1], 'throwOnError'>) {
    return getDataOrThrow(_5Db1D88(parameters, options));
}

/**
 * Update a Worker Queue
 */
export function update(parameters: Omit<Parameters<typeof _4Ed5363b>[0], 'workerQueueControllerApiCreateOrUpdateWorkerQueueRequest'> & WorkerQueueControllerApiCreateOrUpdateWorkerQueueRequest, options?: Omit<Parameters<typeof _4Ed5363b>[1], 'throwOnError'>) {
    return getDataOrThrow(_4Ed5363b({ ...parameters, workerQueueControllerApiCreateOrUpdateWorkerQueueRequest: parameters }, options));
}
