// This file is auto-generated by @hey-api/openapi-ts

import { getDataOrThrow } from './shared.gen';
import { _0219920Ed, _031Ffc737, _0437Ae8F2, _04Eb8003f, _04F997A55, _0509A5F04, _06Fe9C3A2, _18F56, _20D7B66, _23F18A34, _32B09e, _6757D584, _77Cf5230 } from '../sdk.gen';
import type { WorkerGroupControllerApiCreateWorkerGroupRequest, WorkerGroupControllerApiGenerateTokenRequest, WorkerGroupControllerApiSubscriptionRequest, WorkerGroupControllerApiUpdateSubscriptionRequest, WorkerGroupControllerApiUpdateWorkerGroupRequest } from '../types.gen';

export function list(parameters?: Parameters<typeof _32B09e>[0], options?: Omit<Parameters<typeof _32B09e>[1], 'throwOnError'>) {
    return getDataOrThrow(_32B09e(parameters, options));
}

/**
 * Create a worker group
 */
export function create(parameters: WorkerGroupControllerApiCreateWorkerGroupRequest, options?: Omit<Parameters<typeof _0509A5F04>[1], 'throwOnError'>) {
    return getDataOrThrow(_0509A5F04({ workerGroupControllerApiCreateWorkerGroupRequest: parameters }, options));
}

export function deleteWorkerGroups(parameters: Parameters<typeof _04F997A55>[0], options?: Omit<Parameters<typeof _04F997A55>[1], 'throwOnError'>) {
    return getDataOrThrow(_04F997A55(parameters, options));
}

export function get(parameters: Parameters<typeof _18F56>[0], options?: Omit<Parameters<typeof _18F56>[1], 'throwOnError'>) {
    return getDataOrThrow(_18F56(parameters, options));
}

/**
 * Update a worker group
 */
export function update(parameters: Omit<Parameters<typeof _031Ffc737>[0], 'workerGroupControllerApiUpdateWorkerGroupRequest'> & WorkerGroupControllerApiUpdateWorkerGroupRequest, options?: Omit<Parameters<typeof _031Ffc737>[1], 'throwOnError'>) {
    return getDataOrThrow(_031Ffc737({ ...parameters, workerGroupControllerApiUpdateWorkerGroupRequest: parameters }, options));
}

export function getCapacity(parameters: Parameters<typeof _77Cf5230>[0], options?: Omit<Parameters<typeof _77Cf5230>[1], 'throwOnError'>) {
    return getDataOrThrow(_77Cf5230(parameters, options));
}

/**
 * Add a Worker Queue subscription to a worker group
 */
export function addSubscription(parameters: Omit<Parameters<typeof _06Fe9C3A2>[0], 'workerGroupControllerApiSubscriptionRequest'> & WorkerGroupControllerApiSubscriptionRequest, options?: Omit<Parameters<typeof _06Fe9C3A2>[1], 'throwOnError'>) {
    return getDataOrThrow(_06Fe9C3A2({ ...parameters, workerGroupControllerApiSubscriptionRequest: parameters }, options));
}

export function removeSubscription(parameters: Parameters<typeof _04Eb8003f>[0], options?: Omit<Parameters<typeof _04Eb8003f>[1], 'throwOnError'>) {
    return getDataOrThrow(_04Eb8003f(parameters, options));
}

/**
 * Update a subscription's reserved capacity
 */
export function updateSubscriptionReservation(parameters: Omit<Parameters<typeof _20D7B66>[0], 'workerGroupControllerApiUpdateSubscriptionRequest'> & WorkerGroupControllerApiUpdateSubscriptionRequest, options?: Omit<Parameters<typeof _20D7B66>[1], 'throwOnError'>) {
    return getDataOrThrow(_20D7B66({ ...parameters, workerGroupControllerApiUpdateSubscriptionRequest: parameters }, options));
}

/**
 * Generate a registration token
 */
export function generateToken(parameters: Omit<Parameters<typeof _6757D584>[0], 'workerGroupControllerApiGenerateTokenRequest'> & WorkerGroupControllerApiGenerateTokenRequest, options?: Omit<Parameters<typeof _6757D584>[1], 'throwOnError'>) {
    return getDataOrThrow(_6757D584({ ...parameters, workerGroupControllerApiGenerateTokenRequest: parameters }, options));
}

export function deleteToken(parameters: Parameters<typeof _0437Ae8F2>[0], options?: Omit<Parameters<typeof _0437Ae8F2>[1], 'throwOnError'>) {
    return getDataOrThrow(_0437Ae8F2(parameters, options));
}

export function revokeToken(parameters: Parameters<typeof _0219920Ed>[0], options?: Omit<Parameters<typeof _0219920Ed>[1], 'throwOnError'>) {
    return getDataOrThrow(_0219920Ed(parameters, options));
}

export function listRunningWorkers(parameters: Parameters<typeof _23F18A34>[0], options?: Omit<Parameters<typeof _23F18A34>[1], 'throwOnError'>) {
    return getDataOrThrow(_23F18A34(parameters, options));
}
