# See GitHub's docs for more information on this file:
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    labels:
      - "dependency-upgrade"
    open-pull-requests-limit: 50

  # Maintain dependencies for Gradle modules
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      # Check for updates to Gradle modules every week
      interval: "weekly"
    labels:
      - "dependency-upgrade"
    open-pull-requests-limit: 50

  # Maintain dependencies for NPM modules
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "08:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 50
    labels: ["dependency-upgrade"]
    reviewers: ["MilosPaunovic"]
    ignore:
      # Ignore major versions greater than 8, as it's still known to be flaky
      - dependency-name: "eslint"
        versions: [">8"]
      # Ignore updates of version 1.x, as we're using beta of 2.x
      - dependency-name: "vue-virtual-scroller"
        versions: ["1.x"]
