// @ts-check

/**
 * Generates the design-system colour layer from the Figma token export.
 *
 * Inputs:  scripts/Figma.json
 * Outputs: src/assets/styles/{_color-palette,ks-theme-light,ks-theme-dark}.scss
 *
 * Usage:   npm run generate:palette inside ui-design-system directory
 */

import fs from "node:fs"
import path from "node:path"
import {fileURLToPath} from "node:url"
import figma from "./Figma.json" with {type: "json"}

/** @typedef {{name: string, value: string, var: string}} FigmaColor */
/** @typedef {Record<string, string>} ColorIndex */

const STYLES_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../src/assets/styles")
const INDENT = "    "
const HEADER = `/**
 * This file is auto-generated by scripts/generate-palette.mjs.
 * It is a summary of color choices made in Figma.
 * Should you need to make a change in it, ask a designer
 * at Kestra first, so your changes are not overwritten.
 */`

const [{color: paletteLight}, {color: paletteDark}] = figma[0].values

const light = writeTheme(paletteLight, "light", ":root")
const dark = writeTheme(paletteDark, "dark", "html.dark")

checkPalettesMatch(light, dark)

/**
 * @param {FigmaColor[]} a
 * @param {FigmaColor[]} b
 */
function checkPalettesMatch(a, b) {
    for (const color of a) {
        const match = b.find(c => c.name === color.name)
        if (!match || match.value !== color.value) {
            console.error(`Color ${color.name} diverges between light and dark palettes`)
        }
    }
}

/**
 * @param {FigmaColor[]} palette
 * @param {string} theme
 * @param {string} selector
 * @returns {FigmaColor[]} the sorted base palette
 */
function writeTheme(palette, theme, selector) {
    const base = sortBase(palette.filter(c => c.name.startsWith("base-color-palette/")))
    const tokens = palette.filter(c => !c.name.startsWith("base-color-palette/"))
    /** @type {ColorIndex} */
    const index = Object.fromEntries(base.map(c => [c.value, shortName(c.name)]))

    fs.writeFileSync(path.resolve(STYLES_DIR, "_color-palette.scss"), renderPalette(base))
    fs.writeFileSync(path.resolve(STYLES_DIR, `ks-theme-${theme}.scss`), renderTheme(tokens, index, selector))

    return base
}

/** @param {string} name */
function shortName(name) {
    return name.split("/").pop() ?? ""
}

/** @param {FigmaColor[]} base */
function sortBase(base) {
    return [...base].sort((a, b) => {
        const [an, bn] = [shortName(a.name), shortName(b.name)]
        const [ar, br] = [an.split("-")[0], bn.split("-")[0]]
        if (ar !== br) return ar.localeCompare(br)
        if (an.length !== bn.length) return an.length - bn.length
        return an.localeCompare(bn)
    })
}

/** @param {FigmaColor[]} base */
function renderPalette(base) {
    let prev = ""
    const body = base.map(c => {
        const short = shortName(c.name)
        const group = short.split("-")[0]
        const heading = group !== prev ? `${prev ? "\n" : ""}/* ${group} */\n` : ""
        prev = group
        return `${heading}$base-${short}: ${c.value};`
    }).join("\n")
    return `${HEADER}\n${body}\n`
}

/**
 * @param {FigmaColor[]} tokens
 * @param {ColorIndex} index
 * @param {string} selector
 */
function renderTheme(tokens, index, selector) {
    let prev = ""
    const body = tokens.map(c => {
        const category = c.name.replace(/^ks\//, "").split("-")[0]
        const heading = category !== prev ? `\n${INDENT}/* ${category} */\n` : ""
        prev = category
        const varName = c.name.replace(/\//g, "-")
        return `${heading}${INDENT}#{--${varName}}: ${resolveValue(c, index)};`
    }).join("\n").trim()
    return `${HEADER}\n@use "color-palette" as *;\n\n${selector} {\n${INDENT}${body}\n}\n`
}

/**
 * @param {FigmaColor} color
 * @param {ColorIndex} index
 */
function resolveValue(color, index) {
    if (color.var.startsWith("base-color-palette/")) {
        return `$base-${shortName(color.var)}`
    }
    // 8-digit hex (#RRGGBBAA) → rgba($base-*, alpha) when the base colour is known
    if (color.value.length === 9) {
        const alpha = Math.round(parseInt(color.value.slice(7), 16) / 2.55) / 100
        const base = index[color.value.slice(0, 7)]
        if (base) return `rgba($base-${base}, ${alpha})`
    }
    return color.value
}
