/**
 * Refreshes the committed plugin catalog count baseline (src/utils/pluginCatalogCount.ts)
 * from the public API. Run weekly by the update-plugin-count GitHub workflow, which opens a
 * PR with the change; failures keep the committed value and never fail the run.
 */
import {writeFileSync} from "node:fs"
import {dirname, resolve} from "node:path"
import {fileURLToPath} from "node:url"
import {countUniquePluginElements, type Plugin} from "../src/utils/pluginUtils.ts"

const TARGET = resolve(dirname(fileURLToPath(import.meta.url)), "../src/utils/pluginCatalogCount.ts")
const CATALOG_URL = "https://api.kestra.io/v1/plugins/subgroups"
const FETCH_TIMEOUT_MS = 15000

try {
    const response = await fetch(CATALOG_URL, {signal: AbortSignal.timeout(FETCH_TIMEOUT_MS)})
    if (!response.ok) {
        throw new Error(`Unexpected HTTP status ${response.status} from ${CATALOG_URL}.`)
    }
    const plugins = await response.json() as Plugin[]
    const count = countUniquePluginElements(plugins ?? [])
    const rounded = Math.floor(count / 100) * 100
    if (rounded <= 0) {
        throw new Error(`Implausible plugin catalog count ${count}; keeping the committed baseline.`)
    }
    writeFileSync(TARGET, `// Auto-generated by scripts/update_plugin_catalog_count.ts — do not edit manually.
// Offline fallback for the catalog-wide plugin count, refreshed on every production build.
export const PLUGIN_CATALOG_COUNT = ${rounded}
`)
    console.log(`Plugin catalog count baseline set to ${rounded} (${count} element classes).`)
} catch (error) {
    console.warn(`Plugin catalog count baseline not refreshed, keeping the committed value: ${error instanceof Error ? error.message : error}`)
}
