// This file is auto-generated by @hey-api/openapi-ts

import {_02135D614, _5Ded489f, _6667C843} from "../sdk.gen";

export const generateDashboard = _5Ded489f;

export const generateFlow = _6667C843;

export const getProviders = _02135D614;
