// This file is auto-generated by @hey-api/openapi-ts

import {addTenantToParameters} from "./ks-shared.gen";
import {_1Aac14e} from "../sdk.gen";

/**
 * List blueprint tags matching the filter
 */
export const listBlueprintTags = (parameters: Omit<Parameters<typeof _1Aac14e>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _1Aac14e>[1]) => _1Aac14e(addTenantToParameters(parameters), options);
