// This file is auto-generated by @hey-api/openapi-ts

import {addTenantToParameters} from "./ks-shared.gen";
import {_030B1A670, _06666E52f, _1Ec18Cc3, _1F9D50E4, _41A7Bacb} from "../sdk.gen";

/**
 * Search for flow concurrency limits
 */
export const searchConcurrencyLimits = (parameters?: Omit<Parameters<typeof _1Ec18Cc3>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _1Ec18Cc3>[1]) => _1Ec18Cc3(addTenantToParameters(parameters), options);

/**
 * Update a flow concurrency limit
 */
export const updateConcurrencyLimit = (parameters: Omit<Parameters<typeof _06666E52f>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _06666E52f>[1]) => _06666E52f(addTenantToParameters(parameters), options);

/**
 * Generate a graph for a flow source
 */
export const generateFlowGraphFromSource = (parameters?: Omit<Parameters<typeof _030B1A670>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _030B1A670>[1]) => _030B1A670(addTenantToParameters(parameters), options);

/**
 * Generate a graph for a flow
 */
export const generateFlowGraph = (parameters: Omit<Parameters<typeof _41A7Bacb>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _41A7Bacb>[1]) => _41A7Bacb(addTenantToParameters(parameters), options);

/**
 * Get flow dependencies
 */
export const getFlowDependenciesFromNamespace = (parameters: Omit<Parameters<typeof _1F9D50E4>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _1F9D50E4>[1]) => _1F9D50E4(addTenantToParameters(parameters), options);
