// This file is auto-generated by @hey-api/openapi-ts

import {addTenantToParameters} from "./ks-shared.gen";
import {_02A5C7489, _06C136Fdf, _21216412, _459D2D6e, _4Ca5D6B4, _74Ae0977} from "../sdk.gen";

/**
 * Search for logs
 */
export const searchLogs = (parameters?: Omit<Parameters<typeof _02A5C7489>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _02A5C7489>[1]) => _02A5C7489(addTenantToParameters(parameters), options);

/**
 * Delete logs for a specific execution, taskrun or task
 */
export const deleteLogsFromExecution = (parameters: Omit<Parameters<typeof _4Ca5D6B4>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _4Ca5D6B4>[1]) => _4Ca5D6B4(addTenantToParameters(parameters), options);

/**
 * Get logs for a specific execution, taskrun or task
 */
export const listLogsFromExecution = (parameters: Omit<Parameters<typeof _06C136Fdf>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _06C136Fdf>[1]) => _06C136Fdf(addTenantToParameters(parameters), options);

/**
 * Download logs for a specific execution, taskrun or task
 */
export const downloadLogsFromExecution = (parameters: Omit<Parameters<typeof _74Ae0977>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _74Ae0977>[1]) => _74Ae0977(addTenantToParameters(parameters), options);

/**
 * Follow logs for a specific execution
 */
export const followLogsFromExecution = (parameters: Omit<Parameters<typeof _459D2D6e>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _459D2D6e>[1]) => _459D2D6e(addTenantToParameters(parameters), options);

/**
 * Delete logs for a specific execution, taskrun or task
 */
export const deleteLogsFromFlow = (parameters: Omit<Parameters<typeof _21216412>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _21216412>[1]) => _21216412(addTenantToParameters(parameters), options);
