// This file is auto-generated by @hey-api/openapi-ts

import {addTenantToParameters} from "./ks-shared.gen";
import {_0753B2353, _078936A73, _30933140, _334059E8, _435C395a, _6A59A9Ad} from "../sdk.gen";

export const getBasicAuthConfigErrors = _6A59A9Ad;

export const getConfiguration = _30933140;

export const getExpressionFilters = _078936A73;

export const getExpressionFunctions = _0753B2353;

/**
 * Configure basic authentication for the instance.
 */
export const createBasicAuth = (parameters?: Omit<Parameters<typeof _435C395a>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _435C395a>[1]) => _435C395a(addTenantToParameters(parameters), options);

/**
 * Retrieve instance usage information
 */
export const getUsages = (parameters?: Omit<Parameters<typeof _334059E8>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _334059E8>[1]) => _334059E8(addTenantToParameters(parameters), options);
