// This file is auto-generated by @hey-api/openapi-ts

import {addTenantToParameters} from "./ks-shared.gen";
import {_03F73Cd01, _0755159C0, _4A10C6A5, _548A6080} from "../sdk.gen";

/**
 * List namespaces for autocomplete
 */
export const autocompleteNamespaces = (parameters?: Omit<Parameters<typeof _548A6080>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _548A6080>[1]) => _548A6080(addTenantToParameters(parameters), options);

/**
 * Search for namespaces
 */
export const searchNamespaces = (parameters?: Omit<Parameters<typeof _0755159C0>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _0755159C0>[1]) => _0755159C0(addTenantToParameters(parameters), options);

/**
 * Get a namespace
 */
export const getNamespace = (parameters: Omit<Parameters<typeof _4A10C6A5>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _4A10C6A5>[1]) => _4A10C6A5(addTenantToParameters(parameters), options);

/**
 * List inherited secrets
 */
export const getInheritedSecrets = (parameters: Omit<Parameters<typeof _03F73Cd01>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _03F73Cd01>[1]) => _03F73Cd01(addTenantToParameters(parameters), options);
