// This file is auto-generated by @hey-api/openapi-ts

import {_023E2Be03, _02D5B2720, _04C6659B3, _07477A414, _09Bfeede, _0Aad6466, _36Cc3F94, _402B3Be4, _557632E4, _56210B11, _6Fb73243, d02B69d, e16C271} from "../sdk.gen";

export const listPlugins = _09Bfeede;

export const getPluginBySubgroups = _36Cc3F94;

export const getPluginIcons = e16C271;

export const getPluginGroupIcons = _557632E4;

export const getAllInputTypes = _0Aad6466;

export const getSchemaFromInputType = _6Fb73243;

export const getPluginUiManifest = _07477A414;

export const getPropertiesFromType = _04C6659B3;

export const getSchemasFromType = _02D5B2720;

export const getPluginDocumentation = _56210B11;

export const getPluginVersions = _402B3Be4;

export const getPluginDocumentationFromVersion = _023E2Be03;

export const getPluginUi = d02B69d;
