// This file is auto-generated by @hey-api/openapi-ts

import {addTenantToParameters} from "./ks-shared.gen";
import {_077F7Debb} from "../sdk.gen";

/**
 * Search secrets of all namespaces
 */
export const listSecrets = (parameters?: Omit<Parameters<typeof _077F7Debb>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _077F7Debb>[1]) => _077F7Debb(addTenantToParameters(parameters), options);
