// This file is auto-generated by @hey-api/openapi-ts

let globalTenant = "main";

export const setSelectedTenant = (newTenant: string) => {
    globalTenant = newTenant;
};

export const addTenantToParameters = <TParams>(parameters: TParams): TParams & {
    tenant: string;
} => ({tenant: globalTenant, ...parameters});
