// This file is auto-generated by @hey-api/openapi-ts

import {addTenantToParameters} from "./ks-shared.gen";
import {_01Af6F06f, _025Dffc7d, _0361F2856, _03C4Fde05, _0454D50C4, _04A8F87Fa, _04B613E73, _064E031A6, _0669E525e, _0675820B5, _06E9Fc5D4, _075D97736, _077995F6c, _0Af3543f, _0Dd4E62c, _2Bf5E58f, _2D079507, _2F570092, _3139A61a, _4153Db5, _674530A9, _7874E902, e736300} from "../sdk.gen";

/**
 * Create a backfill
 */
export const createBackfill = (parameters?: Omit<Parameters<typeof _04A8F87Fa>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _04A8F87Fa>[1]) => _04A8F87Fa(addTenantToParameters(parameters), options);

/**
 * Delete a backfill
 */
export const deleteBackfill = (parameters?: Omit<Parameters<typeof _4153Db5>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _4153Db5>[1]) => _4153Db5(addTenantToParameters(parameters), options);

/**
 * Delete backfill for given triggers
 */
export const deleteBackfillByQuery = (parameters?: Omit<Parameters<typeof _0454D50C4>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _0454D50C4>[1]) => _0454D50C4(addTenantToParameters(parameters), options);

/**
 * Delete backfill for given triggers
 */
export const deleteBackfillByIds = (parameters?: Omit<Parameters<typeof _06E9Fc5D4>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _06E9Fc5D4>[1]) => _06E9Fc5D4(addTenantToParameters(parameters), options);

/**
 * Pause a backfill
 */
export const pauseBackfill = (parameters?: Omit<Parameters<typeof e736300>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof e736300>[1]) => e736300(addTenantToParameters(parameters), options);

/**
 * Pause backfill for given triggers
 */
export const pauseBackfillByQuery = (parameters?: Omit<Parameters<typeof _01Af6F06f>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _01Af6F06f>[1]) => _01Af6F06f(addTenantToParameters(parameters), options);

/**
 * Pause backfill for given triggers
 */
export const pauseBackfillByIds = (parameters?: Omit<Parameters<typeof _0Af3543f>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _0Af3543f>[1]) => _0Af3543f(addTenantToParameters(parameters), options);

/**
 * Unpause a backfill
 */
export const unpauseBackfill = (parameters?: Omit<Parameters<typeof _2D079507>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _2D079507>[1]) => _2D079507(addTenantToParameters(parameters), options);

/**
 * Unpause backfill for given triggers
 */
export const unpauseBackfillByQuery = (parameters?: Omit<Parameters<typeof _0361F2856>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _0361F2856>[1]) => _0361F2856(addTenantToParameters(parameters), options);

/**
 * Unpause backfill for given triggers
 */
export const unpauseBackfillByIds = (parameters?: Omit<Parameters<typeof _3139A61a>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _3139A61a>[1]) => _3139A61a(addTenantToParameters(parameters), options);

/**
 * Delete triggers by query parameters
 */
export const deleteTriggersByQuery = (parameters?: Omit<Parameters<typeof _0675820B5>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _0675820B5>[1]) => _0675820B5(addTenantToParameters(parameters), options);

/**
 * Delete given triggers
 */
export const deleteTriggersByIds = (parameters?: Omit<Parameters<typeof _03C4Fde05>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _03C4Fde05>[1]) => _03C4Fde05(addTenantToParameters(parameters), options);

/**
 * Export all triggers as a streamed CSV file
 */
export const exportTriggers = (parameters?: Omit<Parameters<typeof _2Bf5E58f>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _2Bf5E58f>[1]) => _2Bf5E58f(addTenantToParameters(parameters), options);

/**
 * Search for triggers
 */
export const searchTriggers = (parameters?: Omit<Parameters<typeof _025Dffc7d>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _025Dffc7d>[1]) => _025Dffc7d(addTenantToParameters(parameters), options);

/**
 * Disable/enable a trigger
 */
export const disableTriggerById = (parameters?: Omit<Parameters<typeof _0669E525e>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _0669E525e>[1]) => _0669E525e(addTenantToParameters(parameters), options);

/**
 * Disable/enable triggers by query parameters
 */
export const disabledTriggersByQuery = (parameters?: Omit<Parameters<typeof _064E031A6>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _064E031A6>[1]) => _064E031A6(addTenantToParameters(parameters), options);

/**
 * Disable/enable given triggers
 */
export const disabledTriggersByIds = (parameters?: Omit<Parameters<typeof _075D97736>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _075D97736>[1]) => _075D97736(addTenantToParameters(parameters), options);

/**
 * Unlock triggers by query parameters
 */
export const unlockTriggersByQuery = (parameters?: Omit<Parameters<typeof _2F570092>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _2F570092>[1]) => _2F570092(addTenantToParameters(parameters), options);

/**
 * Unlock given triggers
 */
export const unlockTriggersByIds = (parameters?: Omit<Parameters<typeof _7874E902>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _7874E902>[1]) => _7874E902(addTenantToParameters(parameters), options);

/**
 * Get all triggers for a flow
 */
export const searchTriggersForFlow = (parameters: Omit<Parameters<typeof _077995F6c>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _077995F6c>[1]) => _077995F6c(addTenantToParameters(parameters), options);

/**
 * Delete a trigger
 */
export const deleteTrigger = (parameters: Omit<Parameters<typeof _04B613E73>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _04B613E73>[1]) => _04B613E73(addTenantToParameters(parameters), options);

/**
 * Restart a trigger
 */
export const restartTrigger = (parameters: Omit<Parameters<typeof _674530A9>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _674530A9>[1]) => _674530A9(addTenantToParameters(parameters), options);

/**
 * Unlock a trigger. Trigger will be unlocked asynchronously
 */
export const unlockTrigger = (parameters: Omit<Parameters<typeof _0Dd4E62c>[0], "tenant"> & {
    tenant?: string;
}, options?: Parameters<typeof _0Dd4E62c>[1]) => _0Dd4E62c(addTenantToParameters(parameters), options);
