package io.kestra.webserver.services.ai.agent.tool;

import java.util.Map;

import com.fasterxml.jackson.core.JsonProcessingException;

import io.kestra.core.docs.JsonSchemaGenerator;
import io.kestra.core.models.Plugin;
import io.kestra.core.plugins.PluginClassAndMetadata;
import io.kestra.core.plugins.PluginRegistry;
import io.kestra.core.serializers.JacksonMapper;
import io.kestra.webserver.services.ai.agent.domain.AgentToolFamily;
import io.kestra.webserver.services.ai.agent.domain.AgentWritePolicy;

import dev.langchain4j.agent.tool.P;
import dev.langchain4j.agent.tool.Tool;
import jakarta.inject.Inject;
import jakarta.inject.Singleton;

/**
 * Read-only agent tool returning the JSON schema of a single plugin type, as generated by
 * {@link JsonSchemaGenerator}.
 */
@Singleton
public class GetPluginSchemaTool implements AiPlatformTool {
    private final PluginRegistry pluginRegistry;
    private final JsonSchemaGenerator jsonSchemaGenerator;

    @Inject
    public GetPluginSchemaTool(final PluginRegistry pluginRegistry, final JsonSchemaGenerator jsonSchemaGenerator) {
        this.pluginRegistry = pluginRegistry;
        this.jsonSchemaGenerator = jsonSchemaGenerator;
    }

    @Override
    public AgentToolFamily family() {
        return AgentToolFamily.READ;
    }

    @Override
    public AgentWritePolicy writePolicy() {
        return AgentWritePolicy.AUTO;
    }

    @Tool(
        name = "get-plugin-schema",
        value = "Get the JSON schema of a Kestra plugin type (its configuration properties and their types). Read-only; use this to learn how to configure a task, trigger or other plugin before authoring flow YAML."
    )
    public String getPluginSchema(
        @P(name = "pluginType", value = "The fully-qualified plugin type, e.g. io.kestra.plugin.core.log.Log") String pluginType) {
        PluginClassAndMetadata<? extends Plugin> metadata = pluginRegistry.findMetadataByIdentifier(pluginType)
            .orElseThrow(() -> new IllegalArgumentException("Plugin type not found: '" + pluginType + "'"));

        Map<String, Object> schema = jsonSchemaGenerator.schemas(metadata.type());
        try {
            return JacksonMapper.ofJson().writeValueAsString(schema);
        } catch (JsonProcessingException e) {
            throw new IllegalStateException("Failed to serialize the schema of '" + pluginType + "': " + e.getMessage(), e);
        }
    }
}
