package io.kestra.webserver.services.ai.agent.tool;

import java.util.Map;

import io.kestra.core.ai.agent.models.AgentToolFamily;
import io.kestra.core.ai.agent.models.AgentWritePolicy;
import io.kestra.core.docs.JsonSchemaGenerator;
import io.kestra.core.models.Plugin;
import io.kestra.core.plugins.PluginClassAndMetadata;
import io.kestra.core.plugins.PluginRegistry;

import dev.langchain4j.agent.tool.P;
import dev.langchain4j.agent.tool.Tool;
import jakarta.inject.Inject;
import jakarta.inject.Singleton;

/**
 * Read-only agent tool returning the JSON schema of a single plugin type, as generated by
 * {@link JsonSchemaGenerator}.
 */
@Singleton
public class GetPluginSchemaTool implements AiPlatformTool {
    private final PluginRegistry pluginRegistry;
    private final JsonSchemaGenerator jsonSchemaGenerator;

    @Inject
    public GetPluginSchemaTool(final PluginRegistry pluginRegistry, final JsonSchemaGenerator jsonSchemaGenerator) {
        this.pluginRegistry = pluginRegistry;
        this.jsonSchemaGenerator = jsonSchemaGenerator;
    }

    @Override
    public AgentToolFamily family() {
        return AgentToolFamily.READ;
    }

    @Override
    public AgentWritePolicy writePolicy() {
        return AgentWritePolicy.AUTO;
    }

    @Tool(
        name = "get-plugin-schema",
        value = "Get the JSON schema of a Kestra plugin type (its configuration properties and their types). Read-only; use this to learn how to configure a task, trigger or other plugin before authoring flow YAML. "
            + "Returns an object { pluginType, schema } where `schema` is the plugin's JSON schema (a nested object of properties and their types)."
    )
    public Result getPluginSchema(
        @P(name = "pluginType", value = "The fully-qualified plugin type, e.g. io.kestra.plugin.core.log.Log") String pluginType) {
        PluginClassAndMetadata<? extends Plugin> metadata = pluginRegistry.findMetadataByIdentifier(pluginType)
            .orElseThrow(() -> new IllegalArgumentException("Plugin type not found: '%s'".formatted(pluginType)));

        return new Result(pluginType, jsonSchemaGenerator.schemas(metadata.type()));
    }

    public record Result(String pluginType, Map<String, Object> schema) {
    }
}
