name: 'Frontend Test'

inputs:
  example-input:
    description: 'An example input'
    required: false
    default: 'default value'

runs:
  using: composite
  steps:
    - id: checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }} # Using ref_name in case translations has committed something
    - name: Npm install
      shell: bash
      working-directory: ui
      run: npm ci

    - name: Npm lint
      uses: reviewdog/action-eslint@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review # Change reporter.
        workdir: "ui"

    - name: Run front-end unit tests
      shell: bash
      working-directory: ui
      run: npm run test:unit

    - name: Install Playwright
      shell: bash
      working-directory: ui
      run: npx playwright install --with-deps

    - name: Build Storybook
      shell: bash
      working-directory: ui
      run: npm run build-storybook --quiet

    - name: Serve Storybook and run tests
      shell: bash
      working-directory: ui
      run: |
        npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
          "npx http-server storybook-static --port 6006 --silent" \
          "npx wait-on tcp:127.0.0.1:6006 && npm run test-storybook"
