configurations {
    implementation.extendsFrom(micronaut)
}

dependencies {
    implementation project(':webserver-api')
    implementation "io.micronaut:micronaut-http-server-netty"
}

// Static assets require the frontend to be built first
if (rootProject.name == "kestra") {
    tasks.named('processResources') {
        mustRunAfter(':ui:assembleFrontend')
    }
}
