ALTER TABLE triggers ADD COLUMN IF NOT EXISTS "last_triggered_date" TIMESTAMP GENERATED ALWAYS AS (CAST(LEFT(JQ_STRING("value", '.lastTriggeredDate'), 26) AS TIMESTAMP));

ALTER TABLE triggers ADD COLUMN IF NOT EXISTS "type" VARCHAR(250) GENERATED ALWAYS AS (JQ_STRING("value", '.type'));
