name: Blueprint
description: Add a new blueprint

body:
  - type: markdown
    attributes:
      value: |
        Please fill out all the fields listed below. This will help us review and add your blueprint faster.
  
  - type: textarea
    attributes:
      label: Blueprint title
      description: A title briefly describing what the blueprint does, ideally in a verb phrase + noun format.
      placeholder: E.g. "Upload a file to service X, then run Y and Z"
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Source code
      description: Flow code that will appear on the Blueprint page.
      placeholder: |
        ```yaml
        id: yourFlowId
        namespace: blueprint
        tasks:
          - id: taskName
            type: task_type
        ```
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: About this blueprint
      description: "A concise markdown documentation about the blueprint's configuration and usage."
      placeholder: |
        E.g. "This flow downloads a file and uploads it to an S3 bucket. This flow assumes AWS credentials stored as environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`."
    validations:
      required: false
  
  - type: textarea
    attributes:
      label: Tags (optional)
      description: Blueprint categories such as Ingest, Transform, Analyze, Python, Docker, AWS, GCP, Azure, etc.
      placeholder: |
        - Ingest
        - Transform
        - AWS
    validations:
      required: false

labels:
  - blueprint