name: Bug Report
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue, please review the task list below before submitting the issue. Your issue report will be closed if the issue is incomplete and the below tasks not completed.

        NOTE: If you are unsure about something and the issue is more of a question a better place to ask questions is on [Github Discussions](https://github.com/kestra-io/kestra/discussions) or [Slack](https://kestra.io/slack).
  - type: textarea
    attributes:
      label: Explain the bug
      description: A concise description of the problem
      placeholder: Describe the problem and provide steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment Information
      description: Environment information where the problem occurs.
      value: |
        - Kestra Version:
        - Operating System and Java Version (if not using Kestra Docker image):
    validations:
      required: true
labels:
  - bug