name: Feature request
description: Create a new feature request
body:
  - type: textarea
    attributes:
      label: Feature description
      placeholder: Tell us more about your feature request
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Priority
      options:
        - High
        - Medium
        - Low  
labels:
  - enhancement
  - area/backend
  - area/frontend
