package io.kestra.repository.postgres.migration;

import io.kestra.jdbc.migration.AbstractV2_0_10BasicAuthPasswordMigrationTest;

class PostgresV2_0_10BasicAuthPasswordMigrationTest extends AbstractV2_0_10BasicAuthPasswordMigrationTest {
}
