package io.kestra.repository.postgres.migration;

import io.kestra.jdbc.migration.AbstractV2_0_24PluginAutoInstallMigrationTest;

class PostgresV2_0_24PluginAutoInstallMigrationTest extends AbstractV2_0_24PluginAutoInstallMigrationTest {
}
