// Auto-generated by scripts/update_plugin_catalog_count.ts — do not edit manually.
// Offline fallback for the catalog-wide plugin count, refreshed on every production build.
export const PLUGIN_CATALOG_COUNT = 1900
