package io.kestra.repository.h2.migration;

import io.kestra.jdbc.migration.AbstractV2_0_26PurgeLegacyWorkerJobRunningMigrationTest;

class H2V2_0_26PurgeLegacyWorkerJobRunningMigrationTest extends AbstractV2_0_26PurgeLegacyWorkerJobRunningMigrationTest {
}
