{{- if .Values.deployments.controller.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "kestra.fullname" . }}-controller"
  labels:
    {{- include "kestra.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: {{ .Values.service.ports.grpc.port }}
      targetPort: {{ .Values.service.ports.grpc.targetPort }}
      protocol: {{ .Values.service.ports.grpc.protocol | default "TCP" }}
  selector:
    {{- include "kestra.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
{{- end }}
