publishSonatypePublicationPublicationToSonatypeRepository.enabled = false

if (rootProject.name == "kestra") {
    processResources {
        dependsOn(':ui:assembleFrontend')
    }
}

configurations {
    implementation.extendsFrom(micronaut)
}

dependencies {

    annotationProcessor "io.micronaut.openapi:micronaut-openapi"
    compileOnly "io.micronaut.openapi:micronaut-openapi-annotations"

    annotationProcessor project(':processor')
    implementation project(":core")

    implementation "io.micronaut:micronaut-management"
    implementation "io.micronaut:micronaut-http-client"
    implementation "io.micronaut:micronaut-http-server-netty"
    implementation "io.micronaut.cache:micronaut-cache-core"
    implementation "io.micronaut.cache:micronaut-cache-caffeine"

    
    implementation 'org.apache.parquet:parquet-hadoop-bundle:1.15.1'
    implementation ('org.apache.hadoop:hadoop-common:3.3.6') {
        exclude group: 'org.slf4j', module: 'slf4j-reload4j'
    }
    implementation('org.apache.hadoop:hadoop-mapreduce-client-core:3.3.6') {
        exclude group: 'org.slf4j', module: 'slf4j-reload4j'
    }

    // test
    testAnnotationProcessor project(':processor')
    testImplementation project(':core').sourceSets.test.output
    testImplementation project(':storage-local')
    testImplementation "org.wiremock:wiremock-jetty12"

    testImplementation project(':tests')
    testImplementation project(':jdbc')
    testImplementation project(':jdbc').sourceSets.test.output
    testImplementation project(':jdbc-h2')
    testImplementation("io.micronaut.sql:micronaut-jooq")
}


