configurations {
    implementation.extendsFrom(micronaut)
}

dependencies {
    annotationProcessor project(":processor")
    implementation project(":core")
    implementation project(":jdbc")
    implementation project(":executor")
    implementation project(":scheduler")
    implementation project(":queue")
    implementation project(":queue-jdbc")

    implementation("io.micronaut.sql:micronaut-jooq")
    implementation("com.github.ben-manes.caffeine:caffeine")
    runtimeOnly("com.h2database:h2")

    testAnnotationProcessor project(":processor")
    testImplementation project(path: ':core', configuration: 'testArtifacts')
    testImplementation project(path: ':jdbc', configuration: 'testArtifacts')
    testImplementation project(path: ':executor', configuration: 'testArtifacts')
    testImplementation project(':storage-local')
    testImplementation project(':indexer')
    testImplementation project(':tests')
    testImplementation project(path: ':queue', configuration: 'testArtifacts')
}
