ALTER TABLE triggers ADD COLUMN IF NOT EXISTS "last_triggered_date" TIMESTAMPTZ GENERATED ALWAYS AS (PARSE_ISO8601_DATETIME(value ->> 'lastTriggeredDate')) STORED;

ALTER TABLE triggers ADD COLUMN IF NOT EXISTS "type" VARCHAR(250) GENERATED ALWAYS AS (value ->> 'type') STORED;
