configurations {
    implementation.extendsFrom(micronaut)
}

dependencies {
    annotationProcessor project(":processor")
    implementation project(":core")
    implementation project(":jdbc")
    implementation project(":executor")
    implementation project(":scheduler")
    implementation project(":queue")
    implementation project(":queue-jdbc")

    implementation("io.micronaut.sql:micronaut-jooq")
    runtimeOnly("com.mysql:mysql-connector-j")

    testAnnotationProcessor project(":processor")
    testImplementation project(path: ':core', configuration: 'testArtifacts')
    testImplementation project(path: ':jdbc', configuration: 'testArtifacts')
    testImplementation project(path: ':executor', configuration: 'testArtifacts')
    testImplementation project(path: ':scheduler', configuration: 'testArtifacts')
    testImplementation project(':storage-local')
    testImplementation project(':indexer')
    testImplementation project(':tests')
    testImplementation project(path: ':queue', configuration: 'testArtifacts')
    testImplementation("io.micronaut.validation:micronaut-validation") // MysqlServiceLivenessCoordinatorTest fail to init without that
}
