package io.kestra.plugin.core.storage;

import com.fasterxml.jackson.core.type.TypeReference;
import io.kestra.core.models.property.Property;
import io.kestra.core.serializers.JacksonMapper;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.*;
import lombok.experimental.SuperBuilder;
import org.apache.commons.io.IOUtils;
import io.kestra.core.models.annotations.Example;
import io.kestra.core.models.annotations.Plugin;
import io.kestra.core.models.annotations.PluginProperty;
import io.kestra.core.models.tasks.RunnableTask;
import io.kestra.core.models.tasks.Task;
import io.kestra.core.runners.RunContext;

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.net.URI;
import java.util.List;

import jakarta.validation.constraints.NotNull;

import static io.kestra.core.utils.Rethrow.throwConsumer;

@SuperBuilder
@ToString
@EqualsAndHashCode
@Getter
@NoArgsConstructor
@Schema(
    title = "Concatenate files from Kestra internal storage.",
    description = """
        Reads a list of `kestra://` URIs (list or JSON string), streams them in order into a single file, and returns the new URI. Optional `separator` is inserted between files; output extension defaults to `.tmp`.

        Use when you need to merge task outputs without downloading locally."""
)
@Plugin(
    examples = {
         @Example(
            title = "Concat a 2 files.",
            full = true,
            code = """
                id: concat_example
                namespace: company.team

                tasks:
                  - id: first_file
                    type: io.kestra.plugin.scripts.shell.Commands
                    commands:
                      - echo "Hello John" > name.txt
                    outputFiles:
                      - "name.txt"
  
                  - id: second_file
                    type: io.kestra.plugin.scripts.shell.Commands
                    commands:
                    - echo "Hello Jane" > name.txt
                    outputFiles:
                      - "name.txt"

                  - id: concat
                    type: io.kestra.plugin.core.storage.Concat
                    files:
                      - "{{ outputs.first_file.outputFiles['name.txt'] }}"
                      - "{{ outputs.second_file.outputFiles['name.txt'] }}"
            """
         ),
        @Example(
            title = "Concat 2 files with a custom separator that adds a new line between each file.",
            full = true,
            code = """
                id: concat_example
                namespace: company.team

                tasks:
                  - id: first_file
                    type: io.kestra.plugin.scripts.shell.Commands
                    commands:
                      - echo "Hello John\nGoodbye John" > name.txt
                    outputFiles:
                      - "name.txt"

                  - id: second_file
                    type: io.kestra.plugin.scripts.shell.Commands
                    commands:
                      - echo "Hello Jane\nGoodbyeJane" > name.txt
                    outputFiles:
                      - "name.txt"

                  - id: concat
                    type: io.kestra.plugin.core.storage.Concat
                    separator: "\n"
                    files:
                      - "{{ outputs.first_file.outputFiles['name.txt'] }}"
                      - "{{ outputs.second_file.outputFiles['name.txt'] }}"
            """
        ),
        @Example(
            title = "Concat a dynamic number of files.",
            full = true,
            code = """
                id: concat_example
                namespace: company.team

                tasks:
                  - id: generate_files
                    type: io.kestra.plugin.scripts.shell.Commands
                    commands:
                      - echo "Hello John" > 1.txt
                      - echo "Hello Jane" > 2.txt
                      - echo "Hello Doe" > 3.txt
                    outputFiles:
                      - "*.txt"

                  - id: concat
                    type: io.kestra.plugin.core.storage.Concat
                    files: "{{ outputs.generate_files.outputFiles | jq('.[]') }}"
            """
        ),
        @Example(
            title = "Concat files generated by a ForEach task.",
            full = true,
            code = """
                id: concat_example
                namespace: company.team
     
                tasks:
                  - id: foreach
                    type: io.kestra.plugin.core.flow.ForEach
                    values: ["value1", "value2", "value3"]
                    tasks:
                      - id: start_api_call
                        type: io.kestra.plugin.scripts.shell.Commands
                        commands:
                          - echo {{ taskrun.value }} > data.txt
                        outputFiles:
                          - data.txt

                  - id: concat_foreach_manual
                    type: io.kestra.plugin.core.storage.Concat
                    files: "{{ outputs.start_api_call | jq('.[].outputFiles.generated') }}"
                """
        )
    },
    aliases = "io.kestra.core.tasks.storages.Concat"
)
public class Concat extends Task implements RunnableTask<Concat.Output> {
    @Schema(
        title = "List of files to be concatenated",
        description = "Must be `kestra://` storage URIs; it can be a list of strings or a JSON string."
    )
    @PluginProperty(dynamic = true, internalStorageURI = true)
    @NotNull
    private Object files;

    @Schema(
        title = "The separator to used between files — the default is no separator"
    )
    private Property<String> separator;

    @Schema(
        title = "The extension of the created file — the default is `.tmp`"
    )
    @Builder.Default
    private Property<String> extension = Property.ofValue(".tmp");

    @SuppressWarnings("unchecked")
    @Override
    public Concat.Output run(RunContext runContext) throws Exception {
        File tempFile = runContext.workingDir().createTempFile(runContext.render(extension).as(String.class).orElseThrow()).toFile();
        try (FileOutputStream fileOutputStream = new FileOutputStream(tempFile)) {
            List<String> finalFiles;
            if (this.files instanceof List<?> listValue) {
                finalFiles = (List<String>) listValue;
            } else if (this.files instanceof String stringValue) {
                final TypeReference<List<String>> reference = new TypeReference<>() {};

                finalFiles = JacksonMapper.ofJson(false).readValue(
                    runContext.render(stringValue),
                    reference
                );
            } else {
                throw new Exception("Invalid `files` properties with type '" + this.files.getClass() + "'");
            }

            finalFiles.forEach(throwConsumer(s -> {
                URI from = new URI(runContext.render(s));
                try (InputStream inputStream = runContext.storage().getFile(from)) {
                    IOUtils.copyLarge(inputStream, fileOutputStream);
                }

                if (separator != null) {
                    IOUtils.copy(new ByteArrayInputStream(runContext.render(this.separator).as(String.class).orElseThrow().getBytes()), fileOutputStream);
                }
            }));
        }

        return Concat.Output.builder()
            .uri(runContext.storage().putFile(tempFile))
            .build();
    }

    @Builder
    @Getter
    public static class Output implements io.kestra.core.models.tasks.Output {
        @Schema(
            title = "The concatenated file URI"
        )
        private final URI uri;
    }
}
