package io.kestra.plugin.core.storage;

import io.kestra.core.models.annotations.Example;
import io.kestra.core.models.annotations.Plugin;
import io.kestra.core.models.annotations.PluginProperty;
import io.kestra.core.models.property.Property;
import io.kestra.core.models.tasks.RunnableTask;
import io.kestra.core.models.tasks.Task;
import io.kestra.core.runners.RunContext;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import lombok.*;
import lombok.experimental.SuperBuilder;

import java.net.URI;

@SuperBuilder
@ToString
@EqualsAndHashCode
@Getter
@NoArgsConstructor
@Schema(
    title = "Get the size of a file in Kestra internal storage.",
    description = "Reads the file attributes for the given `kestra://` URI and returns its size in bytes."
)
@Plugin(
    examples = {
        @Example(
            title = "Get the size of a text file generated by another task.",
            full = true,
            code = """
                id: get_file_size
                namespace: company.team

                tasks:
                  - id: generate_file
                    type: io.kestra.plugin.scripts.shell.Commands
                    commands:
                      - echo "Hello John" > name.txt
                    outputFiles:
                      - "name.txt"

                  - id: get_size
                    type: io.kestra.plugin.core.storage.Size
                    uri: "{{ outputs.generate_file.outputFiles['name.txt'] }}"

                  - id: log
                    type: io.kestra.plugin.core.log.Log
                    message: "{{ outputs.get_size.size }} bytes"
            """
        )
    },
    aliases = "io.kestra.core.tasks.storages.Size"
)
public class Size extends Task implements RunnableTask<Size.Output> {
    @Schema(
        title = "The file where size needs to be fetched"
    )
    @NotNull
    @PluginProperty(internalStorageURI = true)
    private Property<String> uri;

    @Override
    public Size.Output run(RunContext runContext) throws Exception {
        URI render = URI.create(runContext.render(this.uri).as(String.class).orElseThrow());

        Long size = runContext.storage().getAttributes(render).getSize();

        return Output.builder()
            .size(size)
            .build();
    }

    @Builder
    @Getter
    public static class Output implements io.kestra.core.models.tasks.Output {
        @Schema(
            title = "The size of the file in bytes"
        )
        private final Long size;
    }
}
