name: 'Load Kestra Plugin List'
description: 'Composite action to load list of plugins'
inputs:
  plugin-version:
    description: "Kestra version"
    default: 'LATEST'
    required: true
  plugin-file:
    description: "File of the plugins"
    default: './.plugins'
    required: true
outputs:
  plugins:
    description: "List of all Kestra plugins"
    value: ${{ steps.plugins.outputs.plugins }}
  repositories:
    description: "List of all Kestra repositories of plugins"
    value: ${{ steps.plugins.outputs.repositories }}
runs:
  using: composite
  steps:
    - name: Get Plugins List
      id: plugins
      shell: bash
      run: |
        PLUGINS=$([ -f ${{ inputs.plugin-file }} ] && cat ${{ inputs.plugin-file }} | grep "io\\.kestra\\." | sed -e '/#/s/^.//' | sed -e "s/LATEST/${{ inputs.plugin-version }}/g" | cut -d':' -f2- | xargs || echo '');
        REPOSITORIES=$([ -f ${{ inputs.plugin-file }} ] && cat ${{ inputs.plugin-file }} | grep "io\\.kestra\\." | sed -e '/#/s/^.//' | cut -d':' -f1 | uniq | sort | xargs || echo '')
        echo "plugins=$PLUGINS" >> $GITHUB_OUTPUT
        echo "repositories=$REPOSITORIES" >> $GITHUB_OUTPUT
