#!/bin/sh

staged_files=$(git --no-pager diff --cached --name-only | grep '\.java')

#if [ -n "$staged_files" ]; then
#  echo "Running spotlessApply Java files..."
#    ./gradlew spotlessApply "$file"
#  done
#
#  git add $staged_files
#
#  echo "spotlessApply completed."
#else
#  echo "No Java files modified. Skipping spotlessApply."
#fi

echo "Linting UI"
cd ui && npx lint-staged