configurations {
    tests
    implementation.extendsFrom(micronaut)
}

dependencies {
    // Kestra
    annotationProcessor project(':processor')
    implementation project(":core")
    implementation project(":worker-controller")

    implementation "dev.failsafe:failsafe"
    implementation "com.github.ben-manes.caffeine:caffeine"

    // test
    testAnnotationProcessor project(':processor')
    testImplementation project(path: ':core', configuration: 'testArtifacts')
    testImplementation project(':storage-local')

    testImplementation project(':tests')
    testImplementation project(':jdbc')
    testImplementation project(path: ':jdbc', configuration: 'testArtifacts')
    testImplementation project(path: ':queue', configuration: 'testArtifacts')

    testImplementation project(':jdbc-h2')
    testImplementation("io.micronaut.sql:micronaut-jooq")

    // gRPC
    implementation("io.micronaut.grpc:micronaut-grpc-server-runtime")
    implementation("io.micronaut.grpc:micronaut-grpc-client-runtime")
}