export const auditLogTypes = [
    {value: "io.kestra.ee.models.audits.details.AuditLogAuditLog", label: "Auditlog"},
    {value: "io.kestra.ee.models.audits.details.AppAuditLog", label: "App"},
    {value: "io.kestra.ee.models.audits.details.AppExecuteAuditLog", label: "App Execution"},
    {value: "io.kestra.ee.models.audits.details.BlueprintAuditLog", label: "Blueprint"},
    {value: "io.kestra.ee.models.audits.details.BindingAuditLog", label: "Binding"},
    {value: "io.kestra.ee.models.audits.details.DashboardAuditLog", label: "Dashboard"},
    {value: "io.kestra.ee.models.audits.details.ExecutionAuditLog", label: "Execution"},
    {value: "io.kestra.ee.models.audits.details.FlowAuditLog", label: "Flow"},
    {value: "io.kestra.ee.models.audits.details.GroupAuditLog", label: "Group"},
    {value: "io.kestra.ee.models.audits.details.InvitationAuditLog", label: "Invitation"},
    {value: "io.kestra.ee.models.audits.details.KvStoreAuditLog", label: "Kv Store"},
    {value: "io.kestra.ee.models.audits.details.NamespaceAuditLog", label: "Namespace"},
    {value: "io.kestra.ee.models.audits.details.NamespaceFileAuditLog", label: "Namespace File"},
    {value: "io.kestra.ee.models.audits.details.RoleAuditLog", label: "Role"},
    {value: "io.kestra.ee.models.audits.details.SecurityIntegrationAuditLog", label: "Security Integration"},
    {value: "io.kestra.ee.models.audits.details.SecretAuditLog", label: "Secret"},
    {value: "io.kestra.ee.models.audits.details.SettingAuditLog", label: "Setting"},
    {value: "io.kestra.ee.models.audits.details.TemplateAuditLog", label: "Template"},
    {value: "io.kestra.ee.models.audits.details.TenantAuditLog", label: "Tenant"},
    {value: "io.kestra.ee.models.audits.details.TenantAccessAuditLog", label: "Tenant Access"},
    {value: "io.kestra.ee.models.audits.details.TestSuiteAuditLog", label: "Testsuite"},
    {value: "io.kestra.ee.models.audits.details.TestSuiteRunAuditLog", label: "Testsuite Run"},
    {value: "io.kestra.ee.models.audits.details.VersionedPluginAuditLog", label: "Versioned Plugin"},
    {value: "io.kestra.ee.models.audits.details.UserAuditLog", label: "User"},
    {value: "io.kestra.ee.models.audits.details.WorkerGroupAuditLog", label: "Worker Group"},
    {value: "io.kestra.ee.models.audits.details.InstanceAuditLog", label: "Instance"}
];
