export const auditLogTypes = [
    {value: "io.kestra.ee.models.audits.details.AppAuditLog", label: "App"},
    {value: "io.kestra.ee.models.audits.details.AppExecuteAuditLog", label: "AppExecute"},
    {value: "io.kestra.ee.models.audits.details.BindingAuditLog", label: "Binding"},
    {value: "io.kestra.ee.models.audits.details.DashboardAuditLog", label: "Dashboard"},
    {value: "io.kestra.ee.models.audits.details.ExecutionAuditLog", label: "Execution"},
    {value: "io.kestra.ee.models.audits.details.FlowAuditLog", label: "Flow"},
    {value: "io.kestra.ee.models.audits.details.GroupAuditLog", label: "Group"},
    {value: "io.kestra.ee.models.audits.details.InvitationAuditLog", label: "Invitation"},
    {value: "io.kestra.ee.models.audits.details.LogEntryAuditLog", label: "LogEntry"},
    {value: "io.kestra.ee.models.audits.details.NamespaceAuditLog", label: "Namespace"},
    {value: "io.kestra.ee.models.audits.details.RoleAuditLog", label: "Role"},
    {value: "io.kestra.ee.models.audits.details.SecretAuditLog", label: "Secret"},
    {value: "io.kestra.ee.models.audits.details.SecurityIntegrationAuditLog", label: "SecurityIntegration"},
    {value: "io.kestra.ee.models.audits.details.SettingAuditLog", label: "Setting"},
    {value: "io.kestra.ee.models.audits.details.TemplateAuditLog", label: "Template"},
    {value: "io.kestra.ee.models.audits.details.TenantAuditLog", label: "Tenant"},
    {value: "io.kestra.ee.models.audits.details.TestSuiteAuditLog", label: "TestSuite"},
    {value: "io.kestra.ee.models.audits.details.UserAuditLog", label: "User"},
    {value: "io.kestra.ee.models.audits.details.WorkerGroupAuditLog", label: "WorkerGroup"}
];
