export default {
    FLOW: "FLOW",
    EXECUTION: "EXECUTION",
    TEMPLATE: "TEMPLATE",
    NAMESPACE: "NAMESPACE",
    KVSTORE: "KVSTORE",
    DASHBOARD: "DASHBOARD",
    SECRET: "SECRET",
    AI_COPILOT: "AI_COPILOT"
}
