export default {
    FLOW: "FLOW",
    EXECUTION: "EXECUTION",
    NAMESPACE: "NAMESPACE",
    KVSTORE: "KVSTORE",
    DASHBOARD: "DASHBOARD",
    SECRET: "SECRET",
    COPILOT: "COPILOT",
    MCP_SERVER: "MCP_SERVER",
}
