name: "E2E tests scheduling"

on:
  schedule:
    - cron: "0 9-21/2 * * 1-5" # Every 2 hours from 9 AM to 9 PM, Monday to Friday
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e:
    uses: kestra-io/actions/.github/workflows/kestra-oss-e2e-tests.yml@main
    with:
      java-version: 25

  otel-export-trace:
    name: OpenTelemetry - Export Trace
    runs-on: ubuntu-latest
    if: always()
    needs: [ e2e ]
    env:
      OTLP_ENDPOINT: ${{ secrets.OTLP_ENDPOINT }}
    steps:
      - name: OpenTelemetry - Export trace
        uses: kestra-io/actions/actions/otel-collect@main
        if: ${{ env.OTLP_ENDPOINT != '' }}
        with:
          mode: export-all
          github-token: ${{ secrets.GITHUB_TOKEN }}
          otlp-endpoint: ${{ secrets.OTLP_ENDPOINT }}
          otlp-headers: "${{ secrets.OTLP_HEADERS }}"
          logs-enabled: 'true'
          service-name: "Github Actions - ${{ github.repository }} - ${{ github.workflow }}"
