name: Release Modified Kestra Plugins (Manual Trigger)

on:
  workflow_dispatch:
    inputs:
      kestraVersion:
        description: 'The Kestra version to set when a plugin has a breaking change'
        required: false
        type: string
      dryRun:
        description: 'Use DRY_RUN mode'
        required: false
        default: 'false'

jobs:
  release:
    name: Release Modified Plugins
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.GH_PERSONAL_TOKEN }}

      - uses: kestra-io/actions/composite/setup-build@main
        id: build
        with:
          java-enabled: true
          node-enabled: true
          python-enabled: true
          caches-enabled: true

      - name: Get Modified Plugins List
        uses: ./.github/actions/changed-plugins-list
        id: plugins-list
        with:
          plugin-version: 'LATEST'

      - name: Configure Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Run Gradle Release
        if: ${{ github.event.inputs.dryRun == 'false' }}
        env:
          GITHUB_PAT: ${{ secrets.GH_PERSONAL_TOKEN }}
        run: |
          chmod +x ./dev-tools/release-plugins.sh

          ./dev-tools/release-plugins.sh \
            ${{ github.event.inputs.kestraVersion && format('--kestra-version={0}', github.event.inputs.kestraVersion) || '' }} \
            ${{ steps.plugins-list.outputs.repositories }}

      - name: Run Gradle Release (DRY_RUN)
        if: ${{ github.event.inputs.dryRun == 'true' }}
        env:
          GITHUB_PAT: ${{ secrets.GH_PERSONAL_TOKEN }}
        run: |
          chmod +x ./dev-tools/release-plugins.sh

          ./dev-tools/release-plugins.sh \
            ${{ github.event.inputs.kestraVersion && format('--kestra-version={0}', github.event.inputs.kestraVersion) || '' }} \
            --dry-run \
            ${{ steps.plugins-list.outputs.repositories }}
