name: Pull Request - Delete Docker

on:
  pull_request:
    types: [closed]
# TODO import a reusable one
jobs:
  publish:
    name: Pull Request - Delete Docker
    if: github.repository == 'kestra-io/kestra' # prevent running on forks
    runs-on: ubuntu-latest
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@d52806a0dc70b430571a37da1fde39733ffd640f # v1.2.2
        with:
          package: kestra-pr
          delete-tags: ${{ github.event.pull_request.number }}