name: Pull Request Workflow

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-pr
  cancel-in-progress: true

jobs:
  # FIXME revert
  E2E:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Checkout kestra
        uses: actions/checkout@v5
        with:
          path: kestra

      # Setup build
      - uses: kestra-io/actions/composite/setup-build@main
        name: Setup - Build
        id: build
        with:

          node-enabled: true
          python-enabled: true

      - name: Java - Setup
        uses: actions/setup-java@v4
        if: inputs.java-enabled == 'true'
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}

      - name: Java - Setup gradle
        if: inputs.java-enabled == 'true'
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-disabled: 'true'
          #        develocity-injection-enabled: ${{ inputs.java-enable-develocity-injection && secrets.DEVELOCITY_ACCESS_KEY }}
          develocity-url: https://develocity.kestra.io/
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
          dependency-graph: disabled

      - name: Install Npm dependencies
        run: |
          cd kestra/ui
          npm ci
          npx playwright install --with-deps chromium

      - name: Run E2E Tests
        run: |
          cd kestra
          sh build-and-start-e2e-tests.sh
