name: Publish docker

on:
  workflow_dispatch:
    inputs:
      retag-latest:
        description: 'Retag latest Docker images'
        required: true
        type: boolean
        default: false
      retag-lts:
        description: 'Retag LTS Docker images'
        required: true
        type: boolean
        default: false
      plugin-version:
        description: '(deprecated) Plugin version window for old Kestra releases using .plugins file (0.22 to 0.24). If omitted, then plugin list will be fetched from the API compatible versions endpoint'
        required: false
        type: string
        default: "[0.24,1.0)"
      dry-run:
        description: 'Dry run mode that will not write or release anything'
        required: true
        type: boolean
        default: false

jobs:
  publish-docker:
    name: Publish Docker
    if: startsWith(github.ref, 'refs/tags/v')
    uses: kestra-io/actions/.github/workflows/kestra-oss-publish-docker.yml@main
    with:
      plugin-version: ${{ inputs.plugin-version }}
      retag-latest: ${{ inputs.retag-latest }}
      retag-lts: ${{ inputs.retag-lts }}
      dry-run: ${{ inputs.dry-run }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
