name: Vulnerabilities Checks

on:
  schedule:
    - cron: "0 0 * * *"  # Every day
  workflow_dispatch: {}

env:
  JAVA_VERSION: '21'

permissions:
  contents: read

jobs:
  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Setup build
      - uses: kestra-io/actions/composite/setup-build@main
        id: build
        with:
          java-enabled: true
          node-enabled: true

      # Npm
      - name: Npm - Install
        shell: bash
        working-directory: ui
        run: npm ci

      # Run OWASP dependency check plugin
      - name: Gradle Dependency Check
        env:
          NVD_API_KEY: ${{ secrets.NIST_APIKEY }}
        run: |
          ./gradlew dependencyCheckAggregate

        # Upload dependency check report
      - name: Upload dependency check report
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: dependency-check-report
          path: build/reports/dependency-check-report.html
